### PR TITLE
[l10n] Add Norwegian nynorsk (nn-NO) locale and improve Norwegian bokmål (nb-NO) locale

### PR DESCRIPTION
**Pull request by AnderzL7**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

- Adds norwegian nynorsk (nnNO) locale to x-data-grid
- Finishes and improves norwegian bokmål (nbNO) locale for x-data-grid

### CODE REVIEW

**Comment by AnderzL7** [comment]
> ## Localization writing tips ✍️
> Seems you are updating localization 🌍 files.
> 
> Thank you for contributing to the localization! 🎉 To make your PR perfect, here is a list of elements to check: ✔️
> 
> * [ ]  Verify if the PR title respects the release format. Here are two examples (depending if you update or add a locale file)
>   > [l10n] Improve Swedish (sv-SE) locale
>   > [l10n] Add Danish (da-DK) locale
> * [ ]  Update the documentation of supported locales by running `pnpm l10n`
> * [ ]  Verify that you have added an export line in `src/locales/index.ts` for the new locale.
> * [ ]  Run `pnpm docs:api` which should add your new translation to the list of exported interfaces.
> * [ ]  Clean files with `pnpm prettier`.
> 
> **Deploy preview:** https://deploy-preview-13588--material-ui-x.netlify.app/
> 
> Generated by 🚫 [dangerJS](https://danger.systems/js) against [1790b1a](https://github.com/mui/mui-x/commit/1790b1a077ff65b6f4162af7ab178c5f150c61a0)



* [x]  Verify if the PR title respects the release format. 
* [x]  Update the documentation of supported locales by running `pnpm l10n`
* [x]  Verify that you have added an export line in `src/locales/index.ts` for the new locale.
* [x]  Run `pnpm docs:api` which should add your new translation to the list of exported interfaces.
* [x]  Clean files with `pnpm prettier`.

**Review by LukasTy — COMMENTED** [review]
Thank you for your contribution @AnderzL7! 🙏
 
Could you clarify if your use-case specifically requires Nynorsk translations or you are suggesting their addition for completeness? 🤔 

It looks like Nynorsk is somewhat rarely used [dialect of Norwegian language](https://en.wikipedia.org/wiki/Norwegian_language).
We would prefer avoiding introduction of very infrequently used dialects into the packages. 🤔

**Comment by AnderzL7** [comment]
> Thank you for your contribution @AnderzL7! 🙏
> 
> Could you clarify if your use-case specifically requires Nynorsk translations or you are suggesting their addition for completeness? 🤔
> 
> It looks like Nynorsk is somewhat rarely used [dialect of Norwegian language](https://en.wikipedia.org/wiki/Norwegian_language). We would prefer avoiding introduction of very infrequently used dialects into the packages. 🤔

Thank you for the response @LukasTy 

Norwegian Nynorsk is an official written language on the same level as the more widely used Norwegian Bokmål. [(From Wikipedia)](https://en.wikipedia.org/wiki/Nynorsk): Around 10-15% of Norwegians (myself included) have Norwegian Nynorsk as their official language form. Norwegian government organisations/news and similar is also required by law to have x-amount of their content in Norwegian Nynorsk. So even though less than 1 million people have the language as their official written language, not having support for the language could make it so that some Norwegian organisations are not able to use MUI due to being mandated by law to support both languages. 

The reason i made this pull request specifically is that i am currently making a website for a company that uses Norwegian Nynorsk as their written language. Having the language for completeness is also a valid argument, especially since it is listed in [Material-UI/locales](https://mui.com/material-ui/guides/localization/#supported-locales) as a supported locale. Having the same languages supported in material-ui and mui-x makes sense to make more people be able to use your solutions.

So the situation isn't that people will be unable to understand other languages. Norwegians, Swedes and Danes can mostly understand each others languages as well as most of the populations also being fluent in English. The problem arises when companies decides which language to use or are mandated to use and the styling library they want to use don't support that language.

I hope this was understandable and helps you understand the situation. 
If you want more information don't hesitate to reach out again :)

**Comment by LukasTy** [comment]
@AnderzL7 Thank you for confirming the situation. 👍 

The argument that `@mui/material` already has this locale is a strong one.
Given that case, I think that this suggestion makes complete sense. 👍 

I'm leaving the approval and merging honor to the @mui/xgrid team. 😉 

Nitpick: Having the improvement and introduction of the new locale in separate PRs would have made for a cleaner changelog (generation), but we are adjusting it manually anyway. 🙈 🤷 

P.S. I'll just mention, that not having the locale provided out of the box shouldn't be a deal breaker as you can provide your desired locale manually. 😉

**Comment by AnderzL7** [comment]
@LukasTy Yeah my bad for making the PR messy. I didn't realise nbNO needed improvements until I had already committed adding nnNO. 

I am aware you can provide your own locale, I was thinking more that the locale not being natively supported across all MUI packages could discourage someone from using MUI at all. 

Thx for agreeing to include nnNO in datagrid. Let me know if there are other mui packages you want help translating to nnNO to support the same locales across MUI.

**Comment by AnderzL7** [comment]
> > Let me know if there are other mui packages you want help translating to nnNO to support the same locales across MUI.
> 
> We appreciate your contributions and involvement. 🙏 If you have the time, [Pickers](https://github.com/mui/mui-x/tree/master/packages/x-date-pickers/src/locales) will now be the single package missing this particular locale. 🙈

@LukasTy I have now added a new PR to add nnNO to date-pickers as well [https://github.com/mui/mui-x/pull/13946](https://github.com/mui/mui-x/pull/13946)

**Review by romgrk — APPROVED** [review]

**Pull request merged**
