### PR TITLE
[DataGrid] Fix broken "start editing" integration with Japanese

### PR DESCRIPTION
**Pull request by mnajdova**
Fixes https://github.com/mui/mui-x/issues/4687

I also need this for fixing the build in https://github.com/mui/material-ui/pull/33196

### CODE REVIEW

**Review by DanailH — APPROVED** [review]

**Review by oliviertassinari — COMMENTED** [review]
It could be great to add a test case for this. It's the second time we iterate on the logic to fix a bug. The first time was in #1409. We also fix the logic with, say when typing "$12".

**Comment by mnajdova** [comment]
> It could be great to add a test case for this. It's the second time we iterate on the logic to fix a bug. The first time was in https://github.com/mui/mui-x/pull/1409. We also fix the logic with, say when typing "$12" into the cell.

Sure, makes sense. I was looking a bit at the test in `cellEditing.DataGridPro.new.test.tsx`, but looks like the test used directly the `apiRef.current.startCellEditMode` API. I may not have much context, but I was expecting that the tests would focus on the cell, simulate some key-down and validate that the editing has started. I am not sure where/what exactly the test should test out.

**Comment by flaviendelangle** [comment]
Feel free to open another PR for the test
I'm merging to unlock you in this release :+1:

**Comment by mnajdova** [comment]
> Feel free to open another PR for the test
I'm merging to unlock you in this release 👍

Thanks @flaviendelangle

**Comment by m4theushw** [comment]
> Sure, makes sense. I was looking a bit at the test in cellEditing.DataGridPro.new.test.tsx, but looks like the test used directly the apiRef.current.startCellEditMode API. I may not have much context, but I was expecting that the tests would focus on the cell, simulate some key-down and validate that the editing has started. I am not sure where/what exactly the test should test out.

This test file is divided into groups whose tests inside reproduce how the user would interact with the editing functionality. The first group is `apiRef` and it contains only tests checking the methods from the editing API. Here we test the behavior of `apiRef.current.startCellEditMode`, for example. It might be controversy to call API methods here but they're part of the public API, so users can call them directly. The group `start edit mode` is where we have tests simulating user interactions (e.g. keydown). Since we're already tested what the API methods do in the previous group, here we only check that they are called with the right params. Inside this group there're different groups equivalent to the different ways that users can interact with the API, e.g. by double-click, by pressing <kbd>Enter</kbd>, by **pressing a printable character** and so on.

The new test could be inside

https://github.com/mui/mui-x/blob/21c1f6c72838719536ba286551c56aa23f305109/packages/grid/x-data-grid-pro/src/tests/cellEditing.DataGridPro.new.test.tsx#L586-L587

**Pull request merged**
