### PR TITLE
[pickers] fix the issue of the timezone change in Day calendar

### LINKED ISSUE #12195: [pickers] Unable to set timezone in DatePicker
### Steps to reproduce

Link to live example: (required)

Steps:
1. Develop a date component with MUI X DatePicker in a form
2. Call an api and send api formdata in api payload , Open payload in network  tab  , you can see previous date is coming in payload.

### Current behavior

Previous date is coming in payload and also there is no props available to set timezone in DatePicker.

### Expected behavior

Selected date should be come and there should be timezone props to change date according to timezone.

### Context

_No response_

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: timezone,datepicker, UTC,

**Search keywords**:

### PR DESCRIPTION
**Pull request by shaharyar-shamshi**
fixes #12195

### CODE REVIEW

**Comment by shaharyar-shamshi** [comment]
Example code

```
import * as React from 'react';
import { DemoContainer } from '@mui/x-date-pickers/internals/demo';
import { LocalizationProvider } from '@mui/x-date-pickers-pro';
import { AdapterDayjs } from '@mui/x-date-pickers-pro/AdapterDayjs';
import { DateRangeCalendar } from '@mui/x-date-pickers-pro/DateRangeCalendar';
import dayjs from 'dayjs';
import utc from 'dayjs/plugin/utc';
import timezone from 'dayjs/plugin/timezone';

dayjs.extend(utc);
dayjs.extend(timezone);

export default function BasicDateRangeCalendar() {
  const [time, setTime] = React.useState('UTC');

  return (
    <>
      <div>
        <select onChange={(event) => setTime(event.target.value)}>
          <option value="UTC">UTC</option>
          <option value="America/New_York">America/New_York</option>
        </select>
      </div>
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        <DemoContainer components={['DateRangeCalendar']}>
          <DateRangeCalendar timezone={time} />
        </DemoContainer>
      </LocalizationProvider>
    </>
  );
}

```

```
import * as React from 'react';
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider';
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs';
import { DateCalendar } from '@mui/x-date-pickers/DateCalendar';

export default function BasicDateCalendar() {
  const [time, setTime] = React.useState('UTC');
  return (
    <>
      <div>
        <select onChange={(event) => setTime(event.target.value)}>
          <option value="UTC">UTC</option>
          <option value="America/New_York">America/New_York</option>
        </select>
      </div>
      <LocalizationProvider dateAdapter={AdapterDayjs}>
        <DateCalendar timezone={time} />
      </LocalizationProvider>
    </>
  );
}
```

**Comment by shaharyar-shamshi** [comment]
@LukasTy @michelengelen It seems to work I did some manual testing on this two example if you can also check manually I will add the test cases later.

Q) Why I consider this two example only ?
Answer) because DateCalendar and DateRangeCalendar internally uses DayCalendar

**Comment by shaharyar-shamshi** [comment]
@LukasTy @michelengelen is there any breaking change in the docs.I pulled next branch and 

did
1) yarn (to install dependency)
2) yarn start

unfortunately docs deployment is not working now

Screenshot 2024-03-01 at 1 34 31 PM

If you can help with this.

**Comment by shaharyar-shamshi** [comment]
> @LukasTy @michelengelen It seems to work I did some manual testing on this two example if you can also help in checking manually it would be great help. It is just sanity testing to check whether I am proceeding in right direction and didn't miss any case.
> 
> I will add the test cases later.
> 
> Q) Why I consider this two example only ? Answer) because DateCalendar and DateRangeCalendar internally uses DayCalendar

@michelengelen @LukasTy if you check it

**Comment by shaharyar-shamshi** [comment]
@LukasTy if you can review this now.

**Comment by shaharyar-shamshi** [comment]
@LukasTy If you can kindly review the PR. I assume argos failing test can be ignored as current image is correct.

**Comment by LukasTy** [comment]
@shaharyar-shamshi Thank you for taking your time on this issue.
I'm looking into it to identify if a bit more proper solution could be applied.
This looks like a fix for this one condition, it works and that's great, but we still don't know where else we might have a problem with the timezone not being updated when it is changed. 🙈

**Comment by shaharyar-shamshi** [comment]
> @shaharyar-shamshi Thank you for taking your time on this issue. I'm looking into it to identify if a bit more proper solution could be applied. This looks like a fix for this one condition, it works and that's great, but we still don't know where else we might have a problem with the timezone not being updated when it is changed. 🙈

I think problem is more of how we manage the timezone change. Timezone in itself work but major problem is how we are actually using that changed timezone. 

For example in this example timezone change was working correctly but we were not correctly handling the returned result by normalization. 

I am also checking other places where we might encounter similar kind of issue with timezone.

**Comment by LukasTy** [comment]
@shaharyar-shamshi I've created a PR (https://github.com/mui/mui-x/pull/12321), which, I think, solves the problem in a bit more reliable and correct way.
I think it supersedes this PR.
Feel free to check and review it. 😉

**Pull request closed without merging**
