### PR TITLE
[DataGrid] Prevent reopening column menu when clicking in the button while it is open

### PR DESCRIPTION
**Pull request by tanuj-22**
Closes https://github.com/mui/mui-x/issues/8251

Before: https://codesandbox.io/s/zud9od?file=/demo.tsx
After: https://codesandbox.io/s/pensive-bhabha-ov3y19

The fix added prevents calling `hideColumnMenu` if the button clicked is `kebab` icon that opens up column menu.

### CODE REVIEW

**Review by MBilalShafi — APPROVED** [review]
Thanks for the contribution @tanuj-22, adding a test case though will make sure the bug doesn't reproduce again

```diff
diff --git a/packages/grid/x-data-grid/src/tests/columnHeaders.DataGrid.test.tsx b/packages/grid/x-data-grid/src/tests/columnHeaders.DataGrid.test.tsx
index 16517952a..271cf2343 100644
--- a/packages/grid/x-data-grid/src/tests/columnHeaders.DataGrid.test.tsx
+++ b/packages/grid/x-data-grid/src/tests/columnHeaders.DataGrid.test.tsx
@@ -1,5 +1,5 @@
 import * as React from 'react';
-import { createRenderer, fireEvent, screen, within } from '@mui/monorepo/test/utils';
+import { createRenderer, fireEvent, screen, within, userEvent } from '@mui/monorepo/test/utils';
 import { expect } from 'chai';
 import { DataGrid } from '@mui/x-data-grid';
 import { getColumnHeaderCell, getColumnHeadersTextContent } from 'test/utils/helperFn';
@@ -50,7 +50,7 @@ describe('<DataGrid /> - Column Headers', () => {
     });
   });
 
-  describe('GridColumnHeaderMenu', () => {
+  describe('Column Menu', () => {
     it('should allow to hide column', () => {
       render(
         <div style={{ width: 300, height: 300 }}>
@@ -115,6 +115,25 @@ describe('<DataGrid /> - Column Headers', () => {
 
       expect(getColumnHeadersTextContent()).to.deep.equal(['id', 'brand']);
     });
+
+    it('menu icon button should close column menu when already open', async () => {
+      render(
+        <div style={{ width: 300, height: 500 }}>
+          <DataGrid
+            {...baselineProps}
+            columns={[{ field: 'brand' }]}
+          />
+        </div>,
+      );
+      
+      userEvent.mousePress(within(getColumnHeaderCell(0)).getByLabelText('Menu'));
+      clock.runToLast();
+      expect(screen.queryByRole('menu')).to.not.equal(null);
+
+      userEvent.mousePress(within(getColumnHeaderCell(0)).getByLabelText('Menu'));
+      clock.runToLast();
+      expect(screen.queryByRole('menu')).to.equal(null);
+    });
   });
 
   it('should display sort column menu items as per sortingOrder prop', () => {
```

**Comment by tanuj-22** [comment]
Thanks for the suggestion @MBilalShafi, I've added the test case for the bug.

**Comment by mrishabh062** [comment]
@tanuj-22 @MBilalShafi  I am using this version of datagrid "@mui/x-data-grid": "^5.8.0" and I can still see this race condition behavior, what should I do in order to solve it?

**Comment by MBilalShafi** [comment]
@mrishabh062 The fix is already merged but currently not released, it should be released by end of this week.

**Comment by mrishabh062** [comment]
Hi @MBilalShafi do I need to update my datagrid library for this?? Does it released?

**Comment by MBilalShafi** [comment]
Yes @mrishabh062 its released in [v6.0.4](https://github.com/mui/mui-x/releases/tag/v6.0.4), you can update your library to this version to access it.

**Pull request merged**
