### PR TITLE
[CalendarPicker] Don't move to closest enabled date when `props.date` contains a disabled date

### LINKED ISSUE #4705: [DatePicker] `shouldDisableDate` runs on all dates ever, not just visible ones before opening
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using `DesktopDatePicker` it runs `shouldDisableDate` on 100s of years of dates when first opening the modal. This delays the modal opening for several seconds. When switching between months, it only runs `shouldDisableDate` on the visible dates, which looks correct.

- Broken on first open
- Works great once it's already open

https://user-images.githubusercontent.com/6037887/151841250-8c85bcff-61b2-4a5d-84fe-bd59074a3e3d.mov

### Expected behavior 🤔

It should only run `shouldDisableDate` on the visible dates

### Steps to reproduce 🕹

Steps:

1. Create a `DesktopDatePicker` component with `shouldDisableDate` prop
2. Click on the calendar icon to open the date picker modal

```
<LocalizationProvider dateAdapter={AdapterDateFns}>
  <DatePicker
    label="Basic example"
    value={value}
    onChange={(newValue) => {
      setValue(newValue);
    }}
    shouldDisableDate={() => false} // this function will run on every date.
    renderInput={(params) => <TextField {...params} />}
  />
</LocalizationProvider>
```

### Context 🔦

We are creating invoicing software and only want dates to be selectable as a due date if they are on the correct billing day. This can be an expensive function for us to run if we need to pull additional data about exceptions. If it only runs on visible days there is almost no delay visible to the user, but if it's running on all historical dates then it ends up in 100s of network requests and slows down everything.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
 System:
    OS: macOS 12.1
  Binaries:
    Node: 14.1.0 - ~/.nvm/versions/node/v14.1.0/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v14.1.0/bin/npm
  Browsers:
    Chrome: 97.0.4692.99
    Edge: Not Found
    Firefox: 57.0.4
    Safari: 15.2
  npmPackages:
    @emotion/react: ^11.4.1 => 11.7.1 
    @emotion/styled: ^11.3.0 => 11.3.0 
    @mui/base:  5.0.0-alpha.66 
    @mui/core:  5.0.0-alpha.50 
    @mui/lab: ^5.0.0-alpha.66 => 5.0.0-alpha.66 
    @mui/material: ^5.0.3 => 5.0.3 
    @mui/private-theming:  5.0.1 
    @mui/styled-engine:  5.0.1 
    @mui/system:  5.0.3 
    @mui/types: ^7.0.0 => 7.0.0 
    @mui/utils:  5.0.1 
    @types/react:  17.0.11 
    react: 17.0.0 => 17.0.0 
    react-dom: 17.0.0 => 17.0.0 
    styled-components: ^4.4.0 => 4.4.1 
    typescript: ^4.1.3 => 4.3.4 
```
</details>

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixed #4705 for `master` (equivalent of #6146)

### CODE REVIEW

**Review by alexfauquette — APPROVED** [review]

**Comment by traverse** [comment]
Hello, this actually caused some tests to fail on my end. I'm wondering why this wasn't considered a breaking change?

**Comment by flaviendelangle** [comment]
It was considered a bug fix because the existing behavior could lead to UI freeze.

**Comment by traverse** [comment]
Thanks for your reply @flaviendelangle.

I can understand that this was considered a bugfix but this was existing behavior that people might've been relying on like I did. The fix on my end was pretty straightforward but I can imagine it also breaking things for other people.

I'm not sure how strictly MUI adheres to semver and I don't want to be pedantic about it but I would consider this a breaking change even if it was a bugfix.

**Comment by Aerophite** [comment]
Removal of this behavior has really messed up my application as we relied on this happening. Any suggestions on how to get this effect without me having to create all the logic myself? I tried importing your internals directly (which I don't really want to do) but that doesn't work since my project is in CRA and Jest within it can't import ESM scripts...

**Comment by flaviendelangle** [comment]
Hi,

Could you describe why this removal broke your application ?
We could add it back as an opt-in option with a warning saying that if the closest enable date is fare away, it will have terrible performances.

**Comment by Aerophite** [comment]
We have multiple date pickers within multiple rows that, when you select dates in other rows, disables dates for rows that will e created later. In some instances, this means that we disable entire months at a time in the past/future as well as "today". We were relying on this to switch, if "today" is disabled, move to the next available non-disabled date.

For example, if we disabled the past and this month, we'd have wanted it to select the first day of the next month.

**Comment by flaviendelangle** [comment]
In the past, the switch occurred when opening the picker.
Is this the intended behavior for you ?
Would it make sense to move to the closest enabled date on the picker's mount instead ?

**Comment by Aerophite** [comment]
We are only relying on it happening when the picker is opened. We wouldn't want it on mount since we would want to display previously input values, even if they are disabled now. For example, if we selected a date previously that is _now_ disabled, we wouldn't want that date to now start changing.

**Pull request merged**
