### PR TITLE
[core] Rely on immutable ref when possible

### PR DESCRIPTION
**Pull request by oliviertassinari**
Relates to https://github.com/mui/material-ui/pull/38762

### CODE REVIEW

**Review by romgrk — COMMENTED** [review]
I'm not sure about this change, it's more verbose and doesn't seem to change anything in practice. It's also not symmetric for the refs that have an agreed upon empty value (`useRef<Element[]>([])`).

**Comment by oliviertassinari** [comment]
Do you mean we don't need these changes in packages/grid/x-data-grid-pro/src/hooks/features/columnResize/useGridColumnResize.tsx as it's already a mutable ref without them? Yeah, we could do this, say that we treat null or undefined equality so we can be more concise for the demo, I do think it should be a immutable ref.

**Comment by romgrk** [comment]
Yes I'd prefer we keep `useGridResize` as it is for now. It's ok to change the demos.

**Review by romgrk — APPROVED** [review]

**Comment by oliviertassinari** [comment]
@romgrk Going forward, it would make sense to me to change the default value for mutable refs, to use undefined, over null.

**Pull request merged**
