### PR TITLE
[DataGrid] Trigger row spanning computation on rows update

### LINKED ISSUE #15819: [data grid] rowSpanning makes group header disappear [#2]
### Steps to reproduce

Steps:
1. Open this link to live example: [(required)](https://stackblitz.com/edit/react-kxed37-apfujuua?file=Demo.tsx,index.html)
On the example provided, press **UPDATE THE DATA** twice so second row is rendered while first is not

### Current behavior

**alias** field is not being rendered: empty

### Expected behavior

 **alias** field should render: rowSpanning should render **alias** value always even there's only one row of a kind. 

### Context

Related issue: https://github.com/mui/mui-x/issues/15261
Please don't close this one! The issue is obvious: alias column value not being rendered. 
Otherwise, if you exactly see how can this issue be resolved. Previous issue didn't help at all. 

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    System:
    OS: macOS 15.1.1
  Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 131.0.6778.109
    Edge: Not Found
    Safari: 18.1.1
  npmPackages:
    @emotion/react: ^11.4.1 => 11.11.4 
    @emotion/styled: ^11.3.0 => 11.11.5 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.16.7 
    @mui/icons-material: ^5.0.1 => 5.15.20 
    @mui/lab: ^5.0.0-alpha.49 => 5.0.0-alpha.170 
    @mui/material: ^5.0.2 => 5.16.7 
    @mui/private-theming:  5.16.6 
    @mui/styled-engine:  5.16.6 
    @mui/system:  5.16.7 
    @mui/types:  7.2.17 
    @mui/utils:  5.16.6 
    @mui/x-data-grid:  7.23.1 
    @mui/x-data-grid-pro: ^7.6.2 => 7.23.1 
    @mui/x-date-pickers: ^7.6.2 => 7.7.0 
    @mui/x-internals:  7.23.0 
    @mui/x-license:  7.23.0 
    @types/react: ^18.0.25 => 18.3.3 
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1 
    typescript: 5.2.2 => 5.2.2 
```

Used: Chrome: 131.0.6778.109
</details>

**Search keywords**: rowSpanning
**Order ID**: 60827

### PR DESCRIPTION
**Pull request by MBilalShafi**
Fixes #15819 
- Before: https://grfpfs.csb.app/
- After: https://wglxzl.csb.app/

Addresses a corner case, whenever rows get updated and the (index based) `range` doesn't change, it results in skipping the necessary re-computation of row spanning state.

- [x] Add test coverage

### CODE REVIEW

**Review by arminmeh — APPROVED** [review]

**Review by arminmeh — CHANGES_REQUESTED** [review]
In the after preview, after clicking couple of times, the rows are back, but they are combined anymore

**Comment by MBilalShafi** [comment]
Thank you @arminmeh for pointing it out.

There were two issues.
1. The demo didn't have `rowSpanning` prop passed 😄 
2. There was a more serious issue about the indexes of render context, which were designed in a way that the row spanning won't apply on a single row, which was intended in the beginning, since it doesn't make sense to span one row, but this corner case caused problem when we shuffle rows that have already a computed state.

Updated the [demo](https://wglxzl.csb.app/) and it seems to be working now.

**Review by arminmeh — APPROVED** [review]

**Review by cherniavskii — APPROVED** [review]

**Comment by kashyap-cephei** [comment]
Hi team,

I came across this thread and believe I'm experiencing a similar issue. When updating rows in the DataGrid, the row spanning computation doesn't seem to re-trigger if the index-based range remains unchanged.

I've recorded a short video showing the behavior. Could you please help confirm if this is the same issue as reported in #15819 and fixed in #15858?

Thank you for your assistance!


https://github.com/user-attachments/assets/2362ee80-3b55-4658-b664-391ddf3e7974

**Comment by cherniavskii** [comment]
Hey @kashyap-cephei 
It looks like the same issue, but it's hard to say based on a video.
I recommend you upgrade to https://github.com/mui/mui-x/releases/tag/v7.23.3 which includes the fix.
If you want to make sure the issue is fixed before upgrading – create a minimal reproduction example on Codesandbox/Stackblitz and try changing the data grid version in `package.json`. You can start with [this demo](https://mui.com/x/react-data-grid/row-spanning/#customizing-row-spanning-cells) by using Stackblitz/Codesandbox buttons under the demo.

**Pull request merged**
