### PR TITLE
[docs] Respect GoT books

### PR DESCRIPTION
**Pull request by janoma**
OCD request. Jamie and Cersei are twins, they should be the same age.

- [X] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by DanailH** [comment]
@janoma thanks for your contribution, but we can push this further. The correct age is 36 when the Game of Thrones first starts, or 43 during the last season, so you can choose either 36 or 43 as both are valid. Their book age tho is 31 which is also an option. 😜

Source: https://screenrant.com/game-thrones-characters-ages-how-old/#:~:text=Jaime%20%26%20Cersei%20Lannister%20%2D%2036%20Years%20Old&text=The%20book%20counterparts%20of%20the,31%20when%20the%20story%20began.

**Comment by janoma** [comment]
@DanailH haha fair enough. It's been around a decade since I read the books so those details are a bit vague by now. Still, I would prefer to use the book age since the age on the TV show is rarely part of the show itself, and it's usualy only available in some internal document that is submitted to justify which characters can have nude scenes and so on. Incidentally, that also explains why the show ages are so much higher, with so many characters being way under 18 in the books.

**Comment by janoma** [comment]
Updated patch branch, including Jon and Arya's ages. I left Daenerys' age unchanged as it illustrates a `null` in the table.

**Comment by DanailH** [comment]
> Updated patch branch, including Jon and Arya's ages. I left Daenerys' age unchanged as it illustrates a `null` in the table.

Awesome but can you also update the age in the other files to match the one in `[DataGridDemo.js](https://github.com/mui/mui-x/pull/11294/files#diff-664f6a8027a90b0bddcfb081a7a5b24e07822dbd49c30d34a1f8d19a5e551511)`.

**Review by alexfauquette — APPROVED** [review]
Thanks for the fix :+1: 😁

**Pull request merged**
