### PR TITLE
[charts] use ESM with imports

### PR DESCRIPTION
**Pull request by alexfauquette**
- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by alexfauquette** [comment]
@Janpot I think I found an intermediate solution by using the following config in the `package.json`

If I'm correct devs using the `import` will get ESM so no problem for them. Those using the `require` will get commonJS but in that case, they need a way to get the d3 in common JS

```json
  "exports": {
    ".": {
      "require": "./index.js",
      "import": "./esm/index.js"
    },
    "./*": {
      "require": "./*",
      "import": "./esm/*"
    }
  },
  ```

**Comment by Janpot** [comment]
I believe this would implement proposed strategy #2 from https://github.com/mui/material-ui/issues/37335

**Comment by Janpot** [comment]
Oh right, I see, we are not bundling at all, we're just transforming our input files. I'm sorry, that makes my suggestion a bit harder than I expected. I believe we have roughly the same options as described by https://formidable.com/blog/2022/victory-esm/. It's either becoming ESM-only or vendoring in d3. (unless not using d3 is also an option 🙂 )

(cc @mui/code-infra thoughts?)

**Comment by michaldudak** [comment]
As Charts are not stable yet, I believe we may use this package to verify the solution regarding ESM. If it proves to be painless for the community, we'll be more certain it won't cause major problems when eventually other packages follow the same pattern.

**Comment by oliviertassinari** [comment]
I have tried to prefix all the issues we have about publishing JavaScript to the best possible format with `[ESM]`: https://github.com/search?q=org%3Amui+%22%5BESM%5D%22++&type=issues&state=open.

Good luck https://blog.isquaredsoftware.com/2023/08/esm-modernization-lessons/ 😅

**Pull request merged**
