### PR TITLE
[docs] Sort Pickers & Charts API slots alphabetically

### PR DESCRIPTION
**Pull request by LukasTy**
Once again `api:docs` generation results have become flaky and sometimes keep failing in CI: https://app.circleci.com/pipelines/github/mui/mui-x/61920/workflows/b0db904d-129e-4379-9d5d-e7f23d837aea/jobs/353446.
Sorting them alphabetically would ensure this wouldn't happen. 🤔 

Also added the same sorting for the Charts package based on: https://github.com/mui/mui-x/pull/13843#issuecomment-2228310088

### CODE REVIEW

**Comment by JCQuintas** [comment]
I think this would be useful for charts as well 👍

**Comment by LukasTy** [comment]
> I think this would be useful for charts as well 👍

I just wanted to let you know, that flakiness has been observed only for Pickers previously and now again. 🤔 
Would you like me to add the sort for it? 🤔 
WDYT @alexfauquette?
What about @mui/xgrid? Do you like the existing order or do you feel having slots in alphabetical order would make more sense? 🤔

**Comment by JCQuintas** [comment]
We see it on charts too

**Comment by LukasTy** [comment]
> We see it on charts too, the flakiness

Oh, sorry, I didn't notice it then. 🙈

**Comment by JCQuintas** [comment]
@LukasTy it usually happens in the pull request themselves when we change import orders. Sometimes it creates a chain effect that changes a lot of files :(

**Comment by LukasTy** [comment]
> it usually happens in the pull request themselves when we change import orders. Sometimes it creates a chain effect that changes a lot of files :(

Gotcha. I've added Charts to the sorted list. 😉 
Let's wait for @alexfauquette and Grid input. 🤞

**Review by alexfauquette — APPROVED** [review]
It's ok for charts :+1:

Thanks for taking care of it :)

**Pull request merged**
