### PR TITLE
[docs] Fix links pointing to next.mui.com and update monorepo

### PR DESCRIPTION
**Pull request by alexfauquette**
In this PR I remove the markdown links that were pointing to next.mui.com

And I upgrade monorepo to get access to the PR https://github.com/mui/material-ui/pull/35078 which introduced the option to modify headers link into mui-x instead of having to to a PR in core

### CODE REVIEW

**Review by flaviendelangle — COMMENTED** [review]
Do we agree that the changes on `next.config.js` and `_app.js`just to be able to bump je monorepo ?

**Comment by alexfauquette** [comment]
- For the `_app.js` no, it's the fix that redirects to `mui.com` instead of `next.mui.com`
- For the `next.config.js` yes. I roughly follow the diff from our `Updtate monorepo` PRs. It includes:
	- the modification of the feedbacks management (new env variables)
	- the update of the markdown parser (I assume when it moved from docs to a dedicated monorepo package)

**Comment by flaviendelangle** [comment]
Sorry for the delay
I'll have a 2nd look once the CI is passing :+1:

**Comment by alexfauquette** [comment]
@flaviendelangle After searching, it seems the remaining error was due to the version of `@mui/base` not being enough advanced, because of the version of `@mui/joy`.

Since it's a versioning nightmare. I have another option which is to add a branch from the current `@mui/monorepo` (at `v5.11.12`) to update links assuming the monorepo will not have to be updated

**Comment by flaviendelangle** [comment]
> Since it's a versioning nightmare. I have another option which is to add a branch from the current @mui/monorepo (at v5.11.12) to update links assuming the monorepo will not have to be updated https://github.com/mui/mui-x/pull/9494

I'm fine with it
Yet another reason to stop this `@mui/monorepo` approach

**Pull request closed without merging**
