### PR TITLE
[data grid] Fix grid overlay aligment with scroll for RTL

### PR DESCRIPTION
**Pull request by kalyan90**
This PR is created to address https://github.com/mui/mui-x/issues/14289

Preview: https://deploy-preview-15072--material-ui-x.netlify.app/x/react-data-grid/overlays/

### CODE REVIEW

**Comment by kalyan90** [comment]
@romgrk @michelengelen please review the PR when you find sometime

**Comment by romgrk** [comment]
Code LGTM, PR not tested (waiting for the docs deploy to complete), once that's ok we can merge it.

**Comment by oliviertassinari** [comment]
I'm not sure, is the issue fixed?

https://github.com/user-attachments/assets/50576966-4b37-416b-8252-bf2a96d07ae0

https://deploy-preview-15072--material-ui-x.netlify.app/x/react-data-grid/overlays/#no-rows-overlay

**Comment by romgrk** [comment]
That's on chrome/macos? It works fine on chrome/linux:

https://github.com/user-attachments/assets/c3ed56a0-b97f-4853-9105-b79b15e7283f

**Comment by oliviertassinari** [comment]
@romgrk macOS/Chrome 130. Now, your screenshot is in LTR so it doesn't count 😄. I have tried on Windows/Chrome 130. It's broken too.

**Pull request merged**
