### PR TITLE
[DataGridPremium] Allow to customize grouping cell offset

### PR DESCRIPTION
**Pull request by cherniavskii**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Closes https://github.com/mui/mui-x/issues/9416

Preview: https://deploy-preview-9417--material-ui-x.netlify.app/x/react-data-grid/row-grouping/#customize-grouping-cell-indent

Instead of overriding `renderCell` for the grouping column, I've added the `offsetMultiplier` property to `groupingColDef`.

### CODE REVIEW

**Review by romgrk — APPROVED** [review]

**Comment by flaviendelangle** [comment]
An alternative approach would be to add an `ownerState` to `GridGroupingColumnLeafCell` and use it to compute the margin.
People could then override it using the state.

This has the benefit of not multiplying the col def properties for purely cosmetic purpose.

**Comment by cherniavskii** [comment]
> An alternative approach would be to add an ownerState to GridGroupingColumnLeafCell and use it to compute the margin.

This would only work for leaf cells, but not for grouping cells and footer cells. Also, the `GridGroupingColumnLeafCell` component is currently considered private and I would prefer to keep it like this unless there's a strong reason to make it public.

**Comment by flaviendelangle** [comment]
I was talking about `GridGroupingCriteriaCell` sorry, but the problem remains that it's not targeting all the cells you expect it to target (and it's private).

My main issue here is that this prop can not be discovered without the doc, which is not the best in term of DX.
And if I read `offsetMultiplier`, I have honestly no idea what that does unless I go read the doc to have the answer.

**Comment by cherniavskii** [comment]
> My main issue here is that this prop can not be discovered without the doc, which is not the best in term of DX.

Using `renderCell` for this isn't obvious either and you need docs for this as well 🤷🏻‍♂️

> And if I read offsetMultiplier, I have honestly no idea what that does unless I go read the doc to have the answer.

I think this is partially solved by TypeScript autocomplete + JSDoc:



Do you think `cellOffsetMultiplier` would be a better name for this option?

**Comment by flaviendelangle** [comment]
> Using renderCell for this isn't obvious either and you need docs for this as well 🤷🏻‍♂️

True, I'm not saying the current solution is better. It's probably a lot worse.
Ideally, I think styling should rely as much as possible on our regular styling APIs (`styled`, the theme `styleOverrides` etc...) because people know them and they are more likely to test them before going to the doc imho. But maybe for this topic it would be to much of a hassle.

> Do you think cellOffsetMultiplier would be a better name for this option?

I think it would indeed be interesting to have something in the name that refers to the rendering, to make clear that we are talking about the visual offset and not some offset in the data value.
`cellOffsetMultiplier` might do the trick.

**Comment by cherniavskii** [comment]
> Ideally, I think styling should rely as much as possible on our regular styling APIs (styled, the theme styleOverrides etc...) because people know them and they are more likely to test them before going to the doc imho.

I thought about this, I think we can use a CSS variable for the multiplier. This will improve the DX because you can discover it in the dev tools:

Screenshot 2023-07-21 at 14 10 31

And then override it:
```tsx
<DataGrid
  sx={{
    '--DataGrid-cellOffsetMultiplier': 2
  }}
/>
```

**Review by romgrk — APPROVED** [review]

**Comment by cherniavskii** [comment]
> Edit: Actually I was able to fix it by setting the style on the DataGrid directly.
>
> <DataGrid style={{ "--DataGrid-cellOffsetMultiplier": "2", }} ...

Yes, this is the correct usage: https://mui.com/x/react-data-grid/row-grouping/#customize-grouping-cell-indent

**Pull request merged**
