### PR TITLE
[docs] Mention Toolpad from the sidenav bar of X docs

### PR DESCRIPTION
**Pull request by prakhargupta1**
Opening this PR for discussion.

### CODE REVIEW

**Comment by alexfauquette** [comment]
For me that's confusing, because it puts toolpad like if it was a MUI X package

image


Compared to the core docs where each project has it's own title

image

But we could give it a try an track if it bring a valuable traffic. I f it does not, I would be in favor of not having it.
Or have explicitly as section "related projects" that would include material, tolpad, joy, ...

**Comment by prakhargupta1** [comment]
> For me that's confusing, because it puts toolpad like if it was a MUI X package

I agree, compared to the placement on Core docs, this one seems too upfront. 

@joserodolfofreitas Any alternate placement that you can suggest? Else we can skip it for now. When we'll have CRUD, we can link it as it may be more relevant.

**Comment by samuelsycamore** [comment]
I'm not a fan of this placement, for the same reasons that @alexfauquette pointed out. This makes it seem like Toolpad is part of X, and it also adds what feels like unnecessary overhead to the docs: now instead of just updating the Toolpad docs when something new is released, we also need to update the Material UI and MUI X docs.

If we want to try to promote Toolpad more in the X docs, I think a "Related projects" page in the MUI X Introduction section could be nice. As Alex said, we could include details on all of the MUI products to help X users better understand how they all relate.

**Comment by prakhargupta1** [comment]
I agree it will lead to confusion and a separate section will make more sense. I am closing this PR for now.

**Pull request closed without merging**
