### PR TITLE
[DataGrid] Fix scrollbar grabbing issue in Safari

### LINKED ISSUE #4360: Cannot grab vertical scroll
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

In a large table with vertical scrollbars, on MacOS configured with disappearing scrollbars, it's only possible to scroll using the mouse wheel. Even if the scroll bar appears, trying to grab it with the mouse pointer doesn't work. In fact, it seems to appear _behind_ the rows UI.

### Expected behavior 🤔

When the scrollbar appears (because maybe the scroll wheel has been used) it should be possible to grab the scroll bar, for a faster scrolling experience with very large tables.

### Steps to reproduce 🕹

Steps:

1. Configure MacOS System Preferences: General -> Show scroll bars -> "When scrolling"
2. Use Safari
3. Get a large table that requires scrolling
4. Activate scrolling with the scroll wheel, so that the scrollbar appears
5. Try to grab the scrollbar.

Screen Shot 2022-04-04 at 15 54 26

Screen Shot 2022-04-04 at 15 55 09

### Context 🔦

Speed up scrolling of very large tables. When you have 60k lines, it takes a while to wheel through to the end. It's much easier to just grab the scrollbar and get near the right spot.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
    Memory: 746.39 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - ~/.nvm/versions/node/v16.2.0/bin/node
    npm: 7.13.0 - ~/.nvm/versions/node/v16.2.0/bin/npm
  Managers:
    Homebrew: 3.4.4 - /usr/local/bin/brew
    Maven: 3.8.1 - /usr/local/bin/mvn
    pip3: 22.0.4 - ~/.pyenv/shims/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    CMake: 3.20.2 - /usr/local/bin/cmake
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.31.1 - /usr/local/bin/git
    Clang: 13.0.0 - /usr/bin/clang
    Mercurial: 6.1 - /usr/local/bin/hg
    FFmpeg: 5.0 - /usr/local/bin/ffmpeg
  Servers:
    Apache: 2.4.46 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.12 - /usr/local/bin/docker
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.0.1, iOS 15.0, macOS 12.0, tvOS 15.0, watchOS 8.0
  IDEs:
    IntelliJ: 2021.2.1
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/local/bin/vim
    Xcode: 13.1/13A1030d - /usr/bin/xcodebuild
  Languages:
    Bash: 5.1.8 - /usr/local/bin/bash
    Go: 1.16.3 - /usr/local/bin/go
    Perl: 5.30.2 - /usr/bin/perl
    PHP: 7.3.24 - /usr/bin/php
    Python: 2.7.16 - /Users/stefano/.pyenv/shims/python
    Python3: 3.9.12 - /Users/stefano/.pyenv/shims/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    MySQL: 5.7.34 - /usr/local/bin/mysql
    PostgreSQL: 11.15 - /usr/local/opt/postgresql@11/bin/postgres
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Brave Browser: 100.1.37.109
    Chrome: 100.0.4896.60
    Firefox: 98.0.1
    Safari: 14.1.1
```
</details>

### Order ID 💳 (optional)

#39493

### PR DESCRIPTION
**Pull request by cherniavskii**
Preview: https://deploy-preview-4405--material-ui-x.netlify.app/components/data-grid/#commercial-version

Closes #4360 

Before: 

https://user-images.githubusercontent.com/13808724/162418465-d58fa4df-e9a1-4156-9561-f4bbb9f9e885.mov

After:

https://user-images.githubusercontent.com/13808724/162440323-2e888f2d-d7ca-4df2-88fd-da1151f4f7a2.mov

### CODE REVIEW

**Comment by cherniavskii** [comment]
Ok, it broke a lot of things 🙃
Looking for a solution

**Comment by alexfauquette** [comment]
@cherniavskii Maybe it could be solved by modifying the `z-index` scroll bar
```jsx
'&::-webkit-scrollbar-thumb, & *::-webkit-scrollbar-thumb': { zIndex: 2 },
```

**Comment by cherniavskii** [comment]
Thanks, I've fixed it with `position: relative`

**Review by alexfauquette — APPROVED** [review]
Sounds good, I tested on the preview of the demo on Chrom and did not catch any problem on Chrome or Firefox 👍

**Comment by cherniavskii** [comment]
Wait, I think I missed something. It doesn't seem to fix the issue. I'll remove the "after" video and record a new one once it's 100% fixed

**Comment by m4theushw** [comment]
I tested on an old version of Safari and it fixes the issue where the borders appear on top of the scrollbar but I still can't click + drag. Have you found the root cause? Maybe disable the virtualization and see if the problem persists.

**Comment by cherniavskii** [comment]
Ok, it's fixed now. I've recorded a new video.
The root cause seems to be `position: relative` on virtual scroller content element. It's nested inside the element that has the scrollbar and in Safari this somehow made the scrollbar behind the content

**Review by m4theushw — APPROVED** [review]
Tested and it's fixed.

**Pull request merged**
