### PR TITLE
[pickers] Prevent daysweek transformation

### LINKED ISSUE #5330: Week days name in jalali calendar
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hi
As you see week day name use of day number with ش character which in the datepicker just display first letter of the week day name.

image

### Expected behavior 🤔

I want to config the `@date-io/date-fns-jalali` for change default week day names to full name. for example convert:

- ش to شنبه
- ۱ to یکشنبه
- ۲ to دوشنبه
.
.
.

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### LINKED ISSUE #5541: [pickers] Day of the week title (PickersCalendarDayHeader) is forced to truncate to the first char
### Current behavior 😯
The titles of the days of the week in the DayPicker are truncated to the first character, regardless of what the localized helper `getWeekdays` returns.

`children: day.charAt(0).toUpperCase()`

### Expected behavior 🤔
I propose to add an option to disable truncating of days titles or the ability to pass a custom `PickersCalendarDayHeader` component

### PR DESCRIPTION
**Pull request by rajdee**
Fixes #5330
Fixes #5541 

Add a `preventDaysWeekTransformation` prop to DatePickers API to prevent any transformation of calendar weekday titles.
Thus we can change the name of the days of the week using styles or by extending the adapter function.

Before:
Untitled-1

After:
after

### CODE REVIEW

**Comment by alexfauquette** [comment]
This address the same issues as #5373 but with a different approach

Both are nonbreaking changes. They only add an option to allow more than one character

- This one is easier to understand for dev, seems it's a boolean
- #5373 is more flexible since it adds a callback to allow custom formating of the day without having to modify the library or the adapter

**Comment by rajdee** [comment]
@alexfauquette Thank you for your comment!
I wanted to simplify the interface as much as possible so that there were more chances that this PR was accepted :)
Ideally, I would like to add the ability to use a custom component with the original array of weekday names as prop

**Comment by m4theushw** [comment]
I'm in favor of going with the approach from #5373. If we only add a new prop, users will still not be able to fully customize the header labels. But adding both (new prop to disable the transformation and the prop to customize the formatter) it may pollute the component's interface.

**Comment by m4theushw** [comment]
Superseded by #5373, but thanks for the contribution.

**Pull request closed without merging**
