### PR TITLE
[charts] Update Tooltip style

### PR DESCRIPTION
**Pull request by alexfauquette**
Implement the new default styling of tooltip

https://www.figma.com/design/upttiqJUQYGUu3xo6w7COx/Design-refinement?node-id=46-515&node-type=frame&t=kk9pUO7rSFzQXLYG-0

## Some before/after screenshots

| before | after |
| --- | --- |
| image | image |
| image | image | 
| image | image | 
| image | image | 

## Changelog

- The default styling of the charts tooltip has been updated.

### CODE REVIEW

**Review by JCQuintas — COMMENTED** [review]
This deals with the 

- "popper" styles
- removing the shadow around the "series colors"
- decreasing whitespace around values

What is missing

- Different "color indicator" shapes for different graphs
- I feel like the first picture should me more similar to [this](https://www.figma.com/design/upttiqJUQYGUu3xo6w7COx/Design-refinement?node-id=46-445&node-type=frame&t=ESYb7Adp2eF9f7Kx-0) but @noraleonte should be able to confirm 😃

**Comment by noraleonte** [comment]
Looks like a nice first step towards the redesign 🎉 🚀 

I'm fine with doing the `different "color indicator" shapes for different graphs` in a follow-up 👌 

> I agree mine feels a bit weird. Maybe a min-width could solve that

Yes, I would definitely add a min width to the tooltip. The new design should work well both with 'smaller' labels and longer ones. Spacing it out with a min-width could solve this 🙈 
A few additional notes: 
- What font-sizes do we use for the labels? They feel a bit bloated to me 🤔 
- Are we using Roboto for the charts? The font-family looks off to me... Not sure if the plan for charts is to go towards a more material-ish default, but maybe we should use the same font-family as in the other component libraries
image

**Comment by JCQuintas** [comment]
> * using Roboto

Yeah they use the same style, but one is rendered in SVG and the other in HTML, so there are some differences there 🙃

**Review by JCQuintas — APPROVED** [review]

**Comment by JCQuintas** [comment]
I intend to do a pass on tooltips after legends are done. So we can use the correct mark shapes.

**Pull request merged**
