### PR TITLE
[DataGridPremium] Remove last line break on clipboard paste

### PR DESCRIPTION
**Pull request by cherniavskii**
Fixes https://github.com/mui/mui-x/issues/9103

### CODE REVIEW

**Comment by simonesanna1983** [comment]
Hi Guys,

do you know when it will be released in production?
Thanks in advance.

Cheers.
  Simone

**Comment by cherniavskii** [comment]
Hey @simonesanna1983 
We don't have an ETA, but you can use [this workaround](https://github.com/mui/mui-x/issues/9103#issuecomment-1568303386) until it's released 🙂

**Review by MBilalShafi — COMMENTED** [review]
Not related to this PR: I am wondering if it's a common use case to copy and paste empty cells, it might be helpful to bulk-delete cells and could that be a reason AgGrid hasn't enabled that flag by default?

aggrid-cp

What do you think?

**Review by MBilalShafi — APPROVED** [review]

**Comment by cherniavskii** [comment]
I think this PR doesn't prevent us from supporting empty cell copy/paste.
I don't know if it's common or not though 🤷🏻‍♂️ No problems adding it if requested 🙂

**Pull request merged**
