### PR TITLE
[core] Reduce the amount of updated screenshots reported by Argos

### PR DESCRIPTION
**Pull request by cherniavskii**
Backport of https://github.com/mui/mui-x/pull/6099 and https://github.com/mui/mui-x/pull/6032
The goal is to reduce the amount of changes detected by Argos when submitting PRs to master.

Before: https://app.argos-ci.com/mui/mui-x/builds/4255
Screenshot 2022-09-27 at 17 37 04

After: https://app.argos-ci.com/mui/mui-x/builds/4285
Screenshot 2022-09-27 at 18 42 15

### CODE REVIEW

**Review by DanailH — APPROVED** [review]
This is a cherry-pick from of the commits against `next`, right? The number of files changed seems to be the same.

**Comment by cherniavskii** [comment]
@DanailH 
> This is a cherry-pick from of the commits against next, right?

Yes, I cherry-picked merge commits from the `next` branch

> The number of files changed seems to be the same.

Do you mean changes in Argos? The amount of updated screenshots is down from 22 to 3

**Comment by DanailH** [comment]
> Do you mean changes in Argos? The amount of updated screenshots is down from 22 to 3

No I meant the git diff.

**Comment by cherniavskii** [comment]
@DanailH There's [3 commits](https://github.com/mui/mui-x/pull/6310/commits):
- cherry-picked merge commit from https://github.com/mui/mui-x/pull/6099
- cherry-picked merge commit from https://github.com/mui/mui-x/pull/6032
- few manually picked changes from https://github.com/mui/mui-x/pull/5999 to reduce the amount of updated screenshots

So the amount of files changed is different that in https://github.com/mui/mui-x/pull/6099, but it's expected

**Comment by flaviendelangle** [comment]
> few manually picked changes from https://github.com/mui/mui-x/pull/5999 to reduce the amount of updated screenshots

I can confirm that the changes picked from this PR are compatible with v5
It's just demo on which we forgot to spread the initial state so it was still using the old `hide` api.

**Pull request merged**
