### PR TITLE
[charts] smoother path animation

### PR DESCRIPTION
**Pull request by romgrk**
I was checking the charts and I noticed the path is animated via a clipping mask rather than a path animation. You could use this technique to animate it more smoothly. It uses `SVGPath.getPointAtLength(n: number)` to create an animated path from a set of linear segments that sample the original path every N pixels.

| before | after |
| --- | --- |
| [Screencast from 2024-04-26 08-31-31.webm](https://github.com/mui/mui-x/assets/1423607/ef7c041b-6474-4b16-850d-daad1c756f31) | [Screencast from 2024-04-26 08-33-48.webm](https://github.com/mui/mui-x/assets/1423607/fd1cf4d6-9d32-4091-b96f-eda6c31e61f4) |

### CODE REVIEW

**Comment by alexfauquette** [comment]
The initial reason why using the mask was to share it with the marks, without having to do any computation to know if a mark is at a place for which the line is already visible or not. Trying to avoid this intermediate state where marks are visible but not the line

image

**Comment by romgrk** [comment]
Didn't notice. With the points data, adding the mask back would be quite simple: `maskRect.width = points[current].x - points[0].x`. I also see in argos that disjointed paths will need some special handling. Lmk what you think of the approach, if you're fine with it I'll do those changes.

**Comment by alexfauquette** [comment]
> Lmk what you think of the approach, if you're fine with it I'll do those changes.

I'm not sure about this PR, because it seems more complex than the dummy clipping and I fear it adds more edge cases to handle. Maybe it's because I don't have a strong design sensibility, but the ratio UI improvement vs the risk of adding something complex to maintain does not feel good.

Moreover, it seems to deteriorate performances when rendering the line chart for the first time:

I checked in the [docs preview](https://deploy-preview-12918--material-ui-x.netlify.app/x/react-charts/lines/#using-a-dataset) performances when resetting a demo and it shows some blocking time that I don't see in production
image


I tried in codesandbox with a state to toggle with/without data and this PR adds a delay to show the data

- with the current package: https://codesandbox.io/p/sandbox/crazy-pasteur-2wm7w8?file=%2Fsrc%2FDemo.tsx%3A21%2C18-22%2C26
- with this PR build: https://codesandbox.io/p/sandbox/polished-wind-f4l6nr?file=%2Fsrc%2FDemo.tsx%3A14%2C18

**Comment by alexfauquette** [comment]
I spotted a usecase where it would make more sense: plotting a line in a scatter plot

image

In that case, the clip does not work and we can accept to pay the extra computation cost to have the animation

**Comment by alexfauquette** [comment]
Thanks for the additional investigation :pray:

**Pull request closed without merging**
