### PR TITLE
[github] Do not add `plan: Pro` and `plan: Premium` labels on pro / premium issue templates

### PR DESCRIPTION
**Pull request by flaviendelangle**
This is a follow up on a conversation we had with @oliviertassinari a few weeks ago.

The labels `plan: Pro` and `plan: Premium` should refer to the content of the issue, not to the nature of the user creating it.
For example, an issue about row pinning should have `plan: Pro` even though its user has a premium license.

This is how the label is being used by @oliviertassinari and I agree that it make more sense because technically any issue can impact a Pro / Premium user.

I updated the label descriptions (feel free to improve them) and I'm removing them from the pro / premium  issue templates since those are also used to create issues related to features not in the maximum available plan of the user.

### CODE REVIEW

**Review by LukasTy — APPROVED** [review]
The solution and explanation does make sense to me. 👍

**Comment by cherniavskii** [comment]
I believe we need to reflect the user's plan in the issue somehow so that we can prioritize them accordingly.
Maybe keep the `plan: ...` labels and add `scope: Pro` and `scope: Premium`?

**Comment by flaviendelangle** [comment]
For me this is achieved by `support: commercial` and `support: priority` which are describing the level of priority we should apply (none < `support: commercial` < `support: priority`)

**Comment by flaviendelangle** [comment]
Indeed, according to the pricing page we need a "support: commercial pro" and "support: commercial premium".
@oliviertassinari @joserodolfofreitas do you confirm?

**Review by oliviertassinari — COMMENTED** [review]
> Indeed, according to the pricing page we need a "support: commercial pro" and "support: commercial premium". do you confirm?

@flaviendelangle Ah yes, sorry for the delay. I'm adding @michelengelen to this discussion, as I think responsible for this scope.

The changes proposed here make sense to me, they are aligned with https://github.com/mui/mui-x/issues/10488. However, they are a bit too early.

**Comment by michelengelen** [comment]
> > Indeed, according to the pricing page we need a "support: commercial pro" and "support: commercial premium". do you confirm?
> 
> @flaviendelangle Ah yes, sorry for the delay. I'm adding @michelengelen to this discussion, as I think responsible for this scope.

IMO this is a nice improvement, but I guess we can trim down the naming a bit:

(`support: community` <) `support: pro` < `support: premium` (< `support: priority`)

Adding `support: community` would help in filtering, searching and collecting metrics (TBD)
---
Additionally having a scoping label would be great, but this can probably only be added manually:

`scope: community` < `scope: prop` < `scope: premium`

> 
> The changes proposed here make sense to me, they are aligned with step 5. of #10488.
> 
> Note that today, the templates are broken, we have this in GitHub: https://www.notion.so/mui-org/GitHub-labels-af1ef18d3f534f1dbc086aac87b819e8?p=5af1eb7e28eb4c9ebbe20b77cbfc9307&pm=s but this in the issue template:
> 
> https://github.com/mui/mui-x/blob/3f5d36d29cfc63ee10fa5594d27402dabca21d1c/.github/ISSUE_TEMPLATE/3.pro-support.yml?plain=1#L4
> 
> I see 3 possible ways forward with this PR:
> 
> 1. We fix the GitHub issue template by using the right labels
> 2. We update the GitHub issue template by removing the dead labels
> 3. We update the GitHub issue template and introduce these new labels (support: commercial pro" and "support: commercial premium") or (support: pro standard, support: premium standard)
> 
> I think they all make sense, they are all broken in their own ways. Maybe I would go with 2. just for the sake of being closer to the goal and creating an incentive to fix the workflow [#whynot](https://www.notion.so/mui-org/Olivier-Tassinari-a6d0f1d19f8a4cfbb20469878ded8aa8?pvs=4#9bee9ebf3e74404db876eab5462ca547).

In favor of my proposal I would go with option 3, but take in the labels mentioned above. They are a bit more precise and reduce noise.

**Pull request merged**
