### PR TITLE
[fields] Fix Android editing

### PR DESCRIPTION
**Pull request by flaviendelangle**
Part of #7440

In Android, we have 2 `onChange`, for the 1st one we need to just store the result as is in the input.
Since the RTL PR, we were storing the clean value (without the RTL characters), which was causing shift in the edited layout on the 2nd `onChange`.

### CODE REVIEW

**Review by alexfauquette — APPROVED** [review]
It was hard to reproduce. I don't have the bug with Gboard. 

What about adding a test to catch this error?

**Comment by flaviendelangle** [comment]
Do you have an idea of how to test those Android-only behaviors ?

**Comment by flaviendelangle** [comment]
I added two tests :+1:

**Comment by oliviertassinari** [comment]
@flaviendelangle Thanks for looking into it 👌. 

I noticed two other things:

1. https://next.mui.com/x/react-date-pickers/date-field/#customize-the-date-format

https://user-images.githubusercontent.com/3165635/216845789-f4837f75-9fc9-4817-ae3b-eac50238ffc8.mov

2. https://next.mui.com/x/react-date-pickers/date-field/#customize-the-date-format

https://user-images.githubusercontent.com/3165635/216845986-893b299e-69bb-4966-bfb6-4f0f9222e924.mov

It can be reproduced on https://live.browserstack.com/dashboard#os=android&os_version=12.0&device=Samsung+Galaxy+S22&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fy2jlm1.csb.app%2F&speed=1&host_ports=google.com%2C80%2C0.

**Comment by flaviendelangle** [comment]
Bug reproduced, that's not specific to Android, I'll investigate

**Comment by flaviendelangle** [comment]
2nd bug reproduced.
This one is interesting. The `Backspace` logic is not handled by the `onChange` to it does not work on Android...
I created #7835 because it's not a trivial change.

**Pull request merged**
