### PR TITLE
[DataGrid] Provide a clear error message when upgrading

### PR DESCRIPTION
**Pull request by oliviertassinari**
I copied a community demo, but wanted to use the pro package, so I changed the import: https://codesandbox.io/s/exciting-sara-4euipo?file=/demo.tsx which fails with an obscure error message:

Screenshot 2022-10-30 at 13 30 45

and TypeScript doesn't help:

Screenshot 2022-10-30 at 13 31 02

For a moment, I wondered what I did wrong. I had forgotten the component name is different. So I concluded that if it happened to me, it could happen to other existing users.

---

### After

https://codesandbox.io/s/crazy-tu-iubwwq

Screenshot 2022-10-30 at 13 45 40

Screenshot 2022-10-30 at 13 48 10

Screenshot 2022-10-30 at 13 48 04

For the error message, I followed https://www.notion.so/mui-org/Technical-writing-7e55b517ac2e489a9ddb6d0f6dd765de#85219822c3194b6f8a49ee08ea82b90a. I almost wonder if doing the same for the downgrade path wouldn't make sense as well, but I didn't implement it.

### CODE REVIEW

**Comment by cherniavskii** [comment]
What if we use `DataGrid` component name in pro and premium packages instead?
If I recall correctly, it's the only one that is exported under different names depending on the package.
For example, importing `GridToolbar` component works regardless of the package.

**Comment by oliviertassinari** [comment]
@cherniavskii If I recall correctly, the initial idea was to use different names when the API signature is different.

**Comment by cherniavskii** [comment]
> the initial idea was to use different names when the API signature is different.

We can keep the same name and mark the pro/premium props as we do in `GridApi` docs: https://mui.com/x/api/data-grid/grid-api/

**Review by cherniavskii — APPROVED** [review]

**Comment by oliviertassinari** [comment]
> We can keep the same name and mark the pro/premium props as we do in GridApi docs

@cherniavskii I have tried to search in the history for this. Unfortunately, we didn't document this very well.

It might have been a meeting decision. The initial name separation was introduced in #26. In #30 I challenged a bit the naming structure. In #2313, we changed the name for MUI rebranding and pricing release, which was discussed in https://www.notion.so/mui-org/Shipping-the-high-tier-plan-782c6648a4ae4a0491a3d17d65087546.

Beyond having different signatures, a different name allows clarity on the plan used. I think that we can keep this topic open, we might see values as we move forward to change the naming strategy.

**Pull request merged**
