### PR TITLE
[DataGridPro] Apply default properties if they are not passed in a reorder column

### LINKED ISSUE #14057: [data grid] Custom Row Reorder Column Definition omits built-in CSS Classes
### Latest version

- [X] I have tested the latest version

### Steps to reproduce

Link to live example: https://codesandbox.io/s/nifty-scooby-gf4tlc?file=/src/Demo.tsx

Steps:
1. Notice that the drag handle in the priority column is not centered.
2. If you inspect the priority column, you'll notice the cell div does not have the `MuiDataGrid-rowReorderCellContainer` class name on it.

### Current behavior

The `MuiDataGrid-rowReorderCellContainer` className is not being applied when using a custom column  definition  for the reorder column. I believe the problem stems from this code:

https://github.com/mui/mui-x/blob/630acb5595371eac0648fd7f1bea60a429351f69/packages/x-data-grid-pro/src/hooks/features/rowReorder/useGridRowReorderPreProcessors.ts#L33-L45

If a custom column has been passed, the class names don't get added to that column definition.

### Expected behavior

It should be applied so I don' t have to do it manually.

### Context

I want to provide a custom column definition as demonstrated in the documentation, but I'd like to keep a lot of the built-in styling.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 14.5
  Binaries:
    Node: 20.12.1 - ~/.nvm/versions/node/v20.12.1/bin/node
    npm: 10.8.2 - ~/Developer/component-library/node_modules/.bin/npm
    pnpm: Not Found
  Browsers:
    Chrome: 127.0.6533.89
    Edge: 127.0.2651.74
    Safari: 17.5
  npmPackages:
    @emotion/react: ^11.7.1 => 11.13.0 
    @emotion/styled: ^11.6.0 => 11.13.0 
    @mui/base:  5.0.0-beta.40 
    @mui/core-downloads-tracker:  5.16.5 
    @mui/icons-material: ^5.11.16 => 5.16.5 
    @mui/lab: 5.0.0-alpha.173 => 5.0.0-alpha.173 
    @mui/material: ^5.16.5 => 5.16.5 
    @mui/private-theming:  5.16.5 
    @mui/styled-engine:  5.16.4 
    @mui/system:  5.16.5 
    @mui/types:  7.2.15 
    @mui/utils:  5.16.5 
    @mui/x-data-grid:  7.11.1 
    @mui/x-data-grid-premium: ^7.4.0 => 7.11.1 
    @mui/x-data-grid-pro:  7.11.1 
    @mui/x-date-pickers: ^7.0.0 => 7.11.1 
    @mui/x-date-pickers-pro: ^7.0.0 => 7.11.1 
    @mui/x-internals:  7.11.1 
    @mui/x-license: ^7.0.0 => 7.11.1 
    @types/react: ^18.2.79 => 18.3.3 
    react: ^18.2.0 => 18.3.1 
    react-dom: ^18.2.0 => 18.3.1 
    typescript: ^5.2.2 => 5.5.4 
```
</details>

**Search keywords**: row reorder custom column
**Order ID**: 0332927583

### PR DESCRIPTION
**Pull request by k-rajat19**
Fixes #14057 

that's how we did it  in case of [row selection](https://github.com/mui/mui-x/blob/master/packages/x-data-grid/src/hooks/features/rowSelection/useGridRowSelectionPreProcessors.ts#L52-L56)

Before : https://codesandbox.io/s/nifty-scooby-gf4tlc?file=/src/Demo.tsx
After : https://codesandbox.io/p/sandbox/mui-mui-x-x-data-grid-forked-st8h4g

### CODE REVIEW

**Comment by k-rajat19** [comment]
@cherniavskii  could this be merged? :)

**Comment by k-rajat19** [comment]
@MBilalShafi could this be merged ?
let me know if any changes need to be made :)

**Comment by k-rajat19** [comment]
@MBilalShafi can you review these changes? this will not take much time as these are very small changes :)

**Comment by k-rajat19** [comment]
Hi @MBilalShafi,
can we merge these changes, let me know if I missed something

**Comment by MBilalShafi** [comment]
Hey @k-rajat19,

Apologies for the delay. I'll take a look at the PR later this week.

**Comment by k-rajat19** [comment]
Okay, thanks for letting me know

**Comment by k-rajat19** [comment]
Hi @MBilalShafi, sorry for the ping again 
It's a weekend and by any chance if you have some energy left to review this?
I have updated  PR description to make this a bit easier to review

**Comment by k-rajat19** [comment]
Hi @MBilalShafi ,
Are there any plans to merge this?

**Review by MBilalShafi — APPROVED** [review]
LGTM

**Pull request merged**
