### PR TITLE
[DateRangePicker] Fix calendar day outside of month layout shifting on hover

### PR DESCRIPTION
**Pull request by alexfauquette**
When moving to the slot, the DateRangeDay is adding styles to empty grid cells which leads to some inconsistencies

Here is a record of the problem when moving the mouse hover the cell

https://user-images.githubusercontent.com/45398769/194884995-50e17774-e6fd-4bfa-86cb-187e119775c5.mp4

The reason is that on hover the cell adds a 1px border. We do not see it because component are hidden, but it modifies the layout

### CODE REVIEW

**Comment by flaviendelangle** [comment]
```diff
diff --git a/packages/x-date-pickers/src/PickersDay/PickersDay.tsx b/packages/x-date-pickers/src/PickersDay/PickersDay.tsx
index ea562295f..9191d61f4 100644
--- a/packages/x-date-pickers/src/PickersDay/PickersDay.tsx
+++ b/packages/x-date-pickers/src/PickersDay/PickersDay.tsx
@@ -184,6 +184,7 @@ const PickersDayFiller = styled('div', {
   ...styleArg({ theme, ownerState }),
   // visibility: 'hidden' does not work here as it hides the element from screen readers as well
   opacity: 0,
+  pointerEvents: 'none',
 }));
```

The following also fixes the problem, if you don't want the `DateRangePickersDay` to know why a day is hidden or not.

**Comment by LukasTy** [comment]
Is it still a problem?
I struggle to reproduce the issue on latest `next` 🤷

**Comment by alexfauquette** [comment]
I do not manage to reproduce it either. But Flavien's proposal makes sense even if the bug has been solved by an unknown commit.
Hidden element should not react to the pointer

**Comment by flaviendelangle** [comment]
I can still reproduce it with a `DateRangeCalendar`

**Comment by alexfauquette** [comment]
I confirm I can reproduce it (and the PR solves the bug) with 

```jsx
import * as React from 'react';
import { DateRangeCalendar } from '@mui/x-date-pickers-pro/DateRangeCalendar/index';
import { LocalizationProvider } from '@mui/x-date-pickers-pro'
import { AdapterDayjs } from '@mui/x-date-pickers-pro/AdapterDayjs'

export default function PlaygroundExample() {
  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <DateRangeCalendar />
    </LocalizationProvider>
  );
}
```

Can not be done in codesandbox because `DateRangeCalendar` is not currently exported

**Review by LukasTy — APPROVED** [review]

**Comment by LukasTy** [comment]
Proposal for a PR title change:
`[DateRangePicker] Fix calendar day outside of month layout shifting on hover`

**Pull request merged**
