### PR TITLE
[l10n] Add Czech (cs-CZ) locale 

### PR DESCRIPTION
**Pull request by LukasTy**
Cherry-pick #7645

### CODE REVIEW

**Comment by OndrejHj04** [comment]
Hi, the translation is complete, but I cant push a commit to this PR. I am getting a git fatal. Maybe I am doing something wrong cause I am not a proficient GitHub user 😅.

**Comment by OndrejHj04** [comment]
Feel free to add the transation by yourself 😉.
`
const pickerViews = {
  calendar: 'kalendáře',
  clock: 'času',
};
.......


  inputModeToggleButtonAriaLabel: (isKeyboardInputOpen: boolean, viewType: 'calendar' | 'clock') =>
    isKeyboardInputOpen
      ? `zobrazení pro zadávání textu je otevřené, přepněte do zobrazení ${pickerViews[viewType]}`
      : `zobrazení ${pickerViews[viewType]} je otevřené, přepněte do zobrazení textového pole`,
`

**Comment by LukasTy** [comment]
> Hi, the translation is complete, but I cant push a commit to this PR. I am getting a git fatal. Maybe I am doing something wrong cause I am not a proficient GitHub user 😅.

Have you tried adding my repo as an additional remote and pushing to it?
```sh
git remote add LukasTy https://github.com/LukasTy/mui-x.git
```

**Review by OndrejHj04 — COMMENTED** [review]
Yes, that is perfect. 🚀

**Pull request merged**
