### PR TITLE
[DataGrid] Do not publish `rowEditStop` event if row has fields with errors

### PR DESCRIPTION
**Pull request by cherniavskii**
Fixes https://github.com/mui/mui-x/issues/11263
- Before: https://codesandbox.io/p/sandbox/inspiring-dijkstra-g2h52p?file=%2Fsrc%2Fdemo.tsx%3A123%2C25-123%2C43
- After: https://codesandbox.io/p/sandbox/gracious-babycat-8y68c9?file=%2Fsrc%2Fdemo.tsx%3A123%2C25-123%2C43

TODO:
- [x] Add unit tests

### CODE REVIEW

**Comment by lauri865** [comment]
Does this prevent `processRowUpdate` from being called as well? If so, it'll break a lot of things in our custom validator implementation that shows validation errors also in viewing mode, and I'm not sure if there's a good alternative to that.

**Review by michelengelen — APPROVED** [review]
super solid! LGTM! :shipit:

**Comment by michelengelen** [comment]
@lauri865 this will only prevent the `rowEditStop` event to be fired, when there are fields with errors present. Correct @cherniavskii ?

**Comment by cherniavskii** [comment]
@lauri865 `processRowUpdate` is not being called if the row has fields in error state - see https://codesandbox.io/p/sandbox/nostalgic-paper-wyyv28?file=%2Fsrc%2FDemo.tsx%3A19%2C21

If you're not using `preProcessEditCellProps` and only rely on `processRowUpdate` for validation - it should be OK.
The server-side validation demo works as before: https://deploy-preview-11383--material-ui-x.netlify.app/x/react-data-grid/editing/#server-side-validation

**Review by MBilalShafi — APPROVED** [review]

**Comment by cherniavskii** [comment]
Let's wait a bit for @lauri865's feedback on this to make sure we're not breaking anything 🙂
@lauri865 Could you confirm my points in https://github.com/mui/mui-x/pull/11383#issuecomment-1857052758?

**Comment by cherniavskii** [comment]
@lauri865

> So, thanks to that it will not break things for us luckily.

Great, I'll push this PR forward then!

> The problem is that both onCellEditStop and onRowEditStop don't include the latest value

Could you open a new issue for this discussion? A minimal reproduction example would be great!

**Review by romgrk — APPROVED** [review]

**Pull request merged**
