### PR TITLE
[docs] Add unsorted icon slot to the custom sort icons demo

### PR DESCRIPTION
**Pull request by d4rekanguok**
- Add example for overriding `columnUnsortedIcon` slot
- Set sort model using initial state to demonstrate the custom icons

You can verify the updated code example here: https://codesandbox.io/s/long-wood-9x48w7?file=/demo.tsx

### CODE REVIEW

**Comment by d4rekanguok** [comment]
I can't figure out how to make the code example show up (like in this screenshot:)
image

Running `yarn docs:typescript:formatted` seems to have removed the `CustomSortIcons.tsx.preview` file, I added it back in local but it still doesn't show up:
image

Am I missing something? Also not sure why the regression test failed — some help would be appreciated

**Comment by d4rekanguok** [comment]
Thanks for clarifying! I agree the improvement is not significant. When I opened this I was very new to MUI and this example tripped me off:

- by default, there's no difference between 'unsorted column on hover' and 'sorted column in ascending order', so when a user click the column header, it seems like nothing had happened
- the example implies columns are sortable, but the way `sortModel` was initiated in the example, clicking on the column doesn't do anything

Given that this example is strictly on icon override, I think it makes sense to leave it the way it was.

**Comment by alexfauquette** [comment]
I let maintainers of the data grid answer

**Review by cherniavskii — APPROVED** [review]
@d4rekanguok Thank you!

**Pull request merged**
