### PR TITLE
[charts] Add watermark on the pro `ResponsiveChartContainer`

### PR DESCRIPTION
**Pull request by alexfauquette**
I'm hesitating between reexporting the container like I'm currently doing (`<ResponsiveChartContainer />`), or exporting them with a pro suffix `<ResponsiveChartContainerPro />`.

@flaviendelangle Do you have some insight on this aspect? the reexport only add watermark, and it's still unsure if we will add behavior to this component

### CODE REVIEW

**Comment by flaviendelangle** [comment]
> I'm hesitating between reexporting the container like I'm currently doing (<ResponsiveChartContainerPro />), or exporting them with a pro suffix <ResponsiveChartContainerPro />.

Sorry but I don't understand the difference :laughing:

**Comment by alexfauquette** [comment]
> Sorry but I don't understand the difference 😆

😅 Effectively, I copy pasted the same

- ResponsiveChartContainer: current solution (same naming but component with a watermark)
- ResponsiveChartContainerPro: other solution (different naming but only user-facing difference is the watermark)

**Comment by JCQuintas** [comment]
We should probably follow what the other packages do

**Comment by JCQuintas** [comment]
But I noticed each package does a different thing 😅

**Comment by JCQuintas** [comment]
I would probably go with the DataGrid solution if we want to always load the new functionalities on the `Pro` package. This means disallowing the use of `ResponsiveChartContainer`

**Comment by flaviendelangle** [comment]
If people **need** to use the pro version (which is the case here), I'd keep the `Pro` suffix to avoid confusion and somehow prevent users from user the community one.

**Review by JCQuintas — APPROVED** [review]
Looks good, should we also block the use of the `ResponsiveChartContainer`?

**Comment by alexfauquette** [comment]
> should we also block the use of the ResponsiveChartContainer?

The `ResponsiveChartContainer` and `ChartContainer` are not exported by the `@mui/x-charts-pro` :+1:

**Pull request merged**
