### PR TITLE
[DataGrid] Fix dev warning about `InputLabelProps`

### LINKED ISSUE #9335: [DataGrid] Header filters warning: React does not recognize the `InputLabelProps` prop on a DOM element
### Steps to reproduce 🕹

https://codesandbox.io/s/affectionate-liskov-3vqysg?file=/demo.tsx

### Current behavior 😯

This warning is logged to the console:

```
Warning: React does not recognize the `InputLabelProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `inputlabelprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at eval (https://3vqysg.csb.app/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:62:23)
    at InputBase (https://3vqysg.csb.app/node_modules/@mui/material/InputBase/InputBase.js:185:43)
    at Input (https://3vqysg.csb.app/node_modules/@mui/material/Input/Input.js:108:43)
    at eval (https://3vqysg.csb.app/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:62:23)
    at Select (https://3vqysg.csb.app/node_modules/@mui/material/Select/Select.js:54:43)
    at div
    at eval (https://3vqysg.csb.app/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:62:23)
    at FormControl (https://3vqysg.csb.app/node_modules/@mui/material/FormControl/FormControl.js:62:43)
    at div
    at eval (https://3vqysg.csb.app/node_modules/@emotion/react/dist/emotion-element-48d2c2e4.cjs.dev.js:62:23)
    at GridFilterInputBoolean (https://3vqysg.csb.app/node_modules/@mui/x-data-grid/components/panel/filterPanel/GridFilterInputBoolean.js:37:16)
    at div
    at eval (https://3vqysg.csb.app/node_modules/@mui/x-data-grid-pro/components/headerFiltering/GridHeaderFilterCell.js:46:20)
    [cropped]
```

### Expected behavior 🤔

No warning

### Context 🔦

_No response_

### Your environment 🌎

v6.7.0

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by romgrk**
Closes #9335

image

### CODE REVIEW

**Review by MBilalShafi — APPROVED** [review]

**Comment by RavenHursT** [comment]
Is there any way to tell if this fix has been included in a release as of yet? If so, which version?

**Comment by RavenHursT** [comment]
nm.. found it.. 

`v6.15.0`

https://github.com/mui/mui-x/releases/tag/v6.15.0

**Comment by RavenHursT** [comment]
Oh for cryin' out loud... 

https://www.npmjs.com/package/@mui/material?activeTab=versions

🤦

**Comment by RavenHursT** [comment]
Ahh.. mah bad.. Did not realize that MUI is a separate package from MUI base. 

#TIL

**Pull request merged**
