### PR TITLE
[DataGrid] Fix for cell focus preventing scroll when virtualization enabled

### LINKED ISSUE #6378: [DataGridPro] Unable to scroll back up to open row detail panel
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When I expand a row [detail panel](https://mui.com/x/react-data-grid/master-detail/) and scroll down to view more grid rows, I am unable to scroll back up to the expanded detail panel.

https://user-images.githubusercontent.com/1140141/193750897-bf08b146-fd8b-4e1b-be7b-0f7928cba1c4.mov

### Expected behavior 🤔

I expect to be able to scroll the grid up and down as normal, even when one or more detail panels are expanded.

### Steps to reproduce 🕹

I am only able to reproduce this issue in Chrome.

Link to live example:

https://codesandbox.io/s/rough-wave-xnv5i4?file=/demo.tsx

Steps:
1. Expand a row detail panel and leave it open
2. Scroll down enough rows (~20?) that the detail panel moves well outside of the grid
3. Slowly scroll back up toward the open detail panel
4. Notice that as you approach the detail panel, the scroll location of the grid will jump back down, so that you never actually see it

### Context 🔦

This is blocking adoption of the MUI DataGridPro in our codebase because our existing grids have expandable row details, and our users would perceive this scroll bug as a regression in our product.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
 System:
    OS: macOS 12.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 48.52 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.16.0 - ~/.asdf/installs/nodejs/16.16.0/bin/node
    Yarn: 1.22.19 - ~/.asdf/shims/yarn
    npm: 8.11.0 - ~/.asdf/plugins/nodejs/shims/npm
  Managers:
    Homebrew: 3.5.1 - /usr/local/bin/brew
    pip3: 21.2.3 - ~/ff/work/dev/shims/python/pip3
    RubyGems: 3.0.3.1 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 12.1. - /usr/bin/gcc
    Git: 2.36.1 - /usr/local/bin/git
    Clang: 13.0.0 - /usr/bin/clang
  Servers:
    Apache: 2.4.51 - /usr/sbin/apachectl
  Virtualization:
    Docker: 20.10.16 - /usr/local/bin/docker
  IDEs:
    IntelliJ: 2021.2.3
    Nano: 2.0.6 - /usr/bin/nano
    Vim: 8.2 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Go: 1.18.4 - /Users/phillipsaenz/ff/work/dev/shims/golang/go
    Java: 11.0.16 - /Users/phillipsaenz/.asdf/shims/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python: 3.9.7 - /Users/phillipsaenz/ff/work/dev/shims/python/python
    Python3: 3.9.7 - /Users/phillipsaenz/ff/work/dev/shims/python/python3
    Ruby: 2.6.8 - /usr/bin/ruby
  Databases:
    SQLite: 3.36.0 - /usr/bin/sqlite3
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 105.0.1
    Safari: 15.2

```
</details>

### Order ID 💳 (optional)

40131

### PR DESCRIPTION
**Pull request by yaredtsy**
Fixes #6378
Fixes https://github.com/mui/mui-x/issues/5006

Preview: https://deploy-preview-6622--material-ui-x.netlify.app/x/react-data-grid/virtualization/

**Trade-offs**
using `useLayoutEffect` might prevent flickering while using `focus`. but it is also causing major problems. It prevents users from scrolling when virtualization is enabled. changing it to `useEffect` fix the problem

https://user-images.githubusercontent.com/34584266/197604364-5d1bff9f-8ebf-4e99-a51c-4dbb076c87ec.mov

Solution demo: https://codesandbox.io/s/clever-gould-qztsm2?file=/demo.tsx

TODO:
- [ ] @cherniavskii port to the `next` branch

### CODE REVIEW

**Review by cherniavskii — COMMENTED** [review]
Thanks!
Seems to work fine.

Using `.focus()` in `useLayoutEffect` makes sense if we expect scroll, since it allows to avoid flickering.
But since we call `.focus({ preventScroll: true })` I think using `useEffect` is fine.

But I don't really understand why there's scroll jump with `useLayoutEffect` and how does `useEffect` solve it

**Comment by cherniavskii** [comment]
We still have the issue reproducible with `actions` cell and checkbox selection cell:

https://github.com/mui/mui-x/blob/5357eb9a7ab58521b1f76678763b7311658b9e93/packages/grid/x-data-grid/src/components/cell/GridActionsCell.tsx#L76

https://github.com/mui/mui-x/blob/5357eb9a7ab58521b1f76678763b7311658b9e93/packages/grid/x-data-grid/src/components/columnSelection/GridCellCheckboxRenderer.tsx#L71

**Comment by yaredtsy** [comment]
hi, @cherniavskii I have tested them since  ` preventScroll: false` on both of them when the cell mount they are scrolled into view automatically. is there a reason it's set to false? 
demo: https://codesandbox.io/s/clever-gould-qztsm2?file=/demo.tsx

**Comment by oliviertassinari** [comment]
> But since we call .focus({ preventScroll: true }) I think using useEffect is fine.

I think that we should remove `preventScroll` because it should scroll.

**Comment by yaredtsy** [comment]
@oliviertassinari for keyboard navigation ` apiRef.current.scrollToIndexes` is the one scrolling to the cell not the `focus()`. i think this solved https://github.com/mui/mui-x/issues/4282

**Comment by yaredtsy** [comment]
demo https://codesandbox.io/s/clever-gould-qztsm2?file=/package.json. everything seems to be working fine.
Should I look for another way to fix this issue?

**Comment by oliviertassinari** [comment]
> for keyboard navigation apiRef.current.scrollToIndexes is the one scrolling to the cell not the focus(). i think this solved https://github.com/mui/mui-x/issues/4282

@yaredtsy To be clear: #4282 is about scrolling the body (not the data grid scroll container) to get the cell into the viewport.

> We still need to call .focus({ preventScroll: true }) on cell mount, because otherwise we would loose focus outline on the cells that were removed from DOM due to virtualization and then added back.

@cherniavskii I see, arf, tricky problem!

**Comment by yaredtsy** [comment]
@oliviertassinari  oh I see it now. I think I can fix it.

**Comment by yaredtsy** [comment]
@oliviertassinari  I have created PR #6838

**Comment by oliviertassinari** [comment]
@cherniavskii This was merged on the `master` branch, was it expected?

**Comment by cherniavskii** [comment]
@oliviertassinari I've ported it to `next` in https://github.com/mui/mui-x/pull/6785

**Pull request merged**
