### PR TITLE
[docs] Update RTL Support section on Data Grid

### LINKED ISSUE #9552: [docs] Update RTL Support section of the Localization docs
Since #230 is already done, it needs to be reflected on https://mui.com/x/react-data-grid/localization/#rtl-support section so that people start using it and providing feedback.

### PR DESCRIPTION
**Pull request by richbustos**
### What? 
Update RTL Support section of the Localization docs.
Fix #9552

### Before
Screen Shot 2023-07-17 at 4 15 48 PM

### After
Screen Shot 2023-07-17 at 4 15 11 PM

https://deploy-preview-9710--material-ui-x.netlify.app/x/react-data-grid/localization/#rtl-support

### CODE REVIEW

**Comment by richbustos** [comment]
**Follow-up question**
The link directs users to material ui docs. Do we care? 

Should we create a separate page that lives in mui.com/x that explains "RTL"? 

My thoughts are "no". IT will basically have the same exact information on how to use "RTL"

**Comment by oliviertassinari** [comment]
I suspect that a working demo like https://ag-grid.com/react-data-grid/rtl/ or like https://mui.com/material-ui/guides/right-to-left/#demo could make the difference. I suspect that not everyone knows about the toggle:

Screenshot 2023-07-18 at 01 56 58

**Comment by richbustos** [comment]
> I suspect that a working demo like https://ag-grid.com/react-data-grid/rtl/ or like https://mui.com/material-ui/guides/right-to-left/#demo could make the difference. I suspect that not everyone knows about the toggle:
> 
> Screenshot 2023-07-18 at 01 56 58
> However, it wouldn't make sense to add this to all the components, overkill, maybe only the data grid as a flag ship.

Will save this for another PR. I think the current PR will suffice for now. Spoke to @MBilalShafi on slack, we will go this this route first.

**Comment by MBilalShafi** [comment]
I [tried](https://github.com/mui/mui-x/pull/9710/commits/5938f06c6cca8792e3a36aec488bf9d4fe44e120) to add an example of an RTL language usage to make it a little bit more accessible. What do you think?

@richbustos Side note, wouldn't it be better to raise the PR from your personal fork though as mentioned in [contribution guidelines](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#your-first-pull-request), or am I missing something here?

(Sorry for the huge commit list, it's coming from the `master` 😄I can revert to the previous commit and cherry-pick the one with examples.)

**Comment by MBilalShafi** [comment]
@richbustos Would it be better to open another PR from the personal fork? I can do it if it's OK with you?
Also, what do you think about the [demo](https://deploy-preview-9710--material-ui-x.netlify.app/x/react-data-grid/localization/#rtl-support) I added?

**Comment by richbustos** [comment]
> @richbustos Would it be better to open another PR from the personal fork? I can do it if it's OK with you? Also, what do you think about the [demo](https://deploy-preview-9710--material-ui-x.netlify.app/x/react-data-grid/localization/#rtl-support) I added?

Demo looks great! Ill close this PR for now as I think it is outdated.

**Pull request closed without merging**
