### PR TITLE
[DataGrid] Remove `rowPositionsDebounceMs` prop

### PR DESCRIPTION
**Pull request by k-rajat19**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Closes https://github.com/mui/mui-x/issues/15480

### Breaking changes

- The `rowPositionsDebounceMs` prop was removed.

### CODE REVIEW

**Review by arminmeh — CHANGES_REQUESTED** [review]
@k-rajat19 you have to add changelog entry for the breaking change and to update the migration guide stating that this API is removed

You can use https://github.com/mui/mui-x/pull/15523 as a guidance

**Comment by romgrk** [comment]
Right, but just the migration guide no? The changelog is autogenerated from PRs.

**Comment by arminmeh** [comment]
> Right, but just the migration guide no? The changelog is autogenerated from PRs.

Yeah, I meant to add Changelog in the PR description, not in the file.
Didn't explain that properly 😅

**Comment by arminmeh** [comment]
@k-rajat19 I did the necessary updates and approved the PR

**Pull request merged**
