### PR TITLE
[core] Remove Firefox from the BrowserStack list

### PR DESCRIPTION
**Pull request by DanailH**
After discussing it with @m4theushw and @flaviendelangle we have decided that due to the flakiness of the tests run on Firefox that we will remove Firefox from the BrowserStack list (for not). This should not impact the overall stability of the code as we haven't had a case yet where this helped us catch a regression or bug.
We might add it back in the future if the problem is resolved.

Note: If removing Firefox doesn't solve the problem with the away as failed build on master we also discussed disabling the BrowserStack step altogether. For now, we will see if this PR solves the problem.

### CODE REVIEW

**Review by flaviendelangle — APPROVED** [review]

**Comment by oliviertassinari** [comment]
> Note: If removing Firefox doesn't solve the problem with the away as failed build on master we also discussed disabling the BrowserStack step altogether.

Yeah, IMHO, we have learned that steps of the CI that only run on master are useless. So I think that the decision to drop BrowserStack was therefore taken the day we removed it from each PR to master.

The CI still looks unreliable. Looking at the failing test, it seems that the test is simply not passing:

Screenshot 2022-08-25 at 01 29 42

**Comment by oliviertassinari** [comment]
Toolpad seems to run Firefox inside CircleCI directly, without Docker:

https://app.circleci.com/pipelines/github/mui/mui-toolpad/2700/workflows/b0637190-1b36-4154-ba12-8246d4f6d2d4/jobs/9576

Screenshot 2022-08-25 at 12 22 43

cc @apedroferreira who is looking into running the e2e test of Toolpad inside Firefox.

**Comment by cherniavskii** [comment]
I wouldn't agree that tests in Firefox are flaky, it's more like a bottleneck in Browserstack - `test_browser` on master mostly fails because of the Browserstack connection timeout, not only with Firefox:

```
Safari 13.1.2 (Mac OS 10.15.6) ERROR
  Disconnected , because no message in 360000 ms.
Safari 13.1.2 (Mac OS 10.15.6): Executed 0 of 0 DISCONNECTED (6 mins 0.002 secs / 0 secs)

Edge 91.0.864.37 (Windows 10) ERROR
  Disconnected reconnect failed before timeout of 180000ms (transport close)
Edge 91.0.864.37 (Windows 10): Executed 989 of 1571 (skipped 11) DISCONNECTED (6 mins 14.83 secs / 3 mins 1.842 secs)

```

Recent examples:
https://app.circleci.com/pipelines/github/mui/mui-x/22678/workflows/e60b8ff0-2cd8-470a-a40c-43f1a37d54e9/jobs/130784
https://app.circleci.com/pipelines/github/mui/mui-x/22662/workflows/4bb6603d-e32d-4db3-beb2-8ae9152ac282/jobs/130697
https://app.circleci.com/pipelines/github/mui/mui-x/22656/workflows/e6afd25a-c020-4a17-9e6e-ce259e0196d1/jobs/130664

As for regressions - running tests in Firefox 78 did help to spot a bug once in https://github.com/mui/mui-x/pull/5066
But the cost is far higher than the actual value it gives.

But in general, I'm in favor of removing BrowserStack integration on master for faster and more reliable CI pipeline

**Comment by oliviertassinari** [comment]
I have added the topic of the next step as a possible discussion point for the next X - Engineering meeting: https://www.notion.so/mui-org/b02c32f9f5b7426c84a654aaba99d0ab?v=4414e4f2ac5142ecba4615e1fea3f7e3.

**Pull request merged**
