### PR TITLE
[DataGrid] Add `toggleAllMode` prop to the `columnsManagement` slot

### PR DESCRIPTION
**Pull request by H999**
I think the toggle columns visibility panel should have work on showing columns when we have text search on `GridPanelHeader`, so I add a flag call `toggleAllWithSearch` to work with that scenario
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by cherniavskii** [comment]
Hi @H999 
I'm not sure I understand the use case here.
Why would you want to hide columns in the list, but show them during search?
It doesn't seem to be a good UX to be honest..

**Comment by H999** [comment]
> Hi @H999 I'm not sure I understand the use case here. Why would you want to hide columns in the list, but show them during search? It doesn't seem to be a good UX to be honest..

Hi @cherniavskii, I face this use case when my table have **NUMEROUS** cols, and when user want toggle only some cols when in search they must toggle each of it, because your toggle all (on/off) effect the all cols.
ex; cols = ["col-sx0", "col-sx1", "col-sx2", "col-sx3", "col-sy0", "col-sy1", "col-sy2", "col-sy3"] => search sx => toggle (on/off) sx0, sx1, sx2, sx3
current your action when click toggle all: effect on cols
I think it should only effect in what visible on you search
in cmt I left as you see: the `toggleAllWithSearch` if true will do with logic I discuss, and now it default to false to effect on all cols as current

**Comment by cherniavskii** [comment]
Ah, I see now what it does 👍🏻
It's hard to find a good name for the prop though.
I'm thinking about something like this:

```tsx
/**
  * Changes the behavior of the "Show all" and "Hide all" buttons when the search field is used.
  * - `all`: The buttons will toggle all columns.
  * - `filtered`: The buttons will toggle only the columns that match the search criteria.
  * @default 'all'
  */
toggleAllMode: 'all' | 'filtered';
```

What do you think?

**Comment by cherniavskii** [comment]
I've updated the PR:
- changed the prop signature to `toggleAllMode?: 'all' | 'filteredOnly';`
- added unit test
- added a demo: https://deploy-preview-10794--material-ui-x.netlify.app/x/react-data-grid/column-visibility/#customize-action-buttons-behavior-when-search-is-active

**Review by cherniavskii — APPROVED** [review]

**Comment by MBilalShafi** [comment]
Need to update this behavior for the new columns panel design. I'll work on this in a while. @H999, if you want to work on it meanwhile, please feel free to do so.

**Comment by H999** [comment]
> Need to update this behavior for the [new columns panel design](https://github.com/mui/mui-x/pull/11770). I'll work on this in a while. @H999, if you want to work on it meanwhile, please feel free to do so.

I'm not sure how effective it is for others when I fix conflicts. On the other hand, I have some busy tasks here, so there's a high possibility that this pull request will be waiting for you. Thanks.

**Comment by cherniavskii** [comment]
Thanks @MBilalShafi!

**Comment by MBilalShafi** [comment]
@cherniavskii Due to merge conflicts, this couldn't be auto `cherry-pick`'d to master. Do we want to back-port it?

**Comment by cherniavskii** [comment]
@H999 Do you need this change in v6 of the data grid?

**Comment by H999** [comment]
> @H999 Do you need this change in v6 of the data grid?

First, thanks about merged this feat into your awesome repo.
And I'm no rush this feat in official release, I already have it in custom component, so feel free about time.
Thanks.

**Pull request merged**
