### PR TITLE
[Data grid] Fix excessive white space at the end of grid

### PR DESCRIPTION
**Pull request by kalyan90**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

This PR is created to address https://github.com/mui/mui-x/issues/14816

Unable to attach labels to the PR, can someone please help with attaching the component: data grid & bug & docs labels

### CODE REVIEW

**Comment by kalyan90** [comment]
@romgrk can you please look at these changes when you have time?

**Review by romgrk — APPROVED** [review]

**Comment by romgrk** [comment]
Did you have a reproduction case to test this with? Could you share it here in a codesandbox? You can fork a codesandbox from any example from the docs in the [deploy for this PR](https://github.com/mui/mui-x/pull/14864#issuecomment-2397771799).

**Comment by kalyan90** [comment]
@romgrk it is replicable on the docs https://mui.com/x/react-data-grid/demo/.
Also argos CI step was failing please help with that

**Comment by romgrk** [comment]
Where in the docs?

**Comment by kalyan90** [comment]
[Uploading screen-capture (1).webm…]()

recording for reference

**Comment by romgrk** [comment]
I can't reproduce on chrome/linux with the demo in that recording, although I can reproduce the original issue at https://mui.com/material-ui/getting-started/templates/dashboard/.

Is there a way you could isolate the issue on the template dashboard and put it in a codesandbox? The code change makes sense, but I don't have a way to test that the issue is fixed.  
Alternatively, maybe someone else on macOS can reproduce the issue @mui/xgrid?

**Comment by kalyan90** [comment]
@romgrk Can you help me with the codesandbox, I tried to publish my own version of x-data-grid package and tried to use that. That didn't help.
https://codesandbox.io/p/sandbox/cranky-river-zvdr3t?file=%2Fcomponents%2FCustomizedDataGrid.tsx%3A4%2C1&from-embed=&workspaceId=da680cdb-77a3-4ab2-8045-3eb83f570a91
https://www.npmjs.com/package/kalyan90-x-data-grid

**Review by cherniavskii — APPROVED** [review]

**Comment by kalyan90** [comment]
@cherniavskii @romgrk I don't have write access, can you please help merge the PR

**Pull request merged**
