### PR TITLE
[DateRangePicker] Fix keyboard selection

### LINKED ISSUE #5231: [DateRangePicker] Not possible to enter a date with keyboard
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Trying to enter a date with the keyboard behaves very strange. Here is a video demonstrating the issue with the on-screen-keyboard, using the official example:

https://user-images.githubusercontent.com/25102041/174170290-ea9a795c-363c-440f-9a5a-413d9a4dcc56.mp4

Problem also occurs in my local project setup (see environment below)

The first keystroke is completely swallowed and has to be pressed again. For the year, zeros are suddenly added after the first two digits. When trying to delete the input again, the numbers shift in a strange way. Conclusion: A year that is valid today cannot be entered.

Occurs in all browsers you can possibly think of 😅 

### Expected behavior 🤔

Should behave like the normal DatePicker. Example is working.

### Steps to reproduce 🕹

see video above

or

1. go to https://codesandbox.io/s/re4kxh?file=/demo.tsx or https://mui.com/x/react-date-pickers/date-range-picker/
2. focus the check-in or check-out field
3. try to enter any date with the keyboard (e.g. 07/11/2022)

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
System:
    OS: macOS 12.3.1
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Edge: Not Found
    Firefox: 100.0
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.7.1 => 11.7.1 
    @emotion/styled: ^11.6.0 => 11.6.0 
    @mui/base:  5.0.0-alpha.68 
    @mui/icons-material: ^5.4.1 => 5.4.1 
    @mui/lab: ^5.0.0-alpha.73 => 5.0.0-alpha.73 
    @mui/material: ^5.4.1 => 5.4.1 
    @mui/private-theming:  5.6.2 
    @mui/styled-engine:  5.4.1 
    @mui/styles:  5.6.2 
    @mui/system:  5.4.1 
    @mui/types:  7.1.3 
    @mui/utils:  5.4.1 
    @mui/x-date-pickers: ^5.0.0-alpha.6 => 5.0.0-alpha.6 
    @mui/x-date-pickers-pro: ^5.0.0-alpha.6 => 5.0.0-alpha.6 
    @mui/x-license-pro:  5.12.1 
    @types/react: ^17.0.39 => 17.0.39 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript: ~4.4.3 => 4.4.4
```
</details>

### Order ID 💳 (optional)

_No response_

### LINKED ISSUE #5284: [StaticDateRangePicker] Mobile Date inputs add leading zeros to the year.
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

When using the StaticDateRangePicker width displayStaticWrapperAs={"mobile"}, typing in a date on the mobile inputs works up until typing the year. The cursor seems to throw the user to the end of the year and doesn't allow for typing in an entire year. The component will then trigger the error state. For example, trying to type 06/05/2020 would result in 06/05/0002 and an invalid field message.

### Expected behavior 🤔

The StaticDateRangePicker mobile view should allow typing of a full date without injecting leading zeros into the YYYY part of the date.

### Steps to reproduce 🕹

Steps:
[CodeSandbox](https://codesandbox.io/s/staticdaterangepickerdemo-demo-mui-x-forked-heur0p?file=/demo.tsx)

1. Open the CodeSandbox
2. Click the pencil icon to change to the mobile input view.
3. Click in the first input and type a full date that has 4 digits in the year.

Component will switch focus out of the input and not allow the full typing of a year in YYYY format.

### Context 🔦

We are developing a graph date range selection tool for our product and noticed this issue when QA ran across it in testing.
Tested in Safari iOS and Chrome 102.0.5005.61.

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

 System:
    OS: macOS 10.15.7
  Binaries:
    Node: 14.16.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.1.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 102.0.5005.115
    Edge: Not Found
    Firefox: 87.0
    Safari: 15.4
  npmPackages:
    @emotion/react: ^11.9.0 => 11.9.3 
    @emotion/styled: ^11.8.1 => 11.9.3 
    @mui/base:  5.0.0-alpha.84 
    @mui/icons-material: ^5.5.1 => 5.8.3 
    @mui/lab: ^5.0.0-alpha.74 => 5.0.0-alpha.85 
    @mui/material: ^5.8.1 => 5.8.3 
    @mui/private-theming:  5.8.0 
    @mui/styled-engine:  5.8.0 
    @mui/system:  5.8.3 
    @mui/types:  7.1.3 
    @mui/utils:  5.8.0 
    @mui/x-data-grid:  5.12.1 
    @mui/x-data-grid-pro: ^5.11.1 => 5.12.1 
    @mui/x-date-pickers: ^5.0.0-alpha.6 => 5.0.0-alpha.6 
    @mui/x-date-pickers-pro: ^5.0.0-alpha.6 => 5.0.0-alpha.6 
    @mui/x-license-pro: ^5.12.2 => 5.12.2 
    @types/react: ^18.0.9 => 18.0.12 
    react: ^18.1.0 => 18.1.0 
    react-dom: ^18.1.0 => 18.1.0 
    typescript: ^4.7.2 => 4.7.3 
</details>

### Order ID 💳 (optional)

39694

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #5231
Fix #5284

I remove the `skip` on the date range picker keyboard setting. But it does not catch the bug of the key pressed ignored, so I added another one

I ensured that the input value is reset only when the `rawValue` is modified by looking at how `useAutocomplete` works

### CODE REVIEW

**Review by N1mi1 — APPROVED** [review]
Looks like a good bug fix.
Probably the bug caused by the remaining debts mentioned [here](https://github.com/mui/mui-x/blob/4306ad1c6f48bf080df980561ff241e8b126280b/packages/x-date-pickers/src/internals/hooks/useMaskedInput.tsx#L71) (Implement with controlled vs uncontrolled `rawValue`)

Could not reproduce the bug in the deployed Netlify link.

**Comment by subvertallchris** [comment]
We just started running into this. I see it's happening on the demo page in the docs, too. https://mui.com/x/react-date-pickers/date-range-picker/#basic-usage

Are there any good workarounds that effected folks can use in the meantime?

**Comment by JonathanGuo** [comment]
We are running into the same issue too. The fix in CSB is working perfectly. Is there any plan to roll out the fix in the next release?

**Review by flaviendelangle — APPROVED** [review]

**Comment by alexfauquette** [comment]
Will be in the next release

**Pull request merged**
