### PR TITLE
[DateRangePicker] Fix missing clearable and clearText props

### PR DESCRIPTION
**Pull request by zigang93**
fix https://github.com/mui/mui-x/issues/4503

currently I am using free version of DateRangePicker from @mui/lab ^5.0.0-alpha.69
can I push the fix to old mui lab ?

### CODE REVIEW

**Comment by zigang93** [comment]
I think I should make PR at https://github.com/mui/material-ui

**Comment by zigang93** [comment]
@flaviendelangle can you help me on review this?

**Comment by alexfauquette** [comment]
Here is a code sandbox to test the fix

https://codesandbox.io/s/basicdatepicker-material-demo-forked-4l3pdk?file=/demo.tsx

**Comment by zigang93** [comment]
> Here is a code sandbox to test the fix
> 
> https://codesandbox.io/s/basicdatepicker-material-demo-forked-4l3pdk?file=/demo.tsx

Yea, it is working now

**Comment by m4theushw** [comment]
Hey, thanks for contributing.

In `@mui/lab`, the `DateRangePicker` was a free-of-charge component. However, in MUI X it became part of the Pro plan, which is paid. If your contribution is merged you won't be able to use it unless you buy a license. It would be unfair since you allocated time to prepare this pull request. We propose to offer you a free Pro license key to continue to use the component you helped to improve. Additionally, since the contribution is on files out of the MIT-license scope, you also need to sign a copyright assignment agreement. Could you send an email at x@mui.com so we can send you the document to sign?

**Comment by zigang93** [comment]
> free Pro license key

Hi @m4theushw , Thanks for the offer. I already send out the email.

**Comment by oliviertassinari** [comment]
CLA signed ✅

**Comment by zigang93** [comment]
Hi @m4theushw, 
I had sign the CLA, but I still no receive any license key yet.
btw, this PR will be review soon?

**Review by flaviendelangle — COMMENTED** [review]
Could you add a test in `DesktopDatePicker.test.tsx` checking if when giving `clearable=true` we have a button that can have a custom label with `clearText` and calls `onClear` when pressed ?

**Comment by zigang93** [comment]
@flaviendelangle  I saw line 271 at `DesktopDatePicker.test.tsx` already include the test. the test at line 271 is workable previously?

**Comment by flaviendelangle** [comment]
Oh sorry, your fix is on the Date Range Picker, `DesktopDateRangePicker.test.tsx`

**Comment by zigang93** [comment]
@flaviendelangle I had done the unit test, please have a look.

**Review by flaviendelangle — APPROVED** [review]

**Pull request merged**
