### PR TITLE
[core] Use type imports for theme augmentation

### PR DESCRIPTION
**Pull request by Janpot**
These are importing from a `.d.ts` file, meaning, here is no code to import from, this can confuse build tools such as in https://github.com/mui/mui-x/pull/14234. Best to either use `.ts` files, or use a `type` import.

Question: Any reason to not just use `.ts` files? These manual type declarations, while supported, feel a bit like an anti-pattern to me.

### CODE REVIEW

**Comment by alexfauquette** [comment]
> Question: Any reason to not just use .ts files? These manual type declarations, while supported, feel a bit like an anti-pattern to me.

@flaviendelangle will have more info, but I think it's just a copy/past from the `@mui/lab` files that got copy/pasted to other components (tree view, and charts)

https://github.com/mui/material-ui/blob/master/packages/mui-lab/src/themeAugmentation/components.d.ts

This would explain why the data-grid uses `.ts` file

**Comment by flaviendelangle** [comment]
> @flaviendelangle will have more info, but I think it's just a copy/past from the @mui/lab files that got copy/pasted to other components (tree view, and charts)

It is :laughing: 
If the grid is using a better format and it works for years, then I see no reason not to migrate to their format :+1:

**Review by LukasTy — APPROVED** [review]
I agree with the change. 👍 
I fear that renaming the files could be a niche breaking change.
We could align the approach and rename files on v8.

Or we can refactor the PR to rename files and merge it to `next` branch when we start working on it. 🤔

**Comment by Janpot** [comment]
> I fear that renaming the files could be a niche breaking change.

I kind of expect the type generation to have the exact same output. Will test.

**Comment by Janpot** [comment]
Looks like the difference in output is:

- this PR:
  output declaration files re-export types with `export type`, instead of just `export`. No js modules are generated
- renaming the files:
  output declaration files re-export with just `export`, just like we currently do. But it also generates empty js modules


I don't see how either of these could lead to a breaking change for the user. The `.ts` method already works for the data grid anyway.

**Comment by Janpot** [comment]
It looks like since I made this PR, they have been updated already on master. Closing this for now, X repo satisfies the needs for https://github.com/mui/mui-x/pull/14234 now. Up to the team if they want to align further.

**Pull request closed without merging**
