### PR TITLE
[DataGrid] Update column menu API `components` -> `slots`

### PR DESCRIPTION
**Pull request by MBilalShafi**
Final part of #6986 
In continuity of #7882 

Updated docs: https://deploy-preview-7999--material-ui-x.netlify.app/x/react-data-grid/column-menu/

**Approach Followed:**

Simple replace `components` and other references to `slots`. Didn't deprecate or list in breaking changes as the API was initially released in alpha.

### CODE REVIEW

**Comment by flaviendelangle** [comment]
Was the decision to entirely drop the `components` prop discussed during a meeting ?

For me the main argument in favor of keeping both was to let people use the same prop name across the whole MUI stack.
If we drop it for the column menu, people will have to use `components` on some places and `slots` on other, to use camel case on some places and not on others.

**Comment by MBilalShafi** [comment]
> Was the decision to entirely drop the components prop discussed during a meeting ?

It wasn't discussed, but the motivation behind going ahead with `slots` only for Column Menu API is to:
1. Keep the API and documentation simple and unified
2. Previously we did not have any such API there (we only introduced it in alpha) so there is very rare to no chances people are using it widely (or there could be breaking changes) so it could be a good opportunity to port the API already to slots pattern.

> For me the main argument in favor of keeping both was to let people use the same prop name across the whole MUI stack.

That's a very good point, but shouldn't the end goal be to port the users to use `slots`, will some users complain if we only support `slots` pattern in new places where we provide similar APIs and only keep deprecated `components` in Grid `rootProps` 🤔

**Comment by flaviendelangle** [comment]
> That's a very good point, but shouldn't the end goal be to port the users to use slots

Yes, but until the MUI Core library support `slots`, people have to use `components` at least on those packages.
My goal was to say that until `slots` is available everywhere, we keep `components` as well to make sure that people don't have to learn two nomenclature.

And then when the MUI Core libraries support `slots`, we can deprecate our `components` props and advertise about the codemod to let people easily migrate from one to the other.

**Comment by DanailH** [comment]
Should we move to merge this?

**Comment by MBilalShafi** [comment]
> For components the scenario is different, users may already have customizations using this prop, but the column menu was recently added.

Could we then assume then if we need to open the interface of `slots/slotProps` to a new component similar to `ColumnMenu` (before v7), we won't add deprecated `components/componentsProps` to it, we only keep supporting `components/componentsProps` in `rootProps`?

**Pull request merged**
