### PR TITLE
[DataGrid] Rename `GridColumnsState['all']` to `GridColumnsState['orderedFields']`

### LINKED ISSUE #5607: [data grid] Rename GridColumnsState `all` field
# Summary

Breaking change for v6.
For more context: https://github.com/mui/mui-x/issues/3287

Rename `GridColumnsState['all']` => `GridColumnsState['orderedFields']`

  https://github.com/mui/mui-x/blob/b778028da23e7455c985c93c53366ab63848ee6d/packages/grid/x-data-grid/src/hooks/features/columns/gridColumnsInterfaces.ts#L15-L17
  
 # Motivation

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #5607

## Breaking changes

```diff
- state.columns.all
+ state.columns.orderedFields
```

### CODE REVIEW

**Review by cherniavskii — APPROVED** [review]
This PR doesn't introduce any breaking changes in our public API, right?

**Comment by DanailH** [comment]
> This PR doesn't introduce any breaking changes in our public API, right?

am It does change the state structure, that's why I marked it as a breaking change. I've updated the description.

**Comment by cherniavskii** [comment]
@DanailH should we add it to https://next.mui.com/x/migration/migration-data-grid-v5/ then?

On the other hand, in our docs we mention that `state` is not considered a public API https://next.mui.com/x/react-data-grid/state/#direct-selector-access

**Comment by DanailH** [comment]
@cherniavskii true, I'm not sure if it's needed to add this to the migration page. The other PR with the deprecated APIs will need a docs update. I'll do that.

**Pull request merged**
