### PR TITLE
[DataGridPro] Fix the height of the printed container

### LINKED ISSUE #3820: [data grid] Print export does not work well with the tree data
### Current behavior 😯

The print export is not complete when using the tree data has open row 

- Go to this code sandbox: https://codesandbox.io/s/treedatafullexample-material-demo-forked-0j16f?file=/demo.js
- export a print, all the rows are present
- expend a row
- not the print will not show the last row

### The end of the grid
image

### The end of the print
image

You can see the top of the rating stars at the bottom of the print

### Expected behavior 🤔

_No response_

### Steps to reproduce 🕹

_No response_

### Context 🔦

_No response_

### Your environment 🌎

_No response_

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #3820
[Preview](https://deploy-preview-3879--material-ui-x.netlify.app/components/data-grid/export/)

### CODE REVIEW

**Comment by siriwatknp** [comment]
👋 The [migration PR](https://github.com/mui/mui-x/pull/3730) has been merged.

Please follow these steps to make sure that the contents are all updated. (Sorry for the inconvenience)

1. pull latest master from upstream to your branch
2. if your PR has changes on the `*.md` or demo files, you are likely to encounter conflict because all of them have been moved to the new folder.
   2.1 revert the change on those markdown files you did
   2.2 pull latest master from upstream (you should not see conflict)
   2.3 make the changes again at `docs/data/material/*`
3. run `yarn docs:api`
    - you might see the changes in `docs/pages/material/api/*` if your PR touches some of the components
    - it is okay if there is no changes

If you are struggle with the steps above, feel free to tag @siriwatknp

**Comment by flaviendelangle** [comment]
@alexfauquette I struggle to reproduce your issue
But we were using the wrong selector to set the page size, it should have been the top level row count.
Can you tell me if the preview still have your bug ?

**Comment by alexfauquette** [comment]
Yes, the bug is still here. I  made the same codesandbox from your PR:
https://codesandbox.io/s/treedatafullexample-material-demo-forked-pg2db?file=/demo.j

For the bug to occur, you need to open some rows. The more you open, the easiest it is to observe. In the recording, the last row is "Alta Howard (26)". First with open rows it does not appears in the print. If I close them, It appears

Peek 2022-02-10 14-42

**Comment by DanailH** [comment]
@flaviendelangle that one has been sitting in draft since February? Can we close it?

**Comment by flaviendelangle** [comment]
@DanailH at some point I proposed you to have a look but I think we both forgot :laughing: 
It would be nice to find a solution

**Comment by DanailH** [comment]
@flaviendelangle thanks for the reminder. That does sound logical.

**Pull request closed without merging**
