### PR TITLE
[pickers] Update pickers when new value has a distinct timezone

### LINKED ISSUE #7833: Change in datetime equality behavior in @mui/x-date-pickers-pro >=5.0.6
### Order ID 💳

58632

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

https://github.com/mui/mui-x/pull/6618

The above update which changes the method in which datetime equality is calculated. It now uses the rounded epoch second instead of the equality method of the date utils.

At Stem we use Luxon - Luxon equality takes into consideration the zone on its DateTime object. If we change the zone (e.g. through an accompanying zone selector component), this new equality check passes instead of fails, resulting in the rendered string not updating. Do you have any suggested workarounds? We are on MUI v5.

Thank you,
Roland

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>
  System:
    OS: macOS 12.5.1
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.15 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 9.4.1 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Edge: Not Found
    Firefox: 104.0.2
    Safari: 15.6.1
  npmPackages:
    @emotion/react: ^11.8.2 => 11.8.2 
    @emotion/styled: ^11.8.1 => 11.8.1 
    @mui/base:  5.0.0-alpha.72 
    @mui/icons-material: ^5.5.1 => 5.5.1 
    @mui/lab: ^5.0.0-alpha.73 => 5.0.0-alpha.73 
    @mui/material: ^5.5.1 => 5.5.1 
    @mui/private-theming:  5.4.4 
    @mui/styled-engine:  5.5.2 
    @mui/styles: ^5.5.1 => 5.5.1 
    @mui/system: ^5.5.2 => 5.5.2 
    @mui/types:  7.1.3 
    @mui/utils:  5.11.7 
    @mui/x-data-grid:  5.17.21 
    @mui/x-data-grid-premium: ^5.17.21 => 5.17.21 
    @mui/x-data-grid-pro:  5.17.21 
    @mui/x-license-pro:  5.17.12 
    @types/react:  16.9.34 
    react: ^17.0.2 => 17.0.2 
    react-dom: ^17.0.2 => 17.0.2 
    typescript:  4.8.4 
</details>

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #7833

### CODE REVIEW

**Review by flaviendelangle — COMMENTED** [review]
Is there a similar problem on the new fields or is it purely a mask issue ?

**Comment by alexfauquette** [comment]
Good points. It does not seem to be a problem in v6 @stem-ui If you could check v6 is working nice

https://codesandbox.io/s/friendly-wilbur-pjudi8?file=/demo.tsx

**Review by LukasTy — APPROVED** [review]
🙌 Could we maybe add a test case asserting this behaviour and potentially forward-porting it to `next` as well? 🤔

**Comment by stem-ui** [comment]
@alexfauquette , confirmed not an issue in v6

https://codesandbox.io/s/elated-austin-pld75s?file=/demo.tsx

**Pull request merged**
