### PR TITLE
[DatePicker] Fix to pass down `className` prop provided on DatePicker to `renderInput`

### LINKED ISSUE #4942: [DatePicker] `className`s provided via prop are never applied to root element
Not much more to say; the `className` prop is destructured in preparation to apply to the component but never gets used.

https://github.com/mui-org/material-ui/blob/ad2535a8b15f76355f4559dbac02e9cb379269ba/packages/mui-lab/src/internal/pickers/Picker/Picker.tsx#L77

### PR DESCRIPTION
**Pull request by CruseCtrl**

### CODE REVIEW

**Comment by CruseCtrl** [comment]
Actually, this doesn't fix #4292 because that issue is mostly concerned with the `StaticDatePicker`, but I've made the `className` work for the `DatePicker`. But maybe it helps #5112

**Review by m4theushw — COMMENTED** [review]
Thanks for the contribution! The CI is green now.

MUI components forward the `className` prop to the root element. However, the pickers don't have an root element, since they wrap a TextField. With that being said, I don't know if it would be correct to forward the root `className` prop directly to the input. In the other hand, https://github.com/mui/mui-x/issues/4942 is different, the calendar of the StaticDatePicker is the root element and `className` should be spread to it. Do you want to go back and modify the PR so it fixes https://github.com/mui/mui-x/issues/4942?

**Comment by CruseCtrl** [comment]
Thanks @m4theushw. I'm not actually using the `StaticDatePicker`, it's just the `DatePicker` that I'm trying to fix at the moment. It does seem strange that the typescript types currently let you pass in a `className` which never gets used. Would the `TextField` not count as the root element in this case?

**Review by alexfauquette — APPROVED** [review]
I do not manage to understand which problem does it solves

You pass the `DatePicker` props `className` to the `renderInput`. That means you can now do

```jsx
<DatePicker className={myClassName} renderInput={params => <TextField {...params}/>} />
```

Which is the same as

```jsx
<DatePicker renderInput={params => <TextField {...params} className={myClassName} />} />
```

From what I understand, both #4942 and #5112 are about customizing the content of the `Modal`/`Popper` which will not be solved with this PR

---

But it seems to be consistent with the core package. The [Autocomplete](https://github.com/mui/material-ui/blob/master/packages/mui-material/src/Autocomplete/Autocomplete.js#L534:L534) component also do not have a root component. Or to be precise it has a `AutocompeteRoot` which is a `div` wrapping the `renderInput` but do not contain the `Popper`. So this PR seems to be the closest solution

**Review by LukasTy — APPROVED** [review]
LGTM, thank you for the contribution! 🙌 
I've also pushed a tiny change to add same logic to `MobileDatePicker`

**Review by alexfauquette — APPROVED** [review]

**Pull request merged**
