### PR TITLE
[fields] Do not clamp day of month

### LINKED ISSUE #9917: [pickers] Valid leap year day changing in datefields
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

[Date Pickers](https://mui.com/x/react-date-pickers/)

Steps:
1. Enter 02/29/1988 which is a valid day for a leap year
2. Changes 29th to 28th

### Current behavior 😯

changes the day value for a valid leap year

### Expected behavior 🤔

should not change day value

### Context 🔦

Users entering a date of birth may end up submitting the wrong data if they have not noticed the day changed without there input.

### Your environment 🌎

_No response_

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #9917

### CODE REVIEW

**Review by LukasTy — APPROVED** [review]
Nice cleanup on our end.
It's always nice to see more removed lines than added ones. 🙈 😆 
I'd just be hesitant in releasing this change with a patch version as this is quite a noticeable behavior change. 🤔 
What do others think?
cc @joserodolfofreitas

**Comment by flaviendelangle** [comment]
I can wait to be sure that we have a minor-worthy feature before merging this one

**Comment by alexfauquette** [comment]
> I can wait to be sure that we have a minor-worthy feature before merging this one

Do you want to highlight this modification in the changelog?

**Comment by flaviendelangle** [comment]
For me it's a duplicate of the new tests introduced in this PR

**Review by alexfauquette — APPROVED** [review]
ok, it even better reflect the issue

**Pull request merged**
