### PR TITLE
[fields] Fix hours editing on dayjs with timezone and DST

### LINKED ISSUE #9900: TimePicker Field is broken when using timezone Lisbon with 'es' locale
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example:

Steps:
1. Open this CodeSandbox example https://mui.com/x/react-date-pickers/timezone/#day-js-and-timezones
2. Add import for 'es' locale: import "dayjs/locale/es";
3. Add to LocalizationProvider 'es' adapterLocale: adapterLocale={"es"}
4. Change the timezone to  "Europe/Lisbon":
5. You will get a example like this: https://codesandbox.io/s/zen-kilby-2c43j6?file=/Demo.tsx
6. Several errors happen:
6.1. Can't type hours writing numbers.
6.2. When change the hour by pressing arrowup/arrowdown, hours convert to NaN and gets invalid date as result.

### Current behavior 😯

Using the time picker field with keyboard its imposible

### Expected behavior 🤔

Be able  to change the time typing

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
    System:
    OS: Windows 10 10.0.22621
  Binaries:
    Node: 14.18.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.11 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: Not Found
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.188)
  npmPackages:
    @emotion/react: ^11.10.4 => 11.10.4
    @emotion/styled: ^11.10.4 => 11.10.4
    @mui/base:  5.0.0-beta.6
    @mui/core-downloads-tracker:  5.13.7
    @mui/icons-material: ^5.13.7 => 5.13.7
    @mui/lab: ^5.0.0-alpha.135 => 5.0.0-alpha.135
    @mui/material: ^5.13.7 => 5.13.7
    @mui/private-theming:  5.13.7
    @mui/styled-engine:  5.13.2
    @mui/styled-engine-sc: ^5.12.0 => 5.12.0
    @mui/styles: ^5.13.7 => 5.13.7
    @mui/system:  5.13.7
    @mui/types:  7.2.4
    @mui/utils:  5.13.7
    @mui/x-data-grid:  6.9.2
    @mui/x-data-grid-pro: ^6.9.2 => 6.9.2
    @mui/x-date-pickers:  6.9.2
    @mui/x-date-pickers-pro: ^6.9.2 => 6.9.2
    @mui/x-license-pro: ^6.9.0 => 6.9.0
    @types/react: 17.0.30 => 17.0.30
    react: 17.0.2 => 17.0.2
    react-dom: 17.0.2 => 17.0.2
    styled-components: ^5.3.5 => 5.3.5
    typescript: ~4.3.5 => 4.3.5

```
</details>

### Order ID or Support key 💳 (optional)

66837

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes #9900

Using `endOfYear` in the field lead to bugs due to the following inconsistency in dayjs:

```tsx
const today = dayjs.tz(undefined, 'Europe/Lisbon')!;
const endOfYear = today.endOf('year');
console.log(endOfYear.hour())
```

Weirdly, I could not reproduce the dayjs strange behavior on the testing environment :thinking:

### CODE REVIEW

**Review by LukasTy — APPROVED** [review]
It does look like a sound fix.
I can't see what it could break. 🤔 

> Weirdly, I could not reproduce the dayjs strange behavior on the testing environment

You could explore writing an e2e test for this, it should be possible to override the timezone for the browser context. 🤔

**Comment by flaviendelangle** [comment]
> I can't see what it could break.

I think it's a bug inside day.js
I could create an issue in there repo.

____

I'll have a look for an e2e test.

**Comment by flaviendelangle** [comment]
The problem is reproducible in the test env if we set the `TZ` env variable to `Europe/Paris` instead of `UTC`.
I think we should migrate away from `UTC` as a test timezone because it's not a realistic environment.

But I can't change this variable at runtime :/

**Comment by flaviendelangle** [comment]
Created #9909

**Pull request merged**
