### PR TITLE
[DataGrid] Padding removed from header title

### LINKED ISSUE #3668: [DataGrid] Text alignment is wrong
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The horizontal padding in the header is wrong:

Screenshot 2022-01-19 at 19 14 49

https://mui.com/components/data-grid/

### Expected behavior 🤔

Screenshot 2022-01-19 at 19 15 12

https://material.io/components/data-tables

It's done correctly in https://mui.com/components/tables/ and https://ant.design/components/table/

### Steps to reproduce 🕹

_No response_

### Context 🔦

It was raised by a designer on https://mui.zendesk.com/agent/tickets/2094. It's also related it #1623 (about the column resize style)

### Your environment 🌎

v5.2.2

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by valenfv**
Fixes #3668 by removing padding from column header title.

https://deploy-preview-3691--material-ui-x.netlify.app/components/data-grid/

- Before fix:
image

- After fix:

image

### CODE REVIEW

**Comment by valenfv** [comment]
Visual tests are failing due to this change. Previous padding was moving header titles 6px to the right.

**Comment by m4theushw** [comment]
Maybe we also need to move the menu icon a bit to the right to keep the margins equally. I'm adding @DanailH as reviewer because he worked in this part recently.

image

**Comment by oliviertassinari** [comment]
The change looks like a good step forward 👍. I think that it will make customization easier too.

**Comment by DanailH** [comment]
> Maybe we also need to move the menu icon a bit to the right to keep the margins equally. I'm adding @DanailH as reviewer because he worked in this part recently.
> 
> image

I agree we can move it a bit to make the spacings even.

**Comment by valenfv** [comment]
Hello @DanailH ! I tried moving the menu button to the right but I guess we can only move it 4px before it's hover state collides with the divider. 
image

**Comment by DanailH** [comment]
@valenfv can we make them both equal then, the sorting arrows left spacing and the menu button right spacing?

**Comment by valenfv** [comment]
@DanailH Sure! 
Making this change,
```diff
diff --git a/packages/grid/_modules_/grid/components/containers/GridRootStyles.ts b/packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
index 939bbed1..39fc7f81 100644
--- a/packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
+++ b/packages/grid/_modules_/grid/components/containers/GridRootStyles.ts
@@ -133,6 +133,11 @@ export const GridRootStyles = styled('div', {
         marginRight: 'auto',
         marginLeft: -6,
       },
+    [`& .${gridClasses['columnHeader--alignRight']} .${gridClasses.menuIcon}, & .${gridClasses['columnHeader--alignRight']} .${gridClasses.menuIcon}`]:
+      {
+        marginRight: 'auto',
+        marginLeft: -10,
+      },
     [`& .${gridClasses['columnHeader--moving']}`]: {
       backgroundColor: theme.palette.action.hover,
     },
@@ -171,7 +176,7 @@ export const GridRootStyles = styled('div', {
       width: 0,
       visibility: 'hidden',
       fontSize: 20,
-      marginRight: -6,
+      marginRight: -10,
       display: 'flex',
       alignItems: 'center',
     },
```
will make both have the same spacing to the left and right respectively.

image

This change will make the button slide 10px to the right and be consistent with the sorting button.

When the `headerAlign` is center, we won't be able to replicate the same behavior since the items get justified to the center (I think we don't need to change the styling there)

image

 When `headerAlign` is right, we can add a `marginLeft: -10` so we make consistent with the default styling

image

Let me know what you think :) 
Thanks!

**Comment by DanailH** [comment]
@valenfv Yes I think, that was the desired behavior.

**Comment by siriwatknp** [comment]
👋 The [migration PR](https://github.com/mui/mui-x/pull/3730) has been merged.

Please follow these steps to make sure that the contents are all updated. (Sorry for the inconvenience)

1. pull latest master from upstream to your branch
2. if your PR has changes on the `*.md` or demo files, you are likely to encounter conflict because all of them have been moved to the new folder.
   2.1 revert the change on those markdown files you did
   2.2 pull latest master from upstream (you should not see conflict)
   2.3 make the changes again at `docs/data/material/*`
3. run `yarn docs:api`
    - you might see the changes in `docs/pages/material/api/*` if your PR touches some of the components
    - it is okay if there is no changes

If you are struggle with the steps above, feel free to tag @siriwatknp

**Comment by DanailH** [comment]
@valenfv I've updated the solution and resolved the conflicts.

**Comment by valenfv** [comment]
Thank you @DanailH for your time 🙏

**Review by DanailH — APPROVED** [review]

**Pull request merged**
