### PR TITLE
[docs] Fix require context path to avoid duplicate key creation

### PR DESCRIPTION
**Pull request by LukasTy**
Fix discussion: https://mui-org.slack.com/archives/C03SUL8TC1M/p1674819479627859
Based on comment by Olivier: https://mui-org.slack.com/archives/C03SUL8TC1M/p1675012202019609?thread_ts=1674819479.627859&cid=C03SUL8TC1M

[This is](https://github.com/mui/mui-x/commit/a83de42d62e45a452e197492600781e5e38b6146) the only relevant change.

> I faced a similar problem 3 months ago: https://github.com/mui/mui-x/pull/6242. It looks like:
Next.js set resolve.modules for webpack to be modules: [ 'node_modules', '/Users/oliviertassinari/mui-x' ], https://webpack.js.org/configuration/resolve/#resolvemodules. So per https://github.com/webpack/webpack/issues/12087#issuecomment-737532578, we need to do:
```diff
diff --git a/docs/pages/x/api/date-pickers/date-time-picker.js b/docs/pages/x/api/date-pickers/date-time-picker.js
index 2bec19c5b..1f3fd6759 100644
--- a/docs/pages/x/api/date-pickers/date-time-picker.js
+++ b/docs/pages/x/api/date-pickers/date-time-picker.js
@@ -12,7 +12,7 @@ Page.getInitialProps = () => {
   const req = require.context(
     'docsx/translations/api-docs/date-pickers',
     false,
-    /\/date-time-picker(-[a-z]{2})?\.json$/,
+    /\.\/date-time-picker(-[a-z]{2})?\.json$/,
   );
   const descriptions = mapApiPageTranslations(req);
```
> It removes the warning. I think to apply to all the MUI Core API pages as well, we require the files twice (console log req.keys()), once is enough. While investigating, I also noticed that removing the webpack alias solves the warning and doesn't break anything. Maybe something to do as well (relying on TypeScript alias and Babel's plugin alias)

### CODE REVIEW

**Comment by oliviertassinari** [comment]
Does it work well? To update it in http://github.com/mui/material-ui after?

**Review by cherniavskii — APPROVED** [review]
Nice, the issue is gone!

**Comment by LukasTy** [comment]
> Does it work well? To update it in [http://github.com/mui/material-ui](https://github.com/mui/material-ui) after?

Well, we'll merge, test and see if it causes any other issues, but from the initial looks—it fixes the actual root cause as you have pointed out and still works without issues. 👌

**Comment by LukasTy** [comment]
> Does it work well? To update it in [http://github.com/mui/material-ui](https://github.com/mui/material-ui) after?

@oliviertassinari I've looked into `material-ui` case and did not find the same warning being thrown as in `mui-x` 🤔 
Do you still think it's worth applying this change to narrow down the available `context.keys`?

**Comment by oliviertassinari** [comment]
> Do you still think it's worth applying this change to narrow down the available context.keys?

It's better, but is it worth it? 🤔 If it's quick to fix, why not.

**Pull request merged**
