### PR TITLE
[DataGridPremium] Fix Excel date serialization when row grouping is enabled

### PR DESCRIPTION
**Pull request by cherniavskii**
Fixes https://github.com/mui/mui-x/pull/4750/files#r865759432

Codesandbox: https://codesandbox.io/s/datagridpremiumdemo-material-demo-forked-qz67bd

### CODE REVIEW

**Review by alexfauquette — APPROVED** [review]
The fix sound good

Do you have an idea about why typescript do not send a warning when calling `date.getFullYear()` because `date` can be `undefined`?

**Comment by cherniavskii** [comment]
> Do you have an idea about why typescript do not send a warning when calling date.getFullYear() because date can be undefined?

Huh, I have no idea - let me check that

**Comment by cherniavskii** [comment]
Well, `date` is of type `any` - so any fields/methods can be accessed.
We can use `api.getCellParams<any, Date>(id, column.field)`.

But thinking about it further - should we use `unknown` for `GridCellParams` `value`, since we don't actually know what's there?

https://github.com/mui/mui-x/blob/936655f43787892d8168ae87b0879968d38247fb/packages/grid/x-data-grid/src/models/params/gridCellParams.ts#L9-L21

cc @flaviendelangle

**Review by flaviendelangle — COMMENTED** [review]
Did we check that the other types are working correctly with undefined values ?

**Comment by flaviendelangle** [comment]
> But thinking about it further - should we use unknown for GridCellParams value, since we don't actually know what's there?

Ideally yes
But it caused a lot of TS errors when I tried to change the default value. So I did not wanted to do a typing BC that massive before v6.

It would be interesting to dive deeper. Maybe we could set the default generic to `unknown` in methods like `getCellParams` but not on `GridCellParams`.

**Comment by cherniavskii** [comment]
> Did we check that the other types are working correctly with undefined values ?

They are not processed in any way, so if it's undefined - cell will be empty in excel file

**Review by flaviendelangle — APPROVED** [review]

**Comment by cherniavskii** [comment]
> But it caused a lot of TS errors when I tried to change the default value. So I did not wanted to do a typing BC that massive before v6.

Sounds like a good candidate for v6 changes.
What do you think?

**Comment by flaviendelangle** [comment]
We need to check if it's viable but if it is yes

I think I remember it causes problem when you tried to pass a `GridCellParams<SomeTypedModel>` to a method expecting `GridCellParams<unknown>`, it could crash in some scenario.
But tbh I would have to spend some time playing with it.

**Pull request merged**
