### PR TITLE
[docs] Add pnpm installation instructions for MUI X

### LINKED ISSUE #9699: [docs] Add pnpm installation instructions
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

Same as https://github.com/mui/material-ui/pull/36650, for consistency of the DX.

### PR DESCRIPTION
**Pull request by richbustos**
Adding the support of pnpm in MUI X 

Fix #9699 

image

https://deploy-preview-9707--material-ui-x.netlify.app/x/react-data-grid/getting-started/

### CODE REVIEW

**Comment by samuelsycamore** [comment]
Love to see this! Don't forget about the installation instructions for the Date Pickers and Charts. There may be other instances of these installation blocks elsewhere, too.

**Review by samuelsycamore — APPROVED** [review]
LGTM!

**Comment by samuelsycamore** [comment]
One thing I notice here is that we don't have a parallel structure for these introductory pages across the three packages: Data Grid and Date Pickers both place this info on the Getting Started page, but for Charts it's in the Overview. We should consider following the established pattern for Charts and create a Getting Started page (in a different PR of course) so the user journey is more predictable.

**Comment by oliviertassinari** [comment]
Nice, I don't see other instances to change

**Pull request merged**
