### PR TITLE
[docs] Move the charts in the sidebar

### PR DESCRIPTION
**Pull request by flaviendelangle**
- [x] Move the charts above the migration section
- [x] Replace the pen with a "NEW" (to be discussed)

### CODE REVIEW

**Comment by alexfauquette** [comment]
I'm not convinced about the "New" since it could let users think those components are stable whereas we are still in alpha.

For me the 🧪 was doing the job of catching the attention with some color and indicate it's not a stable library

image


Since we are on this topic, what would you think about

1. Removing the "Common Components" section. Its content is nearly more helpful than charts pages.
2. Moving API Reference on the top of the WIP components.

Screenshot from 2023-06-30 13-06-53

**Comment by cherniavskii** [comment]
> For me the 🧪 was doing the job of catching the attention with some color and indicate it's not a stable library

Maybe keep the 🧪 emoji **and** add the "New" badge?

**Comment by flaviendelangle** [comment]
I applied both of your proposals :+1:

**Review by alexfauquette — APPROVED** [review]
Thanks :)

**Pull request merged**
