### PR TITLE
[fields] Remove clear button from the tab sequence

### LINKED ISSUE #14587: [pickers] Remove clear button in tab sequence
### Steps to reproduce

Link to live example: (required)

Steps:
1. Open https://mui.com/x/react-date-pickers/date-picker/#clearing-the-value

https://github.com/user-attachments/assets/fb386989-7da6-47e0-910e-8b5dbc4cb044

### Current behavior

The clear button is in the <kbd>Tab</kbd> sequence.

### Expected behavior

The clear button is not in the tab sequence.

### Context

Started to discuss this in https://github.com/mui/mui-x/pull/13289#discussion_r1721293102.

In the autocomplete we ruled to not have it in the tab sequence:

- https://github.com/mui/material-ui/issues/30815#issuecomment-1028935533
- https://github.com/mui/material-ui/issues/30815#issuecomment-2296573576

It would make sense to me to do the same here for the sake of being simple to navigate inside a complex form with the keyboard. The date picker seems simpler to clear than an autocomplete:

- I tab into it. In both cases, everything is selected, so pressing delete once empties the field.
- I have just selected a value. In both cases, I select all + press delete
- I have just selected a value. I spam the delete key, the autocomplete usually has more characters to remove, so is a bit slower.

More on this: https://scottaohara.github.io/clear-text-field-button/.

> The clear button is purposefully not in the tabbing order of the web page. Keyboard users can use the Delete or Backspace keys (or first select all the text field's text and then use these keys) to delete the contents of the text field.

### Your environment

<details>
  <summary><code>npx @mui/envinfo</code></summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

**Search keywords**: -

### PR DESCRIPTION
**Pull request by k-rajat19**
Fixes #14587
clear button should not be in the tab sequence. For more info see [ #14587](https://github.com/mui/mui-x/issues/14587#issue-2520453240) 
Preview : https://deploy-preview-14616--material-ui-x.netlify.app/x/react-date-pickers/date-picker/#clearing-the-value
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by k-rajat19** [comment]
hi @LukasTy @flaviendelangle 
Are we good to go with this change? :)

**Comment by flaviendelangle** [comment]
I'd like @LukasTy opinion on this one, but no problem on my side :+1:

**Comment by k-rajat19** [comment]
Hi @LukasTy,
Are there any blockers to merging this?

**Review by LukasTy — APPROVED** [review]
Thank you for taking care of it. 🙏 
Sorry for the delayed review. 🙈 

The approach makes sense to me. 👌 
We support the select all + <kbd>Del</kbd>/<kbd>Backspace</kbd> to remove the value, so, it shouldn't be a surprise to keyboard users.

**Pull request merged**
