### PR TITLE
[DataDrid] Fix `upsertFilterItems` removing filters that are not part of the update

### PR DESCRIPTION
**Pull request by gitstart**
## Description

Closes [11793](https://github.com/mui/mui-x/issues/11793)

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/material-ui/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.

### CODE REVIEW

**Comment by gitstart** [comment]
@MBilalShafi This PR is ready for review

**Review by MBilalShafi — APPROVED** [review]
Thank you @gitstart for your contribution

**Comment by danisaurio** [comment]
Hey guys, do we have an ETA for this patch?|
Thanks!

**Comment by MBilalShafi** [comment]
@danisaurio It's already merged and should be shipped by the end of the week.

**Pull request merged**
