### PR TITLE
[code-infra] Remove usage of `HighlightedCodeWithTabs` through monorepo alias

### PR DESCRIPTION
**Pull request by Janpot**
Chipping away at removing all usage of the monorepo docs alias

Blocked on https://github.com/mui/material-ui/pull/42841

### CODE REVIEW

**Comment by LukasTy** [comment]
Sorry, I already did it in https://github.com/mui/mui-x/pull/13713 🙈

**Comment by Janpot** [comment]
Oh great! Note to myself, don't forget to rebase master before you start 😄

**Comment by Janpot** [comment]
Actually, I also snuck in the import to `HighLightedCodeWithTabs` in this PR in anticipation to https://github.com/mui/material-ui/pull/42841, may as well keep it

**Comment by LukasTy** [comment]
> Actually, I also snuck in the import to `HighLightedCodeWithTabs` in this PR in anticipation to [mui/material-ui#42841](https://github.com/mui/material-ui/pull/42841), may as well keep it

Yeah, thanks, we can do that after the monorepo is bumped. 👍

**Pull request closed without merging**
