### PR TITLE
[DataGrid] Toggle menu on click in `GridActionsCell`

### PR DESCRIPTION
**Pull request by k-rajat19**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes https://github.com/mui/mui-x/issues/15678

### CODE REVIEW

**Comment by k-rajat19** [comment]
@michelengelen, would you like to review this? Argos diff is surprising, but I think we can ignore it.

**Review by arminmeh — APPROVED** [review]

**Comment by michelengelen** [comment]
@arminmeh could you manually create a cherry pick to v7 please?

**Comment by arminmeh** [comment]
Already merged https://github.com/mui/mui-x/pull/15871

**Comment by michelengelen** [comment]
> Already merged #15871

remind me to refresh the page before asking questions like this next time! 🤣

**Pull request merged**
