### PR TITLE
Don't hijack CTRL+ENTER

### PR DESCRIPTION
**Pull request by ilbrando**
Solving #10577 not hijacking CTRL+ENTER.
ENTER is used to select nodes. When in multi select mode CTRL+ENTER could mean to add to the existing selection - this would align with CTRL + mouseclick, so maybe this line 191

`instance.selectNode(event, state.focusedNodeId, true);`
should be changed to
`instance.selectNode(event, state.focusedNodeId, ctrlPressed);`

I have also renamed the variable `flag` to a more meaningful `preventDefaultBehavior`

### CODE REVIEW

**Comment by flaviendelangle** [comment]
Thanks for your contribution, I did a PR (#11481) to fix #10397 that also takes care of your problem.

We no longer stop the propagation of any event and we only prevent the default behavior when we apply some custom behavior.

I also handed the `defaultMuiPrevented` like we have on most core component, you are now able to disable the behavior with Ctrl + Enter as follow:

```tsx
    const handleKeyDown = (event: React.KeyboardEvent & { defaultMuiPrevented?: boolean }) => {
        if (event.key === 'Enter' && (event.ctrlKey || event.metaKey)) {
            event.defaultMuiPrevented = true;
        }
    }

    return (
        <TreeView onKeyDown={handleKeyDown}>
            // Some items
        </TreeView>
    );
```

**Comment by ilbrando** [comment]
I have been trying your suggestion and now CTRL+ENTER is not captured, but the item with focus is selected even when `defaultMuiPrevented` is set to  `true`. Is this intentionally? I would expect that all MUI behavior would be disabled.

**Comment by flaviendelangle** [comment]
Hi,

To make sure we are talking about the same thing, could you provide a working reproduction, this [Codesandbox template](https://codesandbox.io/s/date-and-time-pickers-uj6btq) might be a good starting point.

**Comment by ilbrando** [comment]
Hi again

Take a look at this [codesandbox](https://codesandbox.io/p/sandbox/mui-x-treeview-d5w3tm?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clw9758vi0006356o6ubxfd42%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clw9758vh0002356oa7hb7nay%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clw9758vi0003356o00gh9uy5%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clw9758vi0005356oyzzhi8fx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clw9758vh0002356oa7hb7nay%2522%253A%257B%2522id%2522%253A%2522clw9758vh0002356oa7hb7nay%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clw9758vi0005356oyzzhi8fx%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clw9758vi0004356ocgq5b1ax%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clw9758vi0005356oyzzhi8fx%2522%252C%2522activeTabId%2522%253A%2522clw9758vi0004356ocgq5b1ax%2522%257D%252C%2522clw9758vi0003356o00gh9uy5%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clw9758vi0003356o00gh9uy5%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

**Comment by flaviendelangle** [comment]
Hi,

OK so it's the same reason as for https://github.com/mui/mui-x/issues/9962#issuecomment-2114804362

You need to block it at the item level now.
Here is the [updated Codesandbox](https://codesandbox.io/p/sandbox/mui-x-treeview-forked-rhwx4n?file=%2Fsrc%2FApp.tsx%3A16%2C6)

To avoid passing explicitly `onKeyDown` to every item, you can create a custom wrapper.
You may also want to consider migrating to `RichTreeView` depending on your usecase.

**Comment by ilbrando** [comment]
Thanks, it works :-)

**Pull request closed without merging**
