### PR TITLE
[l10n] Improve Chinese (zh-CN) locale

### PR DESCRIPTION
**Pull request by SakumyZ**
Adds missing translations for Chinese (zh-CN) locale - https://github.com/mui/mui-x/issues/3211.

### CODE REVIEW

**Review by LukasTy — APPROVED** [review]
Thank you for your contribution! 🙏 💯

**Comment by SakumyZ** [comment]
@LukasTy 

Thank you for reviewing my pr and for your suggestion! 
I will run `yarn prettier` and commit the changes as suggested :blush:

**Comment by SakumyZ** [comment]
I have run the `yarn prettier`command, but it seems that there were no changes made to the files

image

@LukasTy please let me know if there's anything else I can do. 🙏

**Comment by SakumyZ** [comment]
> Either try understanding why yarn prettier does not generate changes, or apply the following diff to resolve CI issue. 😉

@LukasTy Thank you for the diif file you provided. 🙏

After I modified it according to the diff file you provided, I ran `yarn prettier` again and it succeeded,  Although I still can’t figure out why running `yarn prettier` directly on my PC has no effect. :frowning:

**Comment by LukasTy** [comment]
> After I modified it according to the diff file you provided, I ran `yarn prettier` again and it succeeded, Although I still can’t figure out why running `yarn prettier` directly on my PC has no effect.

It's probably because you are on the master branch (ideally, you should have created a branch for making the change) and the `pretty-quick` that we run on dev (`yarn prettier`) compares the diff between the `master` branch, which is technically the same in your case. That's why it might have been confused 🤔

**Pull request merged**
