### PR TITLE
[DataGrid] Fix row reorder with cell selection

### LINKED ISSUE #11753: [data grid] Row reordering triggers cell selection process
### Steps to reproduce

Link to live example: https://mui.com/x/react-data-grid/clipboard/ (just add rowReordering to the paste example

Steps:
1. Drag a row
2. Once you finish , move the cursor to the middle of the table
3. You'll have a grid of highlighted cells for selection

### Current behavior

Finishing a row reordering starts cell selection

### Expected behavior

Row reordering shouldn't keep a cell selection mode

Perhaps drag columns shouldn't be selectable, is it possible to disable it from the api?

**Search keywords**: row reordering cell selection
**Order ID**: 82566

### PR DESCRIPTION
**Pull request by PEsteves8**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Fixes #11753

### CODE REVIEW

**Comment by cherniavskii** [comment]
@PEsteves8 thank you for this pull request! Your changes seem to impact the commercially licensed code. For any changes of this nature, we require contributors to sign the MUI’s Contributor License Agreement (CLA). However, I can’t find a CLA signed that could cover these changes. Please follow the steps at https://mui-org.notion.site/CLA-Contributor-License-Agreement-92ece655b1584b10b00e4de9e67eedb0 to sign the document.

**Comment by PEsteves8** [comment]
Alright, just filled the form and sent forward the email to the legal email with a link to this PR. Hopefully, I did everything correctly.

**Comment by zannager** [comment]
CLA signed, thanks.

**Review by cherniavskii — APPROVED** [review]
Thank you!

**Pull request merged**
