### PR TITLE
[fields] Support empty sections

### PR DESCRIPTION
**Pull request by flaviendelangle**
Explore #10279

@LukasTy I would like to have your opinion on this one.
It's clearly pretty niche.

If we want to support it, I'll add some tests.

### CODE REVIEW

**Review by LukasTy — COMMENTED** [review]
This looks like an interesting/niche addition, but it could prove useful in certain scenarios.
It does not seem to cause too much headache code-wise, hence, I'm not against introducing it. 👌 

I've [explored a solution](https://codesandbox.io/s/quirky-kapitsa-wjv495?file=/Demo.tsx) along the lines of the issue authors case and it seems to work well.
The only issue I could see is that after the value is set and you try to change it using the keyboard - the value get's reset.

Have you explored the option of having such support when `selectedSections` is `undefined` or `null`, it could avoid the extra head-ache of having an `empty` section. 🤔

**Comment by flaviendelangle** [comment]
> I've explored a solution along the lines of the issue authors case and it seems to work well.

In your example I can't edit the value, it's throws invalid dates, not sure why.

> Have you explored the option of having such support when selectedSections is undefined or null, it could avoid the extra head-ache of having an empty section

For me the problem is that if we have 0 section (which is the case before this PR), then the whole escaped format is not put in any section as a start or end separator (which is the only way I see to render it).

**Review by LukasTy — COMMENTED** [review]
> In your example I can't edit the value, it's throws invalid dates, not sure why.

With which editing are you having problems?
You can easily edit with the picker and I expect that this is the behavior the issue author is expecting.

The main question is—how do we handle certain editing actions when an `empty` section is selected?
Should we simply disallow all the actions and call it a day? 🤔 😆

**Comment by flaviendelangle** [comment]
https://github.com/mui/mui-x/assets/3309670/342ffde2-d3e2-4c07-9770-1f38431d9761

**Comment by LukasTy** [comment]
My guess was that this is something that the issue author expected as a final result. 🤔 
But I could be mistaken... 🙈 

https://github.com/mui/mui-x/assets/4941090/af5cdb03-969d-47e2-93bc-54d4dffe3f19

**Comment by flaviendelangle** [comment]
I'd be surprised.
Once the value is filled, the behavior is good IMHO
But when there is no value and you try to do a field editing, I don't think it's ever a good option to display "Invalid Date".

**Comment by LukasTy** [comment]
> Once the value is filled, the behavior is good IMHO

It's not fine if you try modifying the value in any way (i.e. Arrows).


> But when there is no value and you try to do a field editing, I don't think it's ever a good option to display "Invalid Date".

It wasn't the best and most clear example. I've replaced the empty format in the mentioned demo from an incorrect `null` to `[Do] - [Do]`.
Maybe now the behavior is more aligned between my expectation, your expectation, and a presumable issue author's expectation? 🤔

**Comment by flaviendelangle** [comment]
I think this matches exactly what I am building internally
So for me we could start by proposing your solution indded :+1:

**Comment by flaviendelangle** [comment]
Closing because the user-land fix proposed by @LukasTy works well

**Comment by LukasTy** [comment]
> Closing because the user-land fix proposed by @LukasTy works well

@flaviendelangle my [suggested](https://github.com/mui/mui-x/pull/10307#pullrequestreview-1621574828) example is based on the changes in this PR, without them such behavior doesn't work.
In other words, this PR is still relevant, especially when we see [more interest](https://github.com/mui/mui-x/issues/10279#issuecomment-1781132476) in it. 🤔

**Comment by flaviendelangle** [comment]
Oh sorry :grimacing: 
Do you need all the changes of this PR ?

**Comment by LukasTy** [comment]
> Do you need all the changes of this PR?

Possibly. Didn't try going the removal route and checking what would be the minimal working scenario, but the example basically relies on the `empty` section support. 🤔

**Comment by flaviendelangle** [comment]
Test added

**Review by LukasTy — APPROVED** [review]
The addition LGTM. 👍 
We could consider adding a demo about such usage, but on the other hand, it can be done when we see at least a second request for something like this, because the situation that needs this seems quite niche. 🤔

**Comment by flaviendelangle** [comment]
I agree that we can wait a little before adding a doc example :+1:

**Pull request merged**
