### PR TITLE
[DataGridPro] Fix column headers alignment

### PR DESCRIPTION
**Pull request by cherniavskii**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

- Fixes https://github.com/mui/mui-x/pull/7760#discussion_r1188514018 (this one was very annoying 😅)
- Fixes https://github.com/mui/mui-x/issues/9495
  - Before: https://codesandbox.io/s/youthful-nightingale-zxm6zc?file=/demo.tsx
  - After: https://codesandbox.io/s/cocky-satoshi-nqlmsl

### CODE REVIEW

**Comment by MBilalShafi** [comment]
So many argos changes 😱 
Was it adding extra spacing for every demo? 🤔

**Comment by cherniavskii** [comment]
> So many argos changes 😱
Was it adding extra spacing for every demo? 🤔

Yep, this is why I left this PR for later 😅

The root of the issue is that the header height is 1px smaller than it should be:
3 header rows x 56px = 168px, but here we have 167px + 1px border

Screenshot 2023-08-17 at 12 40 12

Compensating this 1px difference causes a lot of visual regressions (and some failed unit tests)

**Comment by cherniavskii** [comment]
> So many argos changes 😱
Was it adding extra spacing for every demo? 🤔

Yep, this is why I left this PR for later 😅

The root of the issue is that the header height is 1px smaller than it should be:
3 header rows x 56px = 168px, but here we have 167px + 1px border



Compensating this 1px difference causes a lot of visual regressions (and some failed unit tests)

**Comment by MBilalShafi** [comment]
Alright, this seems like a proper direction to pursue though, thanks for fixing the root problem!

**Comment by MBilalShafi** [comment]
I think #10059 will handle this, should we close this one @cherniavskii?

**Pull request closed without merging**
