### PR TITLE
[fields] Refacto prop drilling in fields

### PR DESCRIPTION
**Pull request by flaviendelangle**

### CODE REVIEW

**Comment by alexfauquette** [comment]
So if I understand correctly the proposal, you define an array of props that are internal props in `SHARED_FIELD_INTERNAL_PROP_NAMES` and other arrays of validation props.

All the other props are forwardedProps.

Those arrays are defined by a `valueType` ("date"; "time", ...) such that splitting props can be done by using the following command:
```js
const { internalProps, forwardedProps } = splitFieldInternalAndForwardedProps(props, valueType)
```

---

I don't see reasons to be opposed to this unified behavior. Are their some drawback you have in mind?

**Comment by flaviendelangle** [comment]
> Those arrays are defined by a valueType ("date"; "time", ...) such that splitting props can be done by using the following command:

The value type allows us to avoid one very weird edge case: what if someone passes a `minTime` to a `DateField` and do expect it to be forwarded to the DOM?
Right now, I don't see any prop that exists for some value type, not on another value type, and that people might want to use themselves on these other value types.
But I handled it just in case, to respect the typing, anything that is not an internal prop for a specific value type is forwarded to the DOM, even if it's an internal prop for other value types.

> I don't see reasons to be opposed to this unified behavior. Are their some drawback you have in mind?

We add a little bit of computation (but that should be negligible given the size of the object)

**Comment by flaviendelangle** [comment]
Ready for review :pray:

**Review by alexfauquette — APPROVED** [review]
Sounds good 👍

**Pull request merged**
