### PR TITLE
[docs-infra] cherry pick of #11805

### PR DESCRIPTION
**Pull request by michelengelen**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

---

cherry picking of #11805

### CODE REVIEW

**Review by LukasTy — COMMENTED** [review]
I'm not sure, just asking: do we need it? 🤔 
Shouldn't the actions on `default` branch be run? 🤷

**Comment by LukasTy** [comment]
> Good question ... I was just wondering why it did not run yet on any closed issue. Thought that might be because it is not on `master`

Yeah, makes sense, I also checked and did not see any failed actions... 🤷

**Review by LukasTy — APPROVED** [review]

**Comment by michelengelen** [comment]
It seems that it is working as expected:

Screenshot 2024-02-08 at 14 16 41

Going to close this PR then! Sry for the confusion @joserodolfofreitas and @LukasTy ! 🙇🏼

**Comment by MBilalShafi** [comment]
Yes, it picks from the default branch, I also wondered on this a bit with the previous workflow. 😄

**Pull request closed without merging**
