### PR TITLE
[data-grid] Make Autocomplete variant in Filters to standard

### PR DESCRIPTION
**Pull request by sai6855**
closes: https://github.com/mui/mui-x/issues/11786

preview: https://deploy-preview-12413--material-ui-x.netlify.app/x/react-data-grid/filtering/

select `is any of` filter from above demo to see updated variant

image

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by sai6855** [comment]
Ping @michelengelen

**Review by michelengelen — APPROVED** [review]
LGTM

**Comment by sai6855** [comment]
@michelengelen I suppose this can be merged?

**Comment by siriwatknp** [comment]
@michelengelen what happened to this PR? should I reopen it in a separate one?

**Comment by michelengelen** [comment]
> @michelengelen what happened to this PR? should I reopen it in a separate one?

I don't know honestly ... might be worth opening again

**Pull request closed without merging**
