### PR TITLE
[l10n] Improve Russian (ru-RU) locale

### PR DESCRIPTION
**Pull request by dastan-akhmetov-scity**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by michelengelen** [comment]
@cherniavskii do you know if this change makes sense?

**Comment by flaviendelangle** [comment]
@cherniavskii we could probably move on with this one

**Review by cherniavskii — APPROVED** [review]

**Comment by MBilalShafi** [comment]
Hey @dastan-akhmetov-scity Could you rebase with the latest `master` branch to resolve the conflicts?
Thanks

**Comment by oliviertassinari** [comment]
I have tried to fix the PR. Using 

```
var cardinalRules = new Intl.PluralRules("ru-RU")
Array.from(new Array(50)).map((x, index) => cardinalRules.select(index))
```

to check accuracy 

SCR-20240525-rajt

**Pull request merged**
