### PR TITLE
[DataGrid] Add `BaseIconButton` component slot

### PR DESCRIPTION
**Pull request by 123joshuawu**
Fixes https://github.com/mui/mui-x/issues/7312

Adds `rootProps.components.BaseIconButton` which by default is `@mui/material/IconButton` and `rootProps.componentsProps?.baseIconButton` to allow overriding the IconButton component within `DataGrid`.

### CODE REVIEW

**Comment by MBilalShafi** [comment]
Thanks @123joshuawu for the PR, can we target it for the `next` branch instead of `master`?
We can backport it to `master` later if needed.

**Comment by 123joshuawu** [comment]
@MBilalShafi Understood, updated the PR to target `next` branch.

**Comment by MBilalShafi** [comment]
@123joshuawu The PR has conflicts, can you rebase with the latest `next`?

**Review by cherniavskii — APPROVED** [review]

**Comment by cherniavskii** [comment]
@123joshuawu thank you for this pull request!
Your changes seem to impact the commercially licensed code. For any changes of this nature, we require contributors to sign the MUI’s Contributor License Agreement (CLA). However, I can’t find a CLA signed that could cover these changes. Please follow the steps at https://mui-org.notion.site/CLA-Contributor-License-Agreement-92ece655b1584b10b00e4de9e67eedb0 to sign the document.

**Review by cherniavskii — CHANGES_REQUESTED** [review]
Let's wait for the CLA

**Comment by gzrae** [comment]
CLA signed, thanks.

**Comment by cherniavskii** [comment]
@123joshuawu Thank you! 🎉

**Pull request merged**
