### PR TITLE
[pickers] Fix `AdapterDayjs` timezone behavior

### LINKED ISSUE #13290: [pickers][DateRangePicker] timezones handled incorrectly with `dayjs` when timezone extensions are enabled
### Steps to reproduce

Link to live example: https://codesandbox.io/p/sandbox/mui-daterangepicker-error-zphn44

Steps:
1. In the date "04/29/2024" change "29" to e.g. "1" or "2" using keyboard (not clicking in calendar)
2. Error: "MUI X: The timezone of the start and the end date should be the same."

Sometimes it works, maybe depending on the initial value. 

### Current behavior

The error appears only when using dayjs timezone extensions (`dayjs.extend(timezone); dayjs.extend(utc);`).

When I put a breakpoint on [this line of code](https://github.com/mui/mui-x/blob/36e6179a96702d0ec1748b501678e542bf64090b/packages/x-date-pickers-pro/src/internals/utils/valueManagers.ts#L66) (rangeValueManager.getTimezone) I can see that one date has a timezone "system" and the other "Europe/Warsaw" (my system timezone), and that raises an exception. 

### Expected behavior

_No response_

### Context

_No response_

### Your environment

x-date-pickers-pro 7.5.1
material 5.15.14
(see codesandbox)

**Search keywords**: DateRangePicker timezone dayjs

### PR DESCRIPTION
**Pull request by LukasTy**
Fixes #13290

The main problem was that in an environment, where `utc` and `timezone` plugins are enabled, but regular dayjs constructor is used, changing value could have resulted in timezone differences.

### Steps to reproduce
- Focus input
- Press <kbd>ArrowDown</kbd> twice
- Observe the thrown exception/error

### Before
https://codesandbox.io/p/sandbox/adapterdayjs-daterangepicker-timezone-error-lqdjgx?file=%2Fsrc%2FApp.tsx

### After
https://codesandbox.io/p/sandbox/adapterdayjs-daterangepicker-timezone-error-fixed-hcz288?file=%2Fsrc%2FApp.tsx

### CODE REVIEW

**Comment by flaviendelangle** [comment]
@LukasTy out of curiosity, what required a e2e test here rather than a unit test?

**Comment by LukasTy** [comment]
> out of curiosity, what required a e2e test here rather than a unit test?

I failed to trigger this case in a unit test.
Besides, we use the `UTC` timezone in them, which might have been a secondary roadblock for using a unit test. 🙈

**Comment by flaviendelangle** [comment]
OK :ok_hand:

**Review by flaviendelangle — APPROVED** [review]
Great fix!

**Pull request merged**
