### PR TITLE
[DataGrid] Fix `GridColTypeDef` value type

### LINKED ISSUE #5165: [DataGrid] `GridColTypeDef` type issue
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I've noticed that `GridColTypeDef` generic doesn't handle value type (`V`) properly:

```ts
const usdPrice: GridColTypeDef<number, string> = {
  type: 'number',
  valueFormatter: ({ value }) => '', // <= `value` is of `any` type here
};
```

### Expected behavior 🤔

I expect `value` to be typed as `number`

```ts
const usdPrice: GridColTypeDef<number, string> = {
  type: 'number',
  valueFormatter: ({ value }) => '', // <= `value` should be of `number` type here
};
```

It works as expected when using `GridColDef`:

```ts
const usdPrice2: GridColDef<any, number, string> = {
  field: 'field',
  type: 'number',
  valueFormatter: ({ value }) => '', // <= `value` is of `number` type here
};
```

### Steps to reproduce 🕹

Steps:

1. Go to https://stackblitz.com/edit/react-6lcl9t?file=demo.tsx,tsconfig.json
2. Hover `value` param and see its type

### Context 🔦

Given `GridColDef` signature:

https://github.com/mui/mui-x/blob/3be50cc8bbc760e76d5b8fdae14894be8d866b4a/packages/grid/x-data-grid/src/models/colDef/gridColDef.ts#L39

it looks like generic type params have wrong order:

https://github.com/mui/mui-x/blob/3be50cc8bbc760e76d5b8fdae14894be8d866b4a/packages/grid/x-data-grid/src/models/colDef/gridColDef.ts#L273

Should it be like this instead?

```diff
- export type GridColTypeDef<V = any, F = V> = Omit<GridColDef<V, any, F>, 'field'> & {
+ export type GridColTypeDef<V = any, F = V> = Omit<GridColDef<any, V, F>, 'field'> & {
```

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by cherniavskii**
Fixes #5165

### CODE REVIEW

**Comment by cherniavskii** [comment]
By the way, is the value typed correctly for `date` and `dateTime` column types?

https://github.com/mui/mui-x/blob/3be50cc8bbc760e76d5b8fdae14894be8d866b4a/packages/grid/x-data-grid/src/colDef/gridDateColDef.ts#L22

Shouldn't it be `Date` instead of `Date | string`?

**Comment by flaviendelangle** [comment]
@cherniavskii there is cleaning to be done
Because in the filtering we do type check to see if its a date or not
But if you pass a timestamp or a stringified date, it does not work

So either we make it work (if you pass a timestamp it displays the date for instance) or we drop the number / string format altogether.

**Comment by cherniavskii** [comment]
> So either we make it work (if you pass a timestamp it displays the date for instance) or we drop the number / string format altogether.

The problem I see with number / string support for `date`/`dateTime` column types is that not every string can be converted to Date object.
I would be in favor of supporting only `Date`. Then users can use `valueGetter` to convert string / number to Date objects.
This is what we state in the docs: https://mui.com/x/react-data-grid/column-definition/#converting-types

Since it never worked as expected for number / string, it shouldn't be considered as a breaking change, right?

**Comment by flaviendelangle** [comment]
> Since it never worked as expected for number / string, it shouldn't be considered as a breaking change, right?

I think so
Maybe worth waiting the alpha just in case and remove the support in filtering.

**Comment by cherniavskii** [comment]
I've added it to v6 list

**Review by flaviendelangle — APPROVED** [review]

**Pull request merged**
