### PR TITLE
[fields] Fix items alignment on multi input range fields

### PR DESCRIPTION
**Pull request by flaviendelangle**
It solves 2 problems:

1. Wrong separator alignment, it is too low
2. Layout shift when selecting all

The new DOM structure is too complex to try to align with the text using `baseline` IMHO

Before

https://github.com/mui/mui-x/assets/3309670/b813217e-1970-4b06-85d4-f427c54364d7

After

https://github.com/mui/mui-x/assets/3309670/41020e1d-0c45-428f-99b8-a0dbec08ac3a

### CODE REVIEW

**Review by michelengelen — APPROVED** [review]
LGTM

**Review by LukasTy — COMMENTED** [review]
It looks like we could just use `center` for the existing behavior as well. 🤔 
The only problem is that `center` vs `baseline` creates a 1px difference, because the height of the separator and the height od the `input` elements differ by that 1px 🙈 
Would you minds instead adding an explicit
```ts
lineHeight: '1.4375em', // 23px
```
to each `Separator` styled component? 🤔

**Comment by flaviendelangle** [comment]
@LukasTy It seems to work well :+1:

**Review by LukasTy — APPROVED** [review]
Nice! 👏

**Pull request merged**
