### PR TITLE
[core] Update license key used for tests

### PR DESCRIPTION
**Pull request by LukasTy**
Follow-up on https://github.com/mui/mui-x/pull/8917.
Once again update the license key for tests.

Or would you suggest having **a public** perpetual key for tests to avoid the need for updating? 🤔

### CODE REVIEW

**Comment by JCQuintas** [comment]
Shouldn't this be a env secret? Then we could have a perpetual one there for the tests.

**Comment by LukasTy** [comment]
> Shouldn't this be a env secret? Then we could have a perpetual one there for the tests.

Great point. 👍 
It could also help with updating if we stick to a subscription license as we wouldn't need to fire a PR to update it. 🙈

**Comment by LukasTy** [comment]
@JCQuintas However, thinking about it more, I'm not sure, which causes more friction—renewing a hard-coded license key or forcing every developer to add a license key to run scripts locally without errors. 🤔 
Simplicity probably triumphs here. 🙈 
I'd love to leave this topic for possible improvement and unblock CI ASAP. 👍

**Review by JCQuintas — APPROVED** [review]

**Comment by JCQuintas** [comment]
Sorry, didn't notice it was blocking ci already 😅

**Comment by JCQuintas** [comment]
Would it be possible to make the tests not require the key? How are the current keys generated? Could we have very short lived keys generated for tests only?

**Comment by LukasTy** [comment]
> Would it be possible to make the tests not require the key?

We'd have the `Watermark` on those tests, Argos diffs wouldn't be the prettiest. 🙈 

> How are the current keys generated?

I generated it using a private MUI tool.

> Could we have very short lived keys generated for tests only?

That's a fascinating idea. Could be worth exploring. 👍 
It's possible with the `@mui/x-license` package.

**Pull request merged**
