### PR TITLE
[charts] Improve performances of Scatter component

### PR DESCRIPTION
**Pull request by flaviendelangle**
I think a first level of optimization would be to limit the amount of looping on the series data.
This array can quickly grow to several hundred / thousand of items.

On `master` we are looping 3 time on the data points (map => filter => map).
This PR combines the first map and filter and add some memoization.

We could map a single time if we generate the React nodes inside the `useMemo`.

### CODE REVIEW

**Review by alexfauquette — APPROVED** [review]
Thanks for the improvement. However, I'm wondering if those are not early optimization.

> This array can quickly grow to several hundred / thousand of items.

Your message triggered my curiosity, so I tried the following:


render two series of N points and see If resizing is laggy. I took resize since it updates the axis range and so rerender all components. The bottleneck seems to be between 10³ and 10⁴. 

But it's more about rendering 10⁴ components than having to do data loop.

For example, I considered setting `min`/`max` on axis such that only 100 points are visible. In such a situation, the first map and filter will loop over the 10⁴ data points, but React will only render 100. The resizing was ok even with 10⁴ data points. So as long as it does not have to render the 10⁴ points, looping on the data seems ok.

**Comment by LukasTy** [comment]
> Thanks for the improvement. However, I'm wondering if those are not early optimization.

JS runtime engines are smart. If a piece of code is being run a lot, they try to optimize its runtime and that could potentially be what is happening here, the engine might be applying the same optimization that Flavien has made here manually. 🤔 
If we know we can write code that results in more optimal runtime performance, why not do it and avoid the need for extra from the engine? 😄

**Comment by alexfauquette** [comment]
I totally agree, perf improvements are nice to have, especially If it's a quick fix. My concern was more about should we spend time on this topic.

**Comment by flaviendelangle** [comment]
Well it depends which optimization we are talking about.
For me, memoizing and avoid looping several time on the dataset is a first level of optimization I think we should always go for because they are quick win not that negligeable on low tier engines.

My approach would be to always follow a few performance rules, like:
- Limit looping several time on the dataset
- Do not always recompute stuff on the dataset when re-rendering (the `getXPosition` method for example)
- ...

And then to wait for more advanced benchmarks before doing more advanced optimizations (avoid to use the spread operator on large arrays for example).

___

> the engine might be applying the same optimization that Flavien has made here manually

The engine clearly do black magic
I would be very impressed if he was able to replace `.filter(...).map(...)` by something not looping twice (because of potential side effects in the `.filter`) but I clearly can't guarantee that he's not doing it.

___


> So as long as it does not have to render the 10⁴ point

But isn't the goal to be able to render thos 10 000 points ?

**Comment by alexfauquette** [comment]
> But isn't the goal to be able to render those 10,000 points ?

Not sure it's a good target, at least not before stable, for two reasons:

1. The interest in so many points is not obvious at first time. The interest is only if you build data-intensive applications, which is the end target but will make more sense once all the basic features will be reached
2. It's more complicated than some computation optimization. For example,
    - Recharts has the same issue around the same magnitude https://codesandbox.io/s/simple-scatter-chart-forked-2xm2jq?file=/src/App.tsx
    - Echarts set its large data set optimization around the same point ([see docs](https://echarts.apache.org/en/option.html#series-scatter.large)) Seems that if you put a large data set, they do some tricks to simplify the display. For example:
        - Points are not individual SVG objects. It's multiple paths drawing hundreds of circles each.

**Comment by flaviendelangle** [comment]
> The interest in so many points is not obvious at first time. The interest is only if you build data-intensive applications, which is the end target but will make more sense once all the basic features will be reached

For that one I kind of disagree
On my sideprojects I quickly reach at least a few thousands points (for the NPM downloads for example).

I do agree that this optimization is not sufficient to render that many points, but I think it's a good start to have some good habits.

**Comment by flaviendelangle** [comment]
To be clear, I'm not asking that we spend hours trying to optimize the performances yet, I think we can just try to grab the low hanging fruits so that when we try to optimize more, the easiest bits will be done.

**Comment by romgrk** [comment]
You could also include the whole result value (aka the JSX children tree) inside the `React.useMemo`, you'd avoid even more looping & recomputing, and lots of object allocations.

Though if your children tree is memoizable and your function is pure, then it would be reasonable to assume that `React.memo`'ing the whole function would yield the same result as `React.useMemo`'ing the data, or data+children.

You could even re-use our new [`fastMemo`](https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/utils/fastMemo.ts).

**Comment by flaviendelangle** [comment]
> We could map a single time if we generate the React nodes inside the useMemo.

Yep, that would be even better performance-wise

**Comment by flaviendelangle** [comment]
I'll merge that one, we can improve later :+1:

**Pull request merged**
