### PR TITLE
[Datagrid] Memoize root props

### LINKED ISSUE #8932: [Datagrid] activate vertical scroll page and checkbox selection causes performances issues
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://codesandbox.io/s/lucid-cloud-oq39yg

Steps:

1. install @mui/x-data-grid ^6.2.1 and react 18.2.0 on a React Typescript project (or see the codesandbox)
2. make a div above the datagrid that collapse in vertical and add 5 rows (the goal is to activate the vertical scroll of the page)
3. activate the collapse option to change the height of the div above the datagrid
4. you can see the problem: this is not "smooth", I think there is some datagrid re-renders because its width has change due to the activation of the vertical scroll in the page, it's really embarrassing in term of performances... I have some messages like "forced reflow" or "click handler take ...ms"
5. if you change the number of rows to 100 you can see the performances issues again when a box is selected, the datagrid generate a 1s latency at each selected checkbox...

### Current behavior 😯

- This is not "smooth", I think there is some datagrid re-renders because its width has change due to the activation of the vertical scroll in the page, it's really embarrassing in term of performances... I have some messages like "forced reflow" or "click handler take ...ms"
- if you change the number of rows to 100 you can see the performances issues again when a box is selected, the datagrid generate a 1s latency at each selected checkbox...

### Expected behavior 🤔

I have search a lot to optimize the datagrid and I have already include all the performances tips that recommended in Mui website for the latest version of the community datagrid, all github closed issues and stackoverflow discussions.. Please help all the people like me who are struggling to optimize this component.. Thanks !!!

### Context 🔦

I NEED to keep a responsive width on the datagrid, an autoHeight and all renderCell methods

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>
@mui/x-data-grid ^6.2.1, react 18.2.0, typescript ^5.0.4, all browsers
</details>

### PR DESCRIPTION
**Pull request by romgrk**
Closes #8932

This PR partially fixes the performance issues in the issue linked above by memoizing the grid root props. Previously, even if the props values were not changing, the destructuring of props into `...themedProps` was creating a new props object at every rerender of `DataGrid`, which triggered a re-render of all `GridRow` components.

The reason why I say that this PR partially fixes the issue is that if the user does something like below, then the props are going to be recomputed at every render because the `slots` object changes at every render, which will trigger all rows to be re-rendered.

```tsx
<DataGrid
  {...someProps}
  slots={{ row: MemoizedRow }}
/>
```

I think that a more thorough and general solution that expands beyond just `GridRow` would be to replace `useGridRootProps()` by a hook that selects & depends on a partial copy of the root props, so that subcomponents that depend on some of the props re-render only when those specific props change, and not when any of the root props change. This could be done in this PR instead but represents a larger investment & change, so I would like to have some thoughts on that.

| Before | After |
| --- | --- |
| Screenshot from 2023-05-10 22-17-21 | Screenshot from 2023-05-10 05-47-22 |

### CODE REVIEW

**Comment by romgrk** [comment]
I've been thinking more about how to solve the problem with `useGridRootProps`: what we need is an equivalent to redux's `useSelector` hook. One easy way to do it would be to use https://github.com/dai-shi/use-context-selector, but that requires a peer dependency on `scheduler. The other way would be to replicate something like what redux does, which goes through https://github.com/facebook/react/tree/main/packages/use-sync-external-store to avoid using the context API.

**Review by cherniavskii — APPROVED** [review]
Looks good to me!
Can you share a before/after demo where the difference can be observed?

**Comment by romgrk** [comment]
Before: https://codesandbox.io/s/compassionate-robinson-isf7co?file=/demo.tsx
After: https://codesandbox.io/s/mystifying-river-xg0k28?file=/demo.tsx

**Comment by oliviertassinari** [comment]
@romgrk What do you think about writing a test case for this? I have tried something in #8974.

**Comment by jdeca-decat** [comment]
@romgrk I always have a lot of latency when selecting checkboxes, I updated @mui/x-data-grid to version 6.4.0. Maybe it's not the version containing the fix?

**Comment by romgrk** [comment]
Sounds good. I've opened a [discussion](https://github.com/mui/mui-x/discussions/9001) (see point 1) for an architectural change that will avoid a lot of re-renders, I will add benchmarks & tests along with that implementation.

**Pull request merged**
