### PR TITLE
[code-infra] Fully resolve imports in ESM target

### PR DESCRIPTION
**Pull request by Janpot**
Stepping stone towards full ESM support. 
This babel plugin replaces imports with their full resolved path + extension.

`./path/to/module` becomes `./path/to/module.js` or `./path/to/module/index.js`, depending on where it resolves to.

See https://github.com/mui/material-ui/pull/43294

### blocked on
- [x] merge https://github.com/mui/material-ui/pull/43294
- [x] replace csbci dependency

### CODE REVIEW

**Comment by Janpot** [comment]
Tried out with the dataGrid through the csbci published packages and no issues found

**Comment by JCQuintas** [comment]
@alexfauquette added you here cause you might have feedback based on #13608

**Comment by Janpot** [comment]
@JCQuintas @alexfauquette This PR doesn't touch the build process of `@mui/x-charts-vendor`. This package (so far) doesn't seem to have any relative imports in its ESM target. It should be ESM compliant.

**Comment by alexfauquette** [comment]
> This PR doesn't touch the build process of @mui/x-charts-vendor.  This package (so far) doesn't seem to have any relative imports in its ESM target. It looks like it's already ESM compliant.

Just to be sure, "this PR does not touch the build process of `@mui/x-charts-vendor`" and "It looks like it's already ESM compliant" are not related.

1. The PR does not impact the package because it is a [dedicated babel config](https://github.com/mui/mui-x/blob/master/packages/x-charts-vendor/.babelrc.js) that is used in the [build script](https://github.com/mui/mui-x/blob/master/packages/x-charts-vendor/scripts/build.js/#L94-L107) 
2. Tt's already ESM compliant because ESM files are fairly simple

```js
// `x-charts-vendor/d3-color` (ESM)
// See upstream license: https://github.com/d3/d3-color/blob/main/LICENSE
//
// Our ESM package uses the underlying installed dependencies of `node_modules/d3-color`
export * from "d3-color";
```

**Review by alexfauquette — APPROVED** [review]
I tried two codesandboxes, and looked at some of the diff in the build folders. The modification looks ok.

**Comment by Janpot** [comment]
1. Yes, the vendor package does its own build, what I add in this PR has no influence in it whatsoever.
2. Yes, it has an exports field and all its relative modules specifiers contain the extension ("all" because there are none 😉)

**Pull request merged**
