### PR TITLE
[DataGrid] Fix `Commodity` and `Employee` CSV export of the `country` column

### LINKED ISSUE #3806: [DataGrid] CSV export does not work for the `Commodity` and `Employee` data sets `country` column
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The `valueFormatter` of a `singleSelect` column can return an object. It is encourage to return one with two properties: value and label such that it works well with `Select` component.

In such case, the csv export display `[object Object]` see [the demo with single select field](https://codesandbox.io/s/exportdefaulttoolbar-material-demo-forked-3hsfw?file=/demo.js)
```csv
Name,Rating,Country,Created on,Is admin?
George Edwards,4,[object Object],12/3/2021,true
Ruth Simmons,2,[object Object],12/20/2021,true
Barbara Greer,5,[object Object],11/22/2021,false
Daisy Morgan,2,[object Object],1/24/2022,true
```

### Expected behavior 🤔

According to the typescript, `valueFormatter` return type is 
```ts
GridCellValue = string | number | boolean | Date | null | undefined | object; 
```

I propose to add a `valueExportFormatter` which return string. The reason is that `valueFormatter` is made for providing data to a React component, which is more flexible than providing data to a csv file with can only handle string

### Steps to reproduce 🕹

Steps:

1. go to the codesandbox https://codesandbox.io/s/exportdefaulttoolbar-material-demo-forked-3hsfw?file=/demo.js
2. export csv
3. country column contains `[object Object]`

### Context 🔦

_No response_

### Your environment 🌎

_No response_

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by DanailH**
Fixes #3806 

I also added a `console.warn` to the `serialiseRow` function to ensure that the developer is notified about this requirement.

### CODE REVIEW

**Review by alexfauquette — APPROVED** [review]
I'm wondering if we could not warn developers as soon as they define a `renderCell` without a `formattedValue`. For those who do not use the export feature or the clipboard copy, it would be on useless warning. But for others, it teaches good practice, highlight the problem before a user do it.

But for now, this is already a good improvement :)

**Review by m4theushw — APPROVED** [review]
Since you're improving the CSV export of the generated data, there're two small things which could be fixed:

- Boolean value are exported as `true` or `false`, which is not good
- The avatar column in the Employee could be removed from the CSV, it's exported as a hex value because of the color 👎

Otherwise #3806 is fixed.

**Comment by DanailH** [comment]
I looked into fixing the 2 issues - after checking I think its best to fix them on the demos we are using rather than in the data hook itself because it may seem weird when someone is playing with the demos and there isn't a clear way how those 2 are done.
For the demos on the export page, these 2 are not visible. I can fix it on the main demo?

**Comment by m4theushw** [comment]
> The avatar column in the Employee could be removed from the CSV, it's exported as a hex value because of the color

This one can be solved by only adding `disableExport` in this column I guess.

> Boolean value are exported as true or false, which is not good

I think we have three paths:
- Update all translations to label the boolean values as yes/no instead of true/false. IHMO true/false is too technical, e.g. is admin: true
- Add custom translations in all demos
- Add a custom `valueFormatter` in all generated `boolean` columns

**Comment by DanailH** [comment]
Ok, I've added `disableExport` to the avatar column in the Employee dataset columns.

Also I changed the default translation for the `booleanCellTrueLabel`, `booleanCellFalseLabel` to `yes` and `no`.

**Pull request merged**
