### PR TITLE
[docs] Fix line-break markdown list

### PR DESCRIPTION
**Pull request by oliviertassinari**

### CODE REVIEW

**Review by LukasTy — APPROVED** [review]
I do agree that the proposed layout is more in line with `li` elements yo be rendered.
I wouldn't go as far to say that it is a bug. 🤔 
The current solution provides for a better visual separation between the different list items.
What do you think @flaviendelangle ? Would you agree that the proposed layout without the wrapping `p` element to increase spacing between elements is more correct and just as well separated?

**Comment by oliviertassinari** [comment]
Would it work if we add one more pixel of margin between the list item by default?

**Comment by LukasTy** [comment]
> Would it work if we add one more pixel of margin between the list item by default?

We should probably opt for multiples of spacing used in theme. And if it is default of 8px, then the next step would probably be 8px instead of 4px, but maybe in this case using `spacing={0.75}` makes sense? 🤔

**Comment by oliviertassinari** [comment]
My thought is that if https://deploy-preview-7899--material-ui-x.netlify.app/x/react-date-pickers/base-concepts/#responsiveness feels too close, we could use 5px instead of 4px

Screenshot 2023-02-13 at 20 55 44

**Comment by LukasTy** [comment]
> My thought is that if https://deploy-preview-7899--material-ui-x.netlify.app/x/react-date-pickers/base-concepts/#responsiveness feels too close, we could use 5px instead of 4px

Sure, having more than 4px margin does make sense, I was just saying that we should probably aim at having multiples of the spacing denominator (8px) and thus the default `li` `marginBottom` is probably set to `0.5` in the theme. Changing it to `0.75` should result in 6px.

**Comment by oliviertassinari** [comment]
Another constrain is the look & feel for single-line items, the gap feels larger with today's 4px.

Screenshot 2023-02-13 at 23 02 29

**Comment by flaviendelangle** [comment]
Agree that 5px is a weird spacing if we have a base unit of 8px.

I added those line break (which are invalid) because 4px feels very compact to me.
If we can test with 6px that would be great.
8px might be a lot on single liner.

**Comment by LukasTy** [comment]
I agree with both the opinions, but I'd say that indeed, going with either 5px or 6px spacing between all `li` elements does seem somewhat excessive. Especially with single line entries even 5px creates a bit of disconnect between each element.
I'd probably just go with what we have now and ask Gerda's opinion on this matter. 🙈 🎨

**Comment by oliviertassinari** [comment]
I looked a bit closer at this:

1. The markdown specs cover what we are noticing in the visual output, it's the notion of **loose list** vs. **tight list**: https://spec.commonmark.org/0.30/#loose
2. When asked on the forum: Why https://talk.commonmark.org/t/why-are-there-even-tight-lists/2301, it's about visual design.

**Pull request closed without merging**
