### PR TITLE
[data grid] boolean filter "is" uses string version of true for determining truthiness

### LINKED ISSUE #10049: [data grid] boolean filter "is" uses string version of `true` for determining truthiness
### Steps to reproduce 🕹

Link to live example on latest version: https://codesandbox.io/s/mui-x-issue-template-forked-s5nzdk?file=/src/App.tsx

### Current behavior 😯

1. First table shows generated data with 50-50 true false.
2. Second table ( with boolean filter value set to `true` (boolean)) shows rows where the value is `false`
3. Third table (with boolean filter value set to `"true"` (string `"true"`)) shows rows where the value is `true`

### Expected behavior 🤔

1. First table shows generated data with 50-50 true false.
2. Second table (with filter value set to `true` (boolean)) shows rows where the value is `true`
3. Third table (with filter value set to `"true"` (string `"true"`)) isn't either accepted as a value, or shows no rows.

### Context 🔦

Looking to use the built in filter for filtering by boolean.

Source of bug https://github.com/mui/mui-x/blob/master/packages/grid/x-data-grid/src/colDef/gridBooleanOperators.ts#L15

### Your environment 🌎

<details>
  <summary><code>npx @mui/envinfo</code></summary>

Command does not run with asdf for me. Browser: latest Chrome. Reproducible on latest MUI version in codesandbox provided.
</details>

### Order ID or Support key 💳 (optional)

72874

### PR DESCRIPTION
**Pull request by shaharyar-shamshi**
fixes #10049

### CODE REVIEW

**Comment by shaharyar-shamshi** [comment]
@romgrk can you kindly check this out

**Review by romgrk — APPROVED** [review]
@cherniavskii In [this comment](https://github.com/mui/mui-x/issues/10049#issuecomment-1681993612) you suggested to make the filter condition `if (filterItem.value == null)`, but it LGTM as `if (!filterItem.value)`, if you think it should be that feel free to add something.

**Comment by shaharyar-shamshi** [comment]
> @cherniavskii In [this comment](https://github.com/mui/mui-x/issues/10049#issuecomment-1681993612) you suggested to make the filter condition `if (filterItem.value == null)`, but it LGTM as `if (!filterItem.value)`, if you think it should be that feel free to add something.

@cherniavskii if you can kindly check

**Comment by shaharyar-shamshi** [comment]
> @cherniavskii In [this comment](https://github.com/mui/mui-x/issues/10049#issuecomment-1681993612) you suggested to make the filter condition `if (filterItem.value == null)`, but it LGTM as `if (!filterItem.value)`, if you think it should be that feel free to add something.

@cherniavskii can you kindly check this

**Pull request merged**
