### PR TITLE
[pickers] Avoid some nested imports in `@mui/utils`

### LINKED ISSUE #9170: [pickers] Unable to import DatePicker V6 components from components library
### Order ID or Support key 💳 (optional)
Order ID - #46063

### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### The problem in depth 🔍

We have a storybook component library where we're using @mui/x-data-grid-pro and @mui/x-date-pickers. We successfully upgraded datagrid to v6, but when trying to upgrade datepicker to '6.0.0' we faced an issue when importing the component from the components library in a separate project.

We have a component in our library that is using DateCalendar and DesktopDatePicker. The component that is causing issues is DesktopDatePicker, but the same is happening with DatePicker, StaticDatePicker and DateField components. If we remove DesktopDatePicker and leave DateCalendar, it works fine.

When running storybook locally there are no issues, the component with the datepicker is working perfectly fine. It is only when we build the components library with rollup, npm link it with the another project locally and import the component there, is when we get the issue. The app is crashing with the following error in console:

image

If we import DatePicker directly from @mui/x-date-pickers in the project, it works fine as well. Also tried importing components in another project and seeing the same issue, so it shouldn't be connected to the project's particular setup.

Could there be an issue with how rollup is building the new datepicker v6 components?

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: Linux 5.15 KDE neon 5.26
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 4.87 GB / 15.51 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 17.9.1 - ~/.nvm/versions/node/v17.9.1/bin/node
    npm: 8.11.0 - ~/.nvm/versions/node/v17.9.1/bin/npm
  Managers:
    Apt: 2.0.9 - /usr/sbin/apt
    pip3: 20.2.4 - ~/anaconda3/bin/pip3
    RubyGems: 3.1.2 - /usr/bin/gem
  Utilities:
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.4.0 - /usr/bin/gcc
    Git: 2.25.1 - /usr/bin/git
  Servers:
    Apache: 2.4.41 - /usr/sbin/apachectl
  Virtualization:
    Docker: 23.0.1 - /usr/bin/docker
  IDEs:
    Nano: 4.8 - /usr/bin/nano
    Sublime Text: 4143 - /usr/bin/subl
    VSCode: 1.76.2 - /usr/bin/code
    Vim: 8.1 - /usr/bin/vim
  Languages:
    Bash: 5.0.17 - /usr/bin/bash
    Perl: 5.30.0 - /usr/bin/perl
    Python: 3.8.5 - /home/reedvl/anaconda3/bin/python
    Python3: 3.8.5 - /home/reedvl/anaconda3/bin/python3
    Ruby: 2.7.0 - /usr/bin/ruby
  Databases:
    SQLite: 3.33.0 - /home/reedvl/anaconda3/bin/sqlite3
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 111.0

```
</details>
Browser used is Chrome

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #9170

### CODE REVIEW

**Review by flaviendelangle — COMMENTED** [review]
Are we sure we want to do this?
For me it's going against what we are trying to achieve in https://github.com/mui/material-ui/issues/35840

**Comment by alexfauquette** [comment]
> Are we sure we want to do this?

Not at all, that's why I asked for your review 😉
But in that case, I've no clue about how to solve the issue

**Comment by flaviendelangle** [comment]
I think the issue is that `@mui/utils` nested imports are files, not folders.
So the build process can not create nested `package.json`, which causes the issue here:

image

vs

image


So for me, the clean fix would be to move all the utils (or at least the one used in other packages) into folders with an `index` file.
@michaldudak I'd like your opinion here. On the core repo, all the imports from `@mui/utils` are from the root, but https://github.com/mui/material-ui/issues/35840 lets me think that's not something we want to keep in the future. Does my proposal make sense?

**Comment by michaldudak** [comment]
I share @flaviendelangle's concerns about not using nested imports (especially when we try to teach other developers to use them). If introducing directories solves the problem, we can do it. In the future, we can explicitly say it's a private package, then reorganize it a bit more (e.g., place all the prop-types utilities into one directory etc.).

**Comment by LukasTy** [comment]
> But if one of you think the fix will take more that 2-3 weeks top, then I think the intermediate step is needed to unlock our users.

This PR has already been open for 2 weeks already. 🙈 
What's 1 or 2 more weeks if it comes to that? 🤷

**Comment by flaviendelangle** [comment]
Here is the PR: https://github.com/mui/material-ui/pull/37586

**Pull request closed without merging**
