### PR TITLE
[docs] Update installation docs

### PR DESCRIPTION
**Pull request by cherniavskii**
# The problem

I find current installation docs misleading. `@mui/material` installation section is supposed to help users that don't have it installed already, but it's missing other necessary dependencies (like `@emotion/react` and `@emotion/styled`) and it doesn't mention other styling engines.

Screenshot 2022-03-22 at 16 52 31

I've been creating few projects from scratch to test data grid with Vite and Next.js. And each time I follow these instructions I end up with missing dependencies warning.

# The solution

I think duplicating `@mui/material` installation instructions here is too much and we should link to the source of truth. This is my proposal:
Screenshot 2022-03-22 at 17 08 52

Preview: https://deploy-preview-4259--material-ui-x.netlify.app/components/data-grid/getting-started/

### CODE REVIEW

**Review by flaviendelangle — COMMENTED** [review]
Fully agree !

**Comment by samuelsycamore** [comment]
Good idea to update this @cherniavskii! Personally, I think this page should explicitly state all steps to install the necessary dependencies. Even though it's potentially redundant, it leads to a better user experience because readers won't have to leave the page and the flow of the document to find what they need. In general, I think it's better to keep the reader in one place as much as possible. The more they have to jump around, the more likely they are to get lost in multiple pages and tabs.

**Comment by m4theushw** [comment]
Maybe include the other dependencies that also need to be installed and add the link to MUI Core for more information?

**Comment by cherniavskii** [comment]
I ended up with duplicating instructions from MUI core, including the link to Style Engine guide

**Review by samuelsycamore — APPROVED** [review]

**Review by flaviendelangle — APPROVED** [review]

**Pull request merged**
