### PR TITLE
[docs] Reorganize the page menu

### PR DESCRIPTION
**Pull request by alexfauquette**
To simplify the distinction between docs pages that are common to most of the components and the components themself, I propose to reorganize the menu. Part of #10075

## Proposal

A first group "common feature" with most used features: validation, lifecycle, and shortcuts

Identify all components in a group

Replace the two accordion by a subsection

## The diff

Screenshot from 2023-08-25 16-34-36

### CODE REVIEW

**Comment by flaviendelangle** [comment]
I like a lot the result.

I don't know if *Common features* should be above or below *Components*
They are less used than some pages from *Components* so maybe we should keep the components on the top to make those pages as accessible as possible.

**Comment by alexfauquette** [comment]
> I don't know if Common features should be above or below Components

I think it depends for which audience we write it.

For new users, I believe Common before Components is better because it forces them to read it (at least the title) before finding the component. So they know those pages exist

For advanced users, the opposite feels more natural: components > features > API

> And how about moving Base concepts inside Common features?

Not sure. For me up to "Base concepts" it is about pages you have to read before trying to use those components. Otherwise, you might spend some time lost. In common features, it's well-scoped features such as validation or shortcuts. If you don't need validation, you can skip this page.

**Review by LukasTy — APPROVED** [review]
The change looks great! 💯 
My only concern is the vertical height, which no longer fits all the pickers menu items on a MacBook 16" screen.

I do agree with Flavien, IMHO, `Common features` would probably make more sense below the `Components` section. 👌 
As for the `Base Concepts`, I'm not sure it needs to end up in the `Common features` section, especially if we move it below the components. 🤔

**Review by flaviendelangle — APPROVED** [review]

**Comment by alexfauquette** [comment]
> My only concern is the vertical height, which no longer fits all the pickers menu items on a MacBook 16" screen.

I don't think it's an issue since it's just moving from "hidden by a click" to "hidden by scroll"

**Review by noraleonte — APPROVED** [review]
Super nice improvement! 🎉 

I also think that `Base concepts` should live on the top of the menu, as an 'outline' of sorts that users would read before diving deep into the docs, not in `Common features`. So I think the current placement of thinks is 💯

**Pull request merged**
