### PR TITLE
[pickers] Improve the typing of the adapter `dateWithTimezone` method

### PR DESCRIPTION
**Pull request by flaviendelangle**
Related to [this discussion](https://www.notion.so/mui-org/eslint-rule-no-non-null-assertion-2c33fce075934ccdbed4927bf61163d4)
This typing imprecision was probably the main cause of `!` usage of the picker codebase.
I did not migrate the `date` method because in v7 it will be removed.

```tsx
# Before
adapter.dateWithTimezone(undefined, 'system') => TDate / null
adapter.dateWithTimezone(null, 'system') => TDate / null
adapter.dateWithTimezone('2022-04-17', 'system') => TDate / null

# After
adapter.dateWithTimezone(undefined, 'system') => TDate
adapter.dateWithTimezone(null, 'system') => null
adapter.dateWithTimezone('2022-04-17', 'system') => TDate
```

### CODE REVIEW

**Review by noraleonte — APPROVED** [review]
Nice improvement! 🎉 LGTM, makes sense 👍

**Comment by Janpot** [comment]
Nice. I don't know the codebase in depth, but in case it could make things simpler, I usually see this sort of problem solved with function overloads instead of generics:

```ts
function dateWithTimezone(value: null, timezone: string): null;
function dateWithTimezone(value: string | undefined, timezone: string): Date;
function dateWithTimezone(value: string | undefined | null, timezone: string): Date | null {
  // ...
}
```

**Comment by flaviendelangle** [comment]
The problem of function overload here is that inside the adapters I would need a lot of casting to make the typing work.
We have 7 adapters implementing this function.

**Comment by Janpot** [comment]
Oh ok, I see, it's implementing the function from an interface. It should still be possible, but there may be more duplication then I anticipated then:

```ts
interface MuiPickersAdapter<T> {
  dateWithTimezone(value: null, timezone: string): null;
  dateWithTimezone(value: string | undefined, timezone: string): T;
  dateWithTimezone(value: string | undefined | null, timezone: string): T | null;
}

class AdapterDate implements MuiPickersAdapter<Date> {
  dateWithTimezone(value: null, timezone: string): null;
  dateWithTimezone(value: string | undefined, timezone: string): Date;
  dateWithTimezone(value: string | undefined | null, timezone: string): Date | null {
    // ...
  }
}
```

**Review by Janpot — APPROVED** [review]

**Comment by flaviendelangle** [comment]
We are using arrow function on the classes because we use `this` a lot and we don't want to risk having the adapter called with another context.
And I struggle to make your approach work with them, my IDE complains that I'm defining the methods several time.

**Comment by flaviendelangle** [comment]
If would probably work indeed :laughing:

**Review by LukasTy — APPROVED** [review]
Really nice improvement! 👍 
All those `!` really scare me. 😱

**Pull request merged**
