### PR TITLE
[core] Update to typescript 4.8.3 (target master)

### PR DESCRIPTION
**Pull request by flaviendelangle**
Equivalent of #5935 but for v5

### CODE REVIEW

**Review by LukasTy — APPROVED** [review]

**Comment by a2441918** [comment]
@flaviendelangle  Is this released? I see that the package has a new change today. But I do still get the same build error.

**Comment by flaviendelangle** [comment]
Which version of the package are your using ?
If you could create a small reproduction case, I don't have the error anymore but maybe I'm missing some specificity of your project.

**Comment by sheuertz** [comment]
Hi,
I'm still getting this issue as well:

```
node_modules/@mui/x-date-pickers/internals/models/muiPickersAdapter.d.ts:2:55 - error TS2344: Type 'TDate' does not satisfy the constraint 'ExtendableDateType'.

2 export declare type MuiPickersAdapter<TDate> = IUtils<TDate>;
                                                        ~~~~~

  node_modules/@mui/x-date-pickers/internals/models/muiPickersAdapter.d.ts:2:39
    2 export declare type MuiPickersAdapter<TDate> = IUtils<TDate>;
                                            ~~~~~
    This type parameter might need an `extends ExtendableDateType` constraint.


Found 1 error in node_modules/@mui/x-date-pickers/internals/models/muiPickersAdapter.d.ts:2
```
These are my @mui dependencies, updated to latest today:

```
"@mui/icons-material": "^5.10.6",
"@mui/material": "^5.10.6",
"@mui/system": "^5.10.6",
"@mui/x-data-grid-pro": "^5.17.3",
"@mui/x-date-pickers-pro": "^5.0.2",
```
On typescript 4.8.3.

Thanks

**Comment by Methuselah96** [comment]
@flaviendelangle Yes, this is still an issue. It looks like the `@ts-ignore` applied [here](https://github.com/mui/mui-x/pull/6136/files#diff-8c6f6e7c8be9899d958dfe13f833e22f917918f7b7f433207745be630577ad0eR3-R5) does not make it to the declaration file.

**Comment by Methuselah96** [comment]
@flaviendelangle Here is a repo with the error: https://github.com/Methuselah96/mui-x-type-issue. The key is setting `skipLibCheck` to `false`. Let me know if there's anything I can do to help move this along. I looked into extending from `ExtendableDateType` everywhere the `TDate` generic is used, but the changes seemed quite extensive, so I figured I check here first.

**Pull request merged**
