### PR TITLE
[DataGrid] Allow to override the default row count component in footer

### PR DESCRIPTION
**Pull request by hungmanhle**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

Closes: #10055

### CODE REVIEW

**Comment by romgrk** [comment]
I'm not sure I would touch the locale content for this, it's not really meant for that. I was thinking more about adding a prop on the footer, and the footer can be replaced/wrapped with `slots` if necessary.

@mui/xgrid Any opinion on an API we could expose to replace the footer total row count label?

**Comment by hungmanhle** [comment]
Hey @cherniavskii, would you mind giving me another review?

**Review by cherniavskii — COMMENTED** [review]
Thanks!
I've extracted it to a slot to make it more consistent with similar customizations 👍🏻

**Review by romgrk — APPROVED** [review]

**Comment by cherniavskii** [comment]
@hungmanhle Thank you!

**Pull request merged**
