### PR TITLE
[l10n] Add Vietnamese (vi-VN) locale

### PR DESCRIPTION
**Pull request by nhannt201**
Add Vietnamese locales

### CODE REVIEW

**Review by LukasTy — COMMENTED** [review]
Thank you for the contribution! 🙏 
Could you please follow the suggested process in this comment: https://github.com/mui/mui-x/pull/9099#issuecomment-1560437483?

**Review by alexfauquette — COMMENTED** [review]
The failing CI is about `yarn prerettier`

**Comment by LukasTy** [comment]
Could you please just run `yarn prettier` and commit the changes? 🙏 
We can't do it for you, because you have opened a PR from your fork's master branch instead of creating a sub-branch. 🙈

**Review by LukasTy — APPROVED** [review]
Thank you for your contribution and patience! 🙏

**Pull request merged**
