### PR TITLE
[infra] Consolidate issue cleanup and support labeling action

### PR DESCRIPTION
**Pull request by michelengelen**
- [ ] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Review by JCQuintas — APPROVED** [review]
🤞

**Comment by oliviertassinari** [comment]
Did this change introduce a regression? The action doesn't remove this section anymore:

SCR-20240806-lvlc

https://github.com/mui/mui-x/issues/14116

**Comment by michelengelen** [comment]
> Did this change introduce a regression? The action doesn't remove this section anymore:

Maybe... i'll check that tomorrow!

**Comment by michelengelen** [comment]
@oliviertassinari ^^ #14132

**Pull request merged**
