### PR TITLE
Update rfc template

### PR DESCRIPTION
**Pull request by bytasv**
Update template as per https://github.com/mui/material-ui/pull/33871 discussion

### CODE REVIEW

**Review by LukasTy — APPROVED** [review]

**Comment by flaviendelangle** [comment]
@bytasv avoid merging in `master`, we moved to the `next` branch
I'll rebase :+1:

**Comment by LukasTy** [comment]
@flaviendelangle Is there a problem merging github issue template into master for immediate usage? 🤔

**Comment by flaviendelangle** [comment]
Since our default branch is `next`, doesn't Github use this one for the templates ?

**Comment by flaviendelangle** [comment]
We seem to have the old one : https://github.com/mui/mui-x/issues/new?assignees=&labels=RFC&template=5.rfc.yml&title=%5BRFC%5D+

**Comment by LukasTy** [comment]
🤦‍♂️ Good point 👍

**Pull request merged**
