### PR TITLE
[pickers] Use renderer interceptor on `DateTimePicker`

### PR DESCRIPTION
**Pull request by LukasTy**
Follow up on the `DateTimeRangePicker` solution with `rendererInterceptor` instead of `dateTimeViewRenderers`.

The BC is two-fold:
1. We no longer expose `dateTimeViewRenderers`;
2. Providing a specific time view renderer (i.e. `renderTimeViewClock`) will no longer revert back to the v5 (v6) behavior, where only date or time view is shown at one time (changed behavior in 1st [demo here](https://mui.com/x/react-date-pickers/date-time-picker/#choose-time-view-renderer))

## Visual BC showcase
| Before | After |
|--------|--------|
| Screenshot 2024-03-20 at 13 58 46 | Screenshot 2024-03-20 at 13 59 07 |

# Changelog

- The `DesktopDateTimePicker` view rendering has been optimized by using the same technique as for `DesktopDateTimeRangePicker`.
  - The `dateTimeViewRenderers` have been removed in favor of reusing existing time view renderers (`renderTimeViewClock`, `renderDigitalClockTimeView` and `renderMultiSectionDigitalClockTimeView`) and date view renderer (`renderDateViewCalendar`).
  - Passing `renderTimeViewClock` to time view renderers will no longer revert to the old behavior of rendering only date or time view.

### CODE REVIEW

**Review by flaviendelangle — COMMENTED** [review]
image

Probably a nitpick, but the icon to switch time views overlap with the clock

**Review by flaviendelangle — APPROVED** [review]
Nice improvement!
Nothing breaking here?

**Comment by LukasTy** [comment]
> Probably a nitpick, but the icon to switch time views overlap with the clock

I've checked and it seems that the explicit `width: 'auto'` was not needed.
[I've removed it](https://github.com/mui/mui-x/pull/12441/commits/f9d5384ace3a6c068098e01c4a5c56780146c7ee) to avoid this problem.

> Nice improvement!
Nothing breaking here?

1. The removal of `dateTimeViewRenderers`
2. The fact that adding `renderTimeViewClock` will no longer render `DesktopDateTimePicker` in a v5 manner (only date or time view is visible at a single point in time)

@flaviendelangle I've updated the PR description, could you check it? 🤔

**Comment by flaviendelangle** [comment]
@LukasTy I think this would be more complete:

> The dateTimeViewRenderers have been removed in favor of reusing existing timeViewRenderers.

=>

> The dateTimeViewRenderers have been removed in favor of reusing existing time view renderers (`renderTimeViewClock`, `renderDigitalClockTimeView` and `renderMultiSectionDigitalClockTimeView`) and date view renderers (`renderDateViewCalendar`).


And a diff example would probably be a nice addition, both for the changelog and the migration guide

**Comment by flaviendelangle** [comment]
> Though, I'm not sure what kind of diff we could provide here... 🤷

True, it's not great to have a BC without a clear diff but maybe it's too much of an headache here

**Pull request merged**
