### PR TITLE
[DataGrid] Set default `GridCellParams['value']` type to `unknown`

### PR DESCRIPTION
**Pull request by cherniavskii**
Closes https://github.com/mui/mui-x/issues/5614

#### Breaking changes

- The default type of `GridCellParams['value']` was changed from `any` to `unknown`.

### CODE REVIEW

**Comment by cherniavskii** [comment]
There are more places where `any` is used for the value or row model, but I'm not sure if we should aim for using `unknown` everywhere.
If you have a strong opinion on this - please let me know.

**Comment by TheRealCuran** [comment]
> There are more places where `any` is used for the value or row model, but I'm not sure if we should aim for using `unknown` everywhere. If you have a strong opinion on this - please let me know.

Yes, please! As I wrote in https://github.com/mui/mui-x/issues/5614#issuecomment-1236883265 is usually a bad idea. The ESLint rule https://typescript-eslint.io/rules/no-explicit-any/ explains why. Basically: `any` deactivates a lot of type checking and thus forgoing one of the big advantages of using TypeScript.

**Comment by cherniavskii** [comment]
Thanks @TheRealCuran 

> any deactivates a lot of type checking and thus forgoing one of the big advantages of using TypeScript

I agree, but I feel like `unknown` is not a silver bullet though.
I've tried to use `unknown` for the user-provided data by default while allowing passing a generic with a specific type:
```tsx
declare let params: GridCellParams;
params.value // unknown
declare let params2: GridCellParams<number>;
params2.value // number
```

But it doesn't work well with contravariance.
For example, we pass `GridCellParams` to callbacks in a lot of places. If we use the default `unknown` value, it won't be possible to pass a more specific type to `GridCellParams`:

```tsx
const onCellClick = (params: GridCellParams<number>) => {
  params.value // number
};

<DataGrid
  onCellClick={onCellClick} // Error: Type 'unknown' is not assignable to type 'number'
/>
```

This is why I had to override the default value with `any` in https://github.com/mui/mui-x/pull/6959/files#diff-6162335317cfdd435d100a06c7007b0b950ea9c1487e579428d7c0c5ee6cabd7R218

**Comment by TheRealCuran** [comment]
Just a very quick look (might have time tomorrow to look more closely): wouldn't you want to pass `GridCellParams<T>` and then it should work? Ie. have variable types you can pass down the chain?

**Pull request merged**
