### PR TITLE
[charts] Fix some props not working in xAxis/yAxis

### PR DESCRIPTION
**Pull request by Valyok26**
Fixes [#13371](https://github.com/mui/mui-x/issues/13371)

When props are assigned, priority is bottomAxis -> xAxis -> theme -> defaults.

Also while fixing this, found out that `tickNumber` and `reverse` cannot be assigned with `bottomAxis`, but that's much harder to fix.
Also `position` cannot be set with xAxis/yAxis, but I'm not sure it worth adding lines to ChartsAxis.tsx just to change this behavior.

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by alexfauquette** [comment]
@JCQuintas COuld you review the last commits?

The PR introduces following line, I assume to fix TS
```ts
position: inProps.position || defaultProps.position,
```

The TS issue came from the settings which has type `AxisConfig`, including attributes `position: 'top' | 'bottom' | 'left' | 'right'`.

This last commit makes sure that x-axis settings only get the x-axis attribute (top and bottom) and the y-axis only get the left and right.

**Comment by JCQuintas** [comment]
@alexfauquette looked a bit at @Valyok26 comments that `tickNumber` and `reverse` doesn't work. It seems that for the bottom axis that is expected, since it is a `type:"band"`.

Though `CartesianContextProvider` doesn't take theme into account, even for the Y axis, it doesn't work unless you pass it as a prop. Not sure if it is intentional or we should create an issue. 🤔

**Comment by alexfauquette** [comment]
For `reverse` it's expected. It's not something that only impacts the axis rendering. It impacts the entire rendering of the chart so it can only be set in axis config.

For the `tickNumber` it's more surprising. I will have a second look

**Review by JCQuintas — APPROVED** [review]
Seems to be working as expected. We will look at the `ticksNumber` in another issue. Thanks @Valyok26 for the PR 😃

**Comment by alexfauquette** [comment]
`ticksNumber` has the same issue. it's less obvious, but tick number is used when generating the d3 scale. So it's used during the axis processing, not in the axis rendering.

**Comment by JCQuintas** [comment]
It's unclear what would be our next steps, should we remove the ticksNumber type from theme overrides, or should we make sure we are able to load it from theme?

**Comment by JCQuintas** [comment]
If I think about it, it would probably make sense that the `CartesianContextProvider` takes theme props into account, since props are configuration as well, although it could make things a lot more complex 🙃

**Pull request merged**
