### PR TITLE
[core] Clarify the release strategy

### PR DESCRIPTION
**Pull request by MBilalShafi**
https://github.com/mui/mui-x/pull/16010#discussion_r1898538345

### CODE REVIEW

**Review by DanailH — APPROVED** [review]

**Comment by DanailH** [comment]
We need to port the same cange for master

**Comment by MBilalShafi** [comment]
> We need to port the same cange for master

Yes I guess `needs cherry-pick` label would make the GitHub Action handle it.

**Review by LukasTy — APPROVED** [review]

**Comment by LukasTy** [comment]
> Yes I guess `needs cherry-pick` label would make the GitHub Action handle it, unless there are merge conflicts.

Without `v7.x`, no, it wouldn't. 🙈

**Comment by MBilalShafi** [comment]
@michelengelen Correct me if I'm wrong here but I didn't add `v7.x` label as I assumed it'd make the script think that this PR needs to be cherry-picked on `v7.x` branch and it won't get opened on `master`.

**Comment by michelengelen** [comment]
> @michelengelen Correct me if I'm wrong here but I didn't add `v7.x` label as I assumed it'd make the script think that this PR needs to be cherry-picked on `v7.x` branch and it won't get opened on `master`.

Yes, without this it will open a PR to master.

**Comment by michelengelen** [comment]
> > Yes I guess `needs cherry-pick` label would make the GitHub Action handle it, unless there are merge conflicts.
> 
> Without `v7.x`, no, it wouldn't. 🙈

if you have a PR targeting `master` and add version labels (`v7.x` or `v6.x`) it will open a cherry pick PR to these branches, but if you have a PR targeting a version branch the default action is to open a cherry pick PR to `master`

**Pull request merged**
