### PR TITLE
[pickers] Use `PaperProps` in mobile pickers

### PR DESCRIPTION
**Pull request by LukasTy**
Part of #6218 

To apply styling overrides to both desktop and mobile picker versions popups we currently would need to provide duplicate props:
```jsx
// overrides style in desktop version
PaperProps={{
  sx: {
    '.MuiPickersCalendarHeader-label': {
      fontSize: 'initial',
    },
  },
}}
// overrides style in mobile version
DialogProps={{
  sx: {
    '.MuiPickersCalendarHeader-label': {
      fontSize: 'initial',
    },
  },
}}
```

After these changes passing only the following prop would apply changes to both desktop and mobile pickers popup/dialog:
```jsx
PaperProps={{
  sx: {
    '.MuiPickersCalendarHeader-label': {
      fontSize: 'initial',
    },
  },
}}
```

### CODE REVIEW

**Review by alexfauquette — APPROVED** [review]

**Comment by flaviendelangle** [comment]
This PR is going to be replaced by https://github.com/mui/mui-x/pull/6381 to avoid breaking its api just a few days after the introduction of this api.

I checked that with Lukas

**Comment by alexfauquette** [comment]
Don't know if we should merge it or let's wait for #6381

**Comment by flaviendelangle** [comment]
Too fast :laughing:

**Comment by flaviendelangle** [comment]
Closing this one :+1:

**Pull request closed without merging**
