### PR TITLE
[DataGrid] Fix Space triggering edit mode

### LINKED ISSUE #8171: Datagrid scrolls when pressing space bar if editing enabled
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Steps to reproduce 🕹

Link to live example: https://mui.com/x/react-data-grid/editing/

Steps:
1. Go to the editing documentation page and scroll down to the first example datagrid.
2. Single-click the cell in the Age column of the last visible row in the table (currently) 28 in the fourth row.
3. With this cell 'selected', press the space bar. You will see the datagrid scroll up which is unexpected. Furthermore, the value of the cell is deleted which is also unexpected. 

Another problem with hitting the spacebar:
1. Go to the demo editing page
2. Single click any cell in the Date Created column
3. Press the space bar (don't enter a date)
4. Press enter and the demo will crash

image

### Current behavior 😯

The datagrid jumps/scrolls when an editable cell is selected and the space bar is pushed. Some sort of broken editing state is also entered at the same time.

### Expected behavior 🤔

The datagrid should not scroll and either:
1. Pressing the space bar has no effect
2. Pressing the space bar has the identical effect to a double-click or pressing enter on a selected cell

### Context 🔦

The issue was discovered accidentally. I am not looking to allow editing to start on press of the space bar, I'm just reporting some unexpected behaviour.

### Your environment 🌎

Not relevant, it happens on the datagrid editing docs page: https://mui.com/x/react-data-grid/editing/ 

### Order ID or Support key 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by m4theushw**
Fixes #8171 

<kbd>Space</kbd> is not a key that should trigger the edit mode.

### CODE REVIEW

**Review by MBilalShafi — APPROVED** [review]
When pressing <kbd>space</kbd>, the focus goes to last row of current or next **visual page \***, my natural understanding was that <kbd>Shift</kbd> + <kbd>space</kbd> would do the exact opposite (going to first row or first row of previous visual page) but instead it selected/unselected the row.

Do you think we should review this interaction to make keyboard navigation a bit more easier. 🤔 

\* By visual page I mean currently visible rows without scrolling

**Comment by shantanutheone** [comment]
How to add space in the text itself while in editing mode? It's currently scrolling.

**Comment by laikai0000** [comment]
@m4theushw 

How to add space in the text itself while in editing mode? It's currently scrolling.

**Comment by MBilalShafi** [comment]
> How to add space in the text itself while in editing mode? It's currently scrolling.

It's working for me when in edit mode. Could you attach reproduction steps or a video maybe?

**Comment by laikai0000** [comment]
Hi Bilal
Select the currently available cell and press the spacebar to scroll. I
want to fix the current location.

**Comment by laikai0000** [comment]
hurry up

**Comment by laikai0000** [comment]
When I select that cell and click the spacebar, it starts scrolling. 
How do I fix this?

```
<DataGridPremium
          apiRef={apiRef}
        /......
       onCellKeyDown={handleOnCellKeyDown}
 />
 
 const handleOnCellKeyDown: DataGridPremiumPropsWithoutDefaultValue["onCellKeyDown"] = async (params, event) => {
  if (event.code === "Space") {
            event.preventDefault();


    }
 }      
```

**Comment by MBilalShafi** [comment]
Hey @laikai0000,

You could use `event.defaultMuiPrevented = "true"` to stop the <kbd>Space</kbd> key from triggering the scroll.

```js
const handleCellKeyDown = (_, event) => {
  if (event.key === " ") {
    event.defaultMuiPrevented = true;
  }
}
```

Here's a live example: https://codesandbox.io/embed/fcrv7g?module=/src/Demo.tsx

Does that solve your concern?

**Comment by laikai0000** [comment]
Hi @MBilalShafi 
Thanks for your reply.
But it doesn't seem to solve the problem.
I would like to keep focus and not scroll.
Adding a video.

https://github.com/user-attachments/assets/160bfeec-d0da-4df5-b3e8-9ee72f2b5f15

**Comment by MBilalShafi** [comment]
@laikai0000 I mistakenly attached a different example previously, sorry about that. I've updated the example, can you check again?

It's both keeping the focus and not scrolling

https://github.com/user-attachments/assets/51a297a9-f0bf-4d58-ad7d-e53b9746ddd6

**Comment by MBilalShafi** [comment]
It's working fine for me.
https://github.com/user-attachments/assets/26b86074-becc-4b1f-a7c0-e017259a7879

Can you check again: https://codesandbox.io/p/sandbox/suspicious-payne-qt3wsw ?

**Comment by laikai0000** [comment]
sorry

const {hnadleCellKeyDown} = DatagridEvents(apiRef);

<DataGridPremium
   apiRef={apiRef}
   onCellKeyDown={handleCellKeyDown)
   />

* datagrid-event.ts*
 export const  DatagridEvents =
(apiRef:React.MutableRefObject<GridApiPremium>) => {
    const handleCellKeyDown:
DataGridPremiumPropsWithoutDefaultValue["onCellKeyDown"] = async (params,
event) => {
     if(event.key === ' ') {
       event.defaultMuiPrevented = true;
       apiRef.current.startCellEditMode({id: rowId, field: field});
     }
    }
    return {
       handleCellKeyDown,
    }
}
Select the currently available cell and press the spacebar to scroll.

**Pull request merged**
