### PR TITLE
[l10n] Improve Russian (ru-RU) locale

### PR DESCRIPTION
**Pull request by wensiet**
Added a clear value locale filed.

- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

### CODE REVIEW

**Comment by wensiet** [comment]
#locale #russian

**Review by LukasTy — APPROVED** [review]
Thank you for your contribution! 🙏 
I've ran `l10n` and pushed the necessary changes. 😉

**Comment by MBilalShafi** [comment]
Could've been a test for auto cherry-pick 🙈

**Comment by LukasTy** [comment]
> Could've been a test for auto cherry-pick 🙈

Could it?
It was targeting master. 🤔

**Pull request merged**
