### PR TITLE
v6.20.3

### PR DESCRIPTION
**Pull request by KenanYusuf**

### CODE REVIEW

**Review by flaviendelangle — APPROVED** [review]

**Comment by KenanYusuf** [comment]
Need to update the package version numbers. Not sure what is going on, but we have some packages on `6.20.1` and `6.20.2`, but as i understand they should all be on the same version?

**Comment by flaviendelangle** [comment]
> Need to update the package version numbers. Not sure what is going on, but we have some packages on 6.20.1 and 6.20.2, but as i understand they should all be on the same version?

Any package you publish should be on the same version, which is the version of the root `package.json`
But since you don't release every package, not all packages will have this new version

**Comment by LukasTy** [comment]
> Need to update the package version numbers. Not sure what is going on, but we have some packages on `6.20.1` and `6.20.2`, but as i understand they should all be on the same version?

Yeah, in this case, it seems that you only need to bump the root and `x-data-grid` related packages.

**Comment by KenanYusuf** [comment]
Understood, thanks @flaviendelangle @LukasTy

**Review by LukasTy — APPROVED** [review]
LGTM. 👏

**Review by MBilalShafi — APPROVED** [review]

**Pull request merged**
