### PR TITLE
[docs] Keep columns section expanded when switching between pages

### PR DESCRIPTION
**Pull request by cherniavskii**
Quick followup on #4600

Before:

https://user-images.githubusercontent.com/13808724/167468001-5e7c4965-de4b-4155-9cf0-1c2b21faee31.mov

After:

https://user-images.githubusercontent.com/13808724/167468024-3eb3aded-b576-4fe8-ac76-431b46a8e688.mov

### CODE REVIEW

**Review by m4theushw — APPROVED** [review]
@flaviendelangle also opened https://github.com/mui/mui-x/pull/4811 fixing this. I leave for both of you to decide who gets credit in the CHANGELOG, although the solution here is smart. I didn't realize we could test only part of the path.

**Comment by flaviendelangle** [comment]
I did not know about the path either
I already merged my PR but feel free to replace with this one if you want.

We should probably add examples in the interface on the core.

**Comment by flaviendelangle** [comment]
I did not know about the path either
I already merged my PR but feel free to replace with this one if you want.

We should probably add examples in the interface on the core.

**Comment by cherniavskii** [comment]
We don't use `MuiPage` type right now, so we don't see JSDoc from core: https://github.com/mui/material-ui/blob/4eef029981b08c77a9c52d0b863e6b5ced279087/docs/src/pages.ts#L17-L20

I'll update the description and make sure `MuiPage` is used in our repo

**Comment by flaviendelangle** [comment]
> We don't use MuiPage type right now, so we don't see JSDoc from core:

I tried to use it but I had a problem and was to lazy to fix it :laughing: 
But yes we should

**Comment by cherniavskii** [comment]
Yeah, it needs to be addressed in core repo, I've created a PR: https://github.com/mui/material-ui/pull/32715

**Pull request merged**
