### PR TITLE
[charts] Add clip-path to avoid charts overflow

### PR DESCRIPTION
**Pull request by alexfauquette**
I'm adding a clip-path rect that matches the border of the axis, such that there is no overflow.

I'm moving back the axis in front of the data content because otherwise, we have either:
- The clipping overflows a bit on the axis line if we do not take into account the axis width.
- There is a tiny gap between the axis line and the data depending on your zoom due to some anti-aliasing/ender optimization if we take into account the axis width.

### CODE REVIEW

**Review by LukasTy — COMMENTED** [review]
I'm not sure that this is the most correct solution for the problem. 🤔 
I've checked some examples and they do not seem to ever do something like this (cutting off points):
Screenshot 2023-05-23 at 17 26 53
Screenshot 2023-05-23 at 17 27 02

https://echarts.apache.org/examples/en/editor.html?c=line-stack
https://www.highcharts.com/docs/advanced-chart-features/stacking-charts

Maybe adding some sort of margin/padding would work? 🤔

**Comment by alexfauquette** [comment]
Thanks for the heads up, I was too focus on the technical aspect

> I've checked some examples and they do not seem to ever do something like this (cutting off points):

It's mostly related to zooming features

- Nivo don't have zoom, and no clipping
- Hight charts have clipping but only applied to line and are. The tooltip mark is not impacted: https://www.highcharts.com/demo/line-time-series
- Echarts let some overflow. That's visible when elements are draggable: https://echarts.apache.org/examples/en/editor.html?c=line-draggable Probably the reason why when zooming, they don't show lines outside of the left/right points.

---

I propose to have a tight clip on line and area. And a loser one on marks (same for scatter)

**Comment by LukasTy** [comment]
> It's mostly related to zooming features
>
> I propose to have a tight clip on line and area. And a loser one on marks (same for scatter)

Gotcha.
That sounds like a nice compromise and possibly something similar to what ECharts are doing:

https://github.com/mui/mui-x/assets/4941090/2aea31f1-b0cb-4ccd-bd9d-74eb544dcffe

**Comment by alexfauquette** [comment]
The new behavior will be easier to see in this demo since it allows to play with axis min/max
https://deploy-preview-9012--material-ui-x.netlify.app/x/react-charts/axis/#axis-sub-domain

**Review by LukasTy — COMMENTED** [review]
The solution is better, but still not idea, because it often cut's off part of a point. 🙈 
Screenshot 2023-05-31 at 11 34 58
Screenshot 2023-05-31 at 11 35 11
Screenshot 2023-05-31 at 11 35 39
Screenshot 2023-05-31 at 11 36 14

**Comment by alexfauquette** [comment]
> The solution is better, but still not ideal, because it often cuts off part of a point. see_no_evil

It took the following path to answer this issue:

- Remove the clipping path for dots (scatter chart and  line marks) such that I don't have the problem of setting a limit anymore
- Instead, filter items. They are not displayed if they are strictly outside of the axis domain.
- Redo the line marks interaction. The zooming aspect was not elegant. I moved to a color inversion like in [Recharts](https://recharts.org/en-US/examples/DashedLineChart)

**Review by LukasTy — APPROVED** [review]
Great work! 💯 🚀 

Screenshot 2023-06-01 at 13 35 00

- Is the removal of the mark (point) elements expected here?
- the area in the red rectangle could deserve a task on it's own - handle the scale styling so that the text does not overlap the line


https://github.com/mui/mui-x/assets/4941090/37df5c09-a96f-4fef-93c6-edef3eb90a6c

IMHO, these point colors deserve a look from the design side (cc @gerdadesign @noraleonte).
I do not find the opaque inversion to be the most optimal solution, imho, the current solution looks a bit better.
Maybe we could use the same color technique as for the opaque lines? Initially, the inside of a point would be more opaque, but when hovering that would be inverted. Or vice-versa... 🤷 

IMHO, it looks excessively strange/expressive in this particular chart. 🙈 
Screenshot 2023-06-01 at 13 53 33

P.S. It's not something blocking this PR, but probably the first topic that would be great to get feedback from design side. 👍

**Pull request merged**
