### PR TITLE
[Data grid] Fix number of rows to display for page size options with negative value

### PR DESCRIPTION
**Pull request by kalyan90**
- [x] I have followed (at least) the [PR section of the contributing guide](https://github.com/mui/mui-x/blob/HEAD/CONTRIBUTING.md#sending-a-pull-request).

This PR is created to address https://github.com/mui/mui-x/issues/14276

Unable to attach labels to the PR, can someone please help with attaching the labels

### CODE REVIEW

**Comment by kalyan90** [comment]
@romgrk can you please look at these changes when you have time?

**Comment by kalyan90** [comment]
@michelengelen can you please help with review for this PR?

**Review by romgrk — APPROVED** [review]
One small adjustment, could you add a note about this behavior somewhere in the docs?

Also maybe just settle on using `-1` strictly rather than any negative value, imho it's more clear.

**Comment by kalyan90** [comment]
@romgrk addressed the comments, please review you again when you get sometime.
also please merge if everything is okay, I don't have write access to the repo.

**Pull request merged**
