### PR TITLE
[pickers] Pass the generics to the components in the theme augmentation

### PR DESCRIPTION
**Pull request by toruticas**
This pull request drills the base theme by using the generic of ComponentsOverrides.

Motivation:
When overriding global themes, I want to use the override values of the palette, but once the type definition of date picker components doesn't pass by the base theme, the theme will always be considered unknown.

```
const theme = createTheme({
  palette: {
    primary: {
      main: purple[500]
    }
  },
  components: {
    MuiCalendarPicker: {
      styleOverrides: {
        root: ({ theme }) => ({
          backgroundColor: theme.palette.primary.main
          //               /\ (parameter) theme: unknown
        })
      }
    }
  }
});
```

I've also created an example of this issue with code sandbox: https://codesandbox.io/s/elated-violet-1u5qvc?file=/src/App.tsx

### CODE REVIEW

**Comment by cherniavskii** [comment]
Should we do the same for the data grid?
https://github.com/mui/mui-x/blob/11726a297c034a2e907ccd9630aedcd0551be688/packages/grid/x-data-grid/src/themeAugmentation/props.ts#L8

**Comment by flaviendelangle** [comment]
@cherniavskii yeah probably

**Comment by toruticas** [comment]
I'm unfamiliar with the data grid component, but I'll work on it this weekend. Should I create a new PR or add to this one?

Btw guys, what should I do to merge this PR?

**Comment by flaviendelangle** [comment]
@toruticas the CI seems to have a problem, could you rebase on the master branch to see if the CI is passing ?
But yes as soon as the CI is green let's merge it
And do the DataGrid on another one

**Pull request merged**
