### PR TITLE
[data-grid] Remove `minFirstColumn` from `GetHeadersParams` interface

### PR DESCRIPTION
**Pull request by k-rajat19**
usage of `minFirstColumn` was removed in this PR https://github.com/mui/mui-x/pull/10059, so it can be removed completely.

### CODE REVIEW

**Comment by k-rajat19** [comment]
@romgrk could this be merged? :)

**Review by romgrk — APPROVED** [review]

**Comment by k-rajat19** [comment]
can you please take care of the failing tests, if I will push these tests will not run 
also, I am not aware of the context of why they are failing
thanks for your time 🙏

**Comment by k-rajat19** [comment]
Fixed by #14644

**Comment by k-rajat19** [comment]
@romgrk can you please push again 😅?

**Pull request merged**
